// AUTO-GENERATED FILE.
// Source: resources/product-images-mapping.csv
// Do not edit product entries manually.

#[derive(Debug)]
pub(crate) struct BundledProductImage {
    pub product_id: i64,
    pub product_name: &'static str,
    pub file_name: &'static str,
    pub image_url: &'static str,
    pub bytes: &'static [u8],
}

pub(crate) static PRODUCT_IMAGES: &[BundledProductImage] = &[
    BundledProductImage {
        product_id: 1,
        product_name: "Café crème",
        file_name: "bimik-bundled-001_cafe-creme.png",
        image_url: "/uploads/products/bimik-bundled-001_cafe-creme.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-001_cafe-creme.png"),
    },
    BundledProductImage {
        product_id: 2,
        product_name: "Café Nes Nes",
        file_name: "bimik-bundled-002_cafe-nes-nes.png",
        image_url: "/uploads/products/bimik-bundled-002_cafe-nes-nes.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-002_cafe-nes-nes.png"),
    },
    BundledProductImage {
        product_id: 3,
        product_name: "Café Noir",
        file_name: "bimik-bundled-003_cafe-noir.png",
        image_url: "/uploads/products/bimik-bundled-003_cafe-noir.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-003_cafe-noir.png"),
    },
    BundledProductImage {
        product_id: 4,
        product_name: "Café allangé",
        file_name: "bimik-bundled-004_cafe-allange.png",
        image_url: "/uploads/products/bimik-bundled-004_cafe-allange.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-004_cafe-allange.png"),
    },
    BundledProductImage {
        product_id: 5,
        product_name: "Double expresso",
        file_name: "bimik-bundled-005_double-expresso.png",
        image_url: "/uploads/products/bimik-bundled-005_double-expresso.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-005_double-expresso.png"),
    },
    BundledProductImage {
        product_id: 6,
        product_name: "Cappuccino italien",
        file_name: "bimik-bundled-006_cappuccino-italien.png",
        image_url: "/uploads/products/bimik-bundled-006_cappuccino-italien.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-006_cappuccino-italien.png"),
    },
    BundledProductImage {
        product_id: 7,
        product_name: "Cappuccino viennois",
        file_name: "bimik-bundled-007_cappuccino-viennois.png",
        image_url: "/uploads/products/bimik-bundled-007_cappuccino-viennois.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-007_cappuccino-viennois.png"),
    },
    BundledProductImage {
        product_id: 8,
        product_name: "Spanish Coffee",
        file_name: "bimik-bundled-008_spanish-coffee.png",
        image_url: "/uploads/products/bimik-bundled-008_spanish-coffee.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-008_spanish-coffee.png"),
    },
    BundledProductImage {
        product_id: 9,
        product_name: "Café séparé",
        file_name: "bimik-bundled-009_cafe-separe.png",
        image_url: "/uploads/products/bimik-bundled-009_cafe-separe.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-009_cafe-separe.png"),
    },
    BundledProductImage {
        product_id: 10,
        product_name: "Lipton",
        file_name: "bimik-bundled-010_lipton.png",
        image_url: "/uploads/products/bimik-bundled-010_lipton.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-010_lipton.png"),
    },
    BundledProductImage {
        product_id: 11,
        product_name: "Louiza",
        file_name: "bimik-bundled-011_louiza.png",
        image_url: "/uploads/products/bimik-bundled-011_louiza.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-011_louiza.png"),
    },
    BundledProductImage {
        product_id: 12,
        product_name: "Chocolat chaud",
        file_name: "bimik-bundled-012_chocolat-chaud.png",
        image_url: "/uploads/products/bimik-bundled-012_chocolat-chaud.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-012_chocolat-chaud.png"),
    },
    BundledProductImage {
        product_id: 13,
        product_name: "Chocolat ocean",
        file_name: "bimik-bundled-013_chocolat-ocean.png",
        image_url: "/uploads/products/bimik-bundled-013_chocolat-ocean.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-013_chocolat-ocean.png"),
    },
    BundledProductImage {
        product_id: 14,
        product_name: "Thé Petit",
        file_name: "bimik-bundled-014_the-petit.png",
        image_url: "/uploads/products/bimik-bundled-014_the-petit.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-014_the-petit.png"),
    },
    BundledProductImage {
        product_id: 15,
        product_name: "Thé Moyen",
        file_name: "bimik-bundled-015_the-moyen.png",
        image_url: "/uploads/products/bimik-bundled-015_the-moyen.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-015_the-moyen.png"),
    },
    BundledProductImage {
        product_id: 16,
        product_name: "Thé grand",
        file_name: "bimik-bundled-016_the-grand.png",
        image_url: "/uploads/products/bimik-bundled-016_the-grand.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-016_the-grand.png"),
    },
    BundledProductImage {
        product_id: 17,
        product_name: "Iced coffee",
        file_name: "bimik-bundled-017_iced-coffee.png",
        image_url: "/uploads/products/bimik-bundled-017_iced-coffee.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-017_iced-coffee.png"),
    },
    BundledProductImage {
        product_id: 18,
        product_name: "Iced coffee caramel",
        file_name: "bimik-bundled-018_iced-coffee-caramel.png",
        image_url: "/uploads/products/bimik-bundled-018_iced-coffee-caramel.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-018_iced-coffee-caramel.png"),
    },
    BundledProductImage {
        product_id: 20,
        product_name: "Oulmès Bulles Fruitées Mojito",
        file_name: "bimik-bundled-020_oulmes-bulles-fruitees-mojito.png",
        image_url: "/uploads/products/bimik-bundled-020_oulmes-bulles-fruitees-mojito.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-020_oulmes-bulles-fruitees-mojito.png"),
    },
    BundledProductImage {
        product_id: 21,
        product_name: "Sidi Ali 1/5 L",
        file_name: "bimik-bundled-021_sidi-ali-1-5-l.png",
        image_url: "/uploads/products/bimik-bundled-021_sidi-ali-1-5-l.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-021_sidi-ali-1-5-l.png"),
    },
    BundledProductImage {
        product_id: 22,
        product_name: "Sidi Ali 33 cL",
        file_name: "bimik-bundled-022_sidi-ali-33-cl.png",
        image_url: "/uploads/products/bimik-bundled-022_sidi-ali-33-cl.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-022_sidi-ali-33-cl.png"),
    },
    BundledProductImage {
        product_id: 23,
        product_name: "Jus d’Orange",
        file_name: "bimik-bundled-023_jus-d-orange.png",
        image_url: "/uploads/products/bimik-bundled-023_jus-d-orange.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-023_jus-d-orange.png"),
    },
    BundledProductImage {
        product_id: 24,
        product_name: "Jus de Pomme",
        file_name: "bimik-bundled-024_jus-de-pomme.png",
        image_url: "/uploads/products/bimik-bundled-024_jus-de-pomme.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-024_jus-de-pomme.png"),
    },
    BundledProductImage {
        product_id: 25,
        product_name: "Jus de Banane",
        file_name: "bimik-bundled-025_jus-de-banane.png",
        image_url: "/uploads/products/bimik-bundled-025_jus-de-banane.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-025_jus-de-banane.png"),
    },
    BundledProductImage {
        product_id: 26,
        product_name: "Jus de Mangue",
        file_name: "bimik-bundled-026_jus-de-mangue.png",
        image_url: "/uploads/products/bimik-bundled-026_jus-de-mangue.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-026_jus-de-mangue.png"),
    },
    BundledProductImage {
        product_id: 27,
        product_name: "Jus de Kiwi",
        file_name: "bimik-bundled-027_jus-de-kiwi.png",
        image_url: "/uploads/products/bimik-bundled-027_jus-de-kiwi.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-027_jus-de-kiwi.png"),
    },
    BundledProductImage {
        product_id: 28,
        product_name: "Jus de Fraise",
        file_name: "bimik-bundled-028_jus-de-fraise.png",
        image_url: "/uploads/products/bimik-bundled-028_jus-de-fraise.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-028_jus-de-fraise.png"),
    },
    BundledProductImage {
        product_id: 29,
        product_name: "Panaché",
        file_name: "bimik-bundled-029_panache.png",
        image_url: "/uploads/products/bimik-bundled-029_panache.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-029_panache.png"),
    },
    BundledProductImage {
        product_id: 30,
        product_name: "Panaché fruits secs",
        file_name: "bimik-bundled-030_panache-fruits-secs.png",
        image_url: "/uploads/products/bimik-bundled-030_panache-fruits-secs.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-030_panache-fruits-secs.png"),
    },
    BundledProductImage {
        product_id: 31,
        product_name: "Jus d’Avocat",
        file_name: "bimik-bundled-031_jus-d-avocat.png",
        image_url: "/uploads/products/bimik-bundled-031_jus-d-avocat.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-031_jus-d-avocat.png"),
    },
    BundledProductImage {
        product_id: 32,
        product_name: "Avocat fruits secs",
        file_name: "bimik-bundled-032_avocat-fruits-secs.png",
        image_url: "/uploads/products/bimik-bundled-032_avocat-fruits-secs.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-032_avocat-fruits-secs.png"),
    },
    BundledProductImage {
        product_id: 33,
        product_name: "Citron & Gingembre",
        file_name: "bimik-bundled-033_citron-gingembre.png",
        image_url: "/uploads/products/bimik-bundled-033_citron-gingembre.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-033_citron-gingembre.png"),
    },
    BundledProductImage {
        product_id: 34,
        product_name: "Jus d’Ananas",
        file_name: "bimik-bundled-034_jus-d-ananas.png",
        image_url: "/uploads/products/bimik-bundled-034_jus-d-ananas.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-034_jus-d-ananas.png"),
    },
    BundledProductImage {
        product_id: 35,
        product_name: "Jus de Concombre",
        file_name: "bimik-bundled-035_jus-de-concombre.png",
        image_url: "/uploads/products/bimik-bundled-035_jus-de-concombre.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-035_jus-de-concombre.png"),
    },
    BundledProductImage {
        product_id: 36,
        product_name: "Jus de Pêche",
        file_name: "bimik-bundled-036_jus-de-peche.png",
        image_url: "/uploads/products/bimik-bundled-036_jus-de-peche.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-036_jus-de-peche.png"),
    },
    BundledProductImage {
        product_id: 37,
        product_name: "Jus de Kaki",
        file_name: "bimik-bundled-037_jus-de-kaki.png",
        image_url: "/uploads/products/bimik-bundled-037_jus-de-kaki.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-037_jus-de-kaki.png"),
    },
    BundledProductImage {
        product_id: 38,
        product_name: "Jus de BIMIK",
        file_name: "bimik-bundled-038_jus-de-bimik.png",
        image_url: "/uploads/products/bimik-bundled-038_jus-de-bimik.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-038_jus-de-bimik.png"),
    },
    BundledProductImage {
        product_id: 39,
        product_name: "ZAAZAA",
        file_name: "bimik-bundled-039_zaazaa.png",
        image_url: "/uploads/products/bimik-bundled-039_zaazaa.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-039_zaazaa.png"),
    },
    BundledProductImage {
        product_id: 40,
        product_name: "Salade de fruits",
        file_name: "bimik-bundled-040_salade-de-fruits.png",
        image_url: "/uploads/products/bimik-bundled-040_salade-de-fruits.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-040_salade-de-fruits.png"),
    },
    BundledProductImage {
        product_id: 41,
        product_name: "Mojito Classique",
        file_name: "bimik-bundled-041_mojito-classique.png",
        image_url: "/uploads/products/bimik-bundled-041_mojito-classique.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-041_mojito-classique.png"),
    },
    BundledProductImage {
        product_id: 42,
        product_name: "Mojito fruits rouges",
        file_name: "bimik-bundled-042_mojito-fruits-rouges.png",
        image_url: "/uploads/products/bimik-bundled-042_mojito-fruits-rouges.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-042_mojito-fruits-rouges.png"),
    },
    BundledProductImage {
        product_id: 43,
        product_name: "Mojito bleu Curaçao",
        file_name: "bimik-bundled-043_mojito-bleu-curacao.png",
        image_url: "/uploads/products/bimik-bundled-043_mojito-bleu-curacao.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-043_mojito-bleu-curacao.png"),
    },
    BundledProductImage {
        product_id: 44,
        product_name: "Milk-shake Fraise",
        file_name: "bimik-bundled-044_milk-shake-fraise.png",
        image_url: "/uploads/products/bimik-bundled-044_milk-shake-fraise.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-044_milk-shake-fraise.png"),
    },
    BundledProductImage {
        product_id: 45,
        product_name: "Milk-shake Vanille",
        file_name: "bimik-bundled-045_milk-shake-vanille.png",
        image_url: "/uploads/products/bimik-bundled-045_milk-shake-vanille.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-045_milk-shake-vanille.png"),
    },
    BundledProductImage {
        product_id: 46,
        product_name: "Milk-shake Chocolat",
        file_name: "bimik-bundled-046_milk-shake-chocolat.png",
        image_url: "/uploads/products/bimik-bundled-046_milk-shake-chocolat.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-046_milk-shake-chocolat.png"),
    },
    BundledProductImage {
        product_id: 47,
        product_name: "Frappuccino Chocolat",
        file_name: "bimik-bundled-047_frappuccino-chocolat.png",
        image_url: "/uploads/products/bimik-bundled-047_frappuccino-chocolat.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-047_frappuccino-chocolat.png"),
    },
    BundledProductImage {
        product_id: 48,
        product_name: "Frappuccino Caramel",
        file_name: "bimik-bundled-048_frappuccino-caramel.png",
        image_url: "/uploads/products/bimik-bundled-048_frappuccino-caramel.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-048_frappuccino-caramel.png"),
    },
    BundledProductImage {
        product_id: 49,
        product_name: "Frappuccino Oreo",
        file_name: "bimik-bundled-049_frappuccino-oreo.png",
        image_url: "/uploads/products/bimik-bundled-049_frappuccino-oreo.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-049_frappuccino-oreo.png"),
    },
    BundledProductImage {
        product_id: 50,
        product_name: "Frappuccino Kit kat",
        file_name: "bimik-bundled-050_frappuccino-kit-kat.png",
        image_url: "/uploads/products/bimik-bundled-050_frappuccino-kit-kat.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-050_frappuccino-kit-kat.png"),
    },
    BundledProductImage {
        product_id: 51,
        product_name: "Cocktail exotique (Papaye + Avocat + Panaché)",
        file_name: "bimik-bundled-051_cocktail-exotique-papaye-avocat-panache.png",
        image_url: "/uploads/products/bimik-bundled-051_cocktail-exotique-papaye-avocat-panache.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-051_cocktail-exotique-papaye-avocat-panache.png"),
    },
    BundledProductImage {
        product_id: 52,
        product_name: "Cocktail Sweet dream",
        file_name: "bimik-bundled-052_cocktail-sweet-dream.png",
        image_url: "/uploads/products/bimik-bundled-052_cocktail-sweet-dream.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-052_cocktail-sweet-dream.png"),
    },
    BundledProductImage {
        product_id: 53,
        product_name: "Cocktail Paradise",
        file_name: "bimik-bundled-053_cocktail-paradise.png",
        image_url: "/uploads/products/bimik-bundled-053_cocktail-paradise.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-053_cocktail-paradise.png"),
    },
    BundledProductImage {
        product_id: 54,
        product_name: "Expresse",
        file_name: "bimik-bundled-054_expresse.png",
        image_url: "/uploads/products/bimik-bundled-054_expresse.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-054_expresse.png"),
    },
    BundledProductImage {
        product_id: 55,
        product_name: "Soussi",
        file_name: "bimik-bundled-055_soussi.png",
        image_url: "/uploads/products/bimik-bundled-055_soussi.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-055_soussi.png"),
    },
    BundledProductImage {
        product_id: 56,
        product_name: "Fassi",
        file_name: "bimik-bundled-056_fassi.png",
        image_url: "/uploads/products/bimik-bundled-056_fassi.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-056_fassi.png"),
    },
    BundledProductImage {
        product_id: 57,
        product_name: "Special BIMIK",
        file_name: "bimik-bundled-057_special-bimik.png",
        image_url: "/uploads/products/bimik-bundled-057_special-bimik.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-057_special-bimik.png"),
    },
    BundledProductImage {
        product_id: 58,
        product_name: "Betbouta madhouna et Thé",
        file_name: "bimik-bundled-058_betbouta-madhouna-et-the.png",
        image_url: "/uploads/products/bimik-bundled-058_betbouta-madhouna-et-the.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-058_betbouta-madhouna-et-the.png"),
    },
    BundledProductImage {
        product_id: 59,
        product_name: "Amlou d’Amande",
        file_name: "bimik-bundled-059_amlou-d-amande.png",
        image_url: "/uploads/products/bimik-bundled-059_amlou-d-amande.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-059_amlou-d-amande.png"),
    },
    BundledProductImage {
        product_id: 60,
        product_name: "Miel",
        file_name: "bimik-bundled-060_miel.png",
        image_url: "/uploads/products/bimik-bundled-060_miel.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-060_miel.png"),
    },
    BundledProductImage {
        product_id: 61,
        product_name: "Beurre beldia",
        file_name: "bimik-bundled-061_beurre-beldia.png",
        image_url: "/uploads/products/bimik-bundled-061_beurre-beldia.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-061_beurre-beldia.png"),
    },
    BundledProductImage {
        product_id: 62,
        product_name: "Huile d’Olive",
        file_name: "bimik-bundled-062_huile-d-olive.png",
        image_url: "/uploads/products/bimik-bundled-062_huile-d-olive.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-062_huile-d-olive.png"),
    },
    BundledProductImage {
        product_id: 63,
        product_name: "Olives",
        file_name: "bimik-bundled-063_olives.png",
        image_url: "/uploads/products/bimik-bundled-063_olives.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-063_olives.png"),
    },
    BundledProductImage {
        product_id: 64,
        product_name: "Jben",
        file_name: "bimik-bundled-064_jben.png",
        image_url: "/uploads/products/bimik-bundled-064_jben.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-064_jben.png"),
    },
    BundledProductImage {
        product_id: 65,
        product_name: "Betboute",
        file_name: "bimik-bundled-065_betboute.png",
        image_url: "/uploads/products/bimik-bundled-065_betboute.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-065_betboute.png"),
    },
    BundledProductImage {
        product_id: 66,
        product_name: "Fromage",
        file_name: "bimik-bundled-066_fromage.png",
        image_url: "/uploads/products/bimik-bundled-066_fromage.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-066_fromage.png"),
    },
    BundledProductImage {
        product_id: 67,
        product_name: "kasher",
        file_name: "bimik-bundled-067_kasher.png",
        image_url: "/uploads/products/bimik-bundled-067_kasher.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-067_kasher.png"),
    },
    BundledProductImage {
        product_id: 68,
        product_name: "Lanchon",
        file_name: "bimik-bundled-068_lanchon.png",
        image_url: "/uploads/products/bimik-bundled-068_lanchon.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-068_lanchon.png"),
    },
    BundledProductImage {
        product_id: 69,
        product_name: "Omelette nature",
        file_name: "bimik-bundled-069_omelette-nature.png",
        image_url: "/uploads/products/bimik-bundled-069_omelette-nature.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-069_omelette-nature.png"),
    },
    BundledProductImage {
        product_id: 70,
        product_name: "Omelette au Fromage",
        file_name: "bimik-bundled-070_omelette-au-fromage.png",
        image_url: "/uploads/products/bimik-bundled-070_omelette-au-fromage.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-070_omelette-au-fromage.png"),
    },
    BundledProductImage {
        product_id: 71,
        product_name: "Omelette à la Tomate",
        file_name: "bimik-bundled-071_omelette-a-la-tomate.png",
        image_url: "/uploads/products/bimik-bundled-071_omelette-a-la-tomate.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-071_omelette-a-la-tomate.png"),
    },
    BundledProductImage {
        product_id: 72,
        product_name: "Omelette au khliâa",
        file_name: "bimik-bundled-072_omelette-au-khliaa.png",
        image_url: "/uploads/products/bimik-bundled-072_omelette-au-khliaa.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-072_omelette-au-khliaa.png"),
    },
    BundledProductImage {
        product_id: 73,
        product_name: "Omelette Crevettes 60g",
        file_name: "bimik-bundled-073_omelette-crevettes-60g.png",
        image_url: "/uploads/products/bimik-bundled-073_omelette-crevettes-60g.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-073_omelette-crevettes-60g.png"),
    },
    BundledProductImage {
        product_id: 74,
        product_name: "Maqula BIMIK",
        file_name: "bimik-bundled-074_maqula-bimik.png",
        image_url: "/uploads/products/bimik-bundled-074_maqula-bimik.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-074_maqula-bimik.png"),
    },
    BundledProductImage {
        product_id: 75,
        product_name: "Harira marocaine + Oeuf + Datte + Chabakia",
        file_name: "bimik-bundled-075_harira-marocaine-oeuf-datte-chabakia.png",
        image_url: "/uploads/products/bimik-bundled-075_harira-marocaine-oeuf-datte-chabakia.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-075_harira-marocaine-oeuf-datte-chabakia.png"),
    },
    BundledProductImage {
        product_id: 76,
        product_name: "l'eau 33 CL",
        file_name: "bimik-bundled-076_l-eau-33-cl.png",
        image_url: "/uploads/products/bimik-bundled-076_l-eau-33-cl.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-076_l-eau-33-cl.png"),
    },
    BundledProductImage {
        product_id: 77,
        product_name: "Coca cola",
        file_name: "bimik-bundled-077_coca-cola.png",
        image_url: "/uploads/products/bimik-bundled-077_coca-cola.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-077_coca-cola.png"),
    },
    BundledProductImage {
        product_id: 78,
        product_name: "Poms",
        file_name: "bimik-bundled-078_poms.png",
        image_url: "/uploads/products/bimik-bundled-078_poms.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-078_poms.png"),
    },
    BundledProductImage {
        product_id: 79,
        product_name: "Hawai",
        file_name: "bimik-bundled-079_hawai.png",
        image_url: "/uploads/products/bimik-bundled-079_hawai.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-079_hawai.png"),
    },
    BundledProductImage {
        product_id: 80,
        product_name: "Schwips Citron",
        file_name: "bimik-bundled-080_schwips-citron.png",
        image_url: "/uploads/products/bimik-bundled-080_schwips-citron.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-080_schwips-citron.png"),
    },
    BundledProductImage {
        product_id: 81,
        product_name: "Schwips Tonic",
        file_name: "bimik-bundled-081_schwips-tonic.png",
        image_url: "/uploads/products/bimik-bundled-081_schwips-tonic.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-081_schwips-tonic.png"),
    },
    BundledProductImage {
        product_id: 82,
        product_name: "Oulmès",
        file_name: "bimik-bundled-082_oulmes.png",
        image_url: "/uploads/products/bimik-bundled-082_oulmes.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-082_oulmes.png"),
    },
    BundledProductImage {
        product_id: 83,
        product_name: "Oulmès Bulles Fruitées Tropical",
        file_name: "bimik-bundled-083_oulmes-bulles-fruitees-tropical.png",
        image_url: "/uploads/products/bimik-bundled-083_oulmes-bulles-fruitees-tropical.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-083_oulmes-bulles-fruitees-tropical.png"),
    },
    BundledProductImage {
        product_id: 84,
        product_name: "Oulmès Bulles Fruitées Orange",
        file_name: "bimik-bundled-084_oulmes-bulles-fruitees-orange.png",
        image_url: "/uploads/products/bimik-bundled-084_oulmes-bulles-fruitees-orange.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-084_oulmes-bulles-fruitees-orange.png"),
    },
    BundledProductImage {
        product_id: 85,
        product_name: "Oulmès Bulles Fruitées Ananas",
        file_name: "bimik-bundled-085_oulmes-bulles-fruitees-ananas.png",
        image_url: "/uploads/products/bimik-bundled-085_oulmes-bulles-fruitees-ananas.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-085_oulmes-bulles-fruitees-ananas.png"),
    },
    BundledProductImage {
        product_id: 86,
        product_name: "Oulmès Bulles Fruitées Fraise",
        file_name: "bimik-bundled-086_oulmes-bulles-fruitees-fraise.png",
        image_url: "/uploads/products/bimik-bundled-086_oulmes-bulles-fruitees-fraise.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-086_oulmes-bulles-fruitees-fraise.png"),
    },
    BundledProductImage {
        product_id: 87,
        product_name: "petit pain",
        file_name: "bimik-bundled-087_petit-pain.png",
        image_url: "/uploads/products/bimik-bundled-087_petit-pain.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-087_petit-pain.png"),
    },
    BundledProductImage {
        product_id: 88,
        product_name: "Petit Pain madhouna",
        file_name: "bimik-bundled-088_petit-pain-madhouna.png",
        image_url: "/uploads/products/bimik-bundled-088_petit-pain-madhouna.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-088_petit-pain-madhouna.png"),
    },
    BundledProductImage {
        product_id: 89,
        product_name: "Khebza Meadhouna",
        file_name: "bimik-bundled-089_khebza-meadhouna.png",
        image_url: "/uploads/products/bimik-bundled-089_khebza-meadhouna.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-089_khebza-meadhouna.png"),
    },
    BundledProductImage {
        product_id: 90,
        product_name: "Coca Zero",
        file_name: "bimik-bundled-090_coca-zero.png",
        image_url: "/uploads/products/bimik-bundled-090_coca-zero.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-090_coca-zero.png"),
    },
    BundledProductImage {
        product_id: 91,
        product_name: "Sprite",
        file_name: "bimik-bundled-091_sprite.png",
        image_url: "/uploads/products/bimik-bundled-091_sprite.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-091_sprite.png"),
    },
    BundledProductImage {
        product_id: 92,
        product_name: "Garnier",
        file_name: "bimik-bundled-092_garnier.png",
        image_url: "/uploads/products/bimik-bundled-092_garnier.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-092_garnier.png"),
    },
    BundledProductImage {
        product_id: 93,
        product_name: "Msemna",
        file_name: "bimik-bundled-093_msemna.png",
        image_url: "/uploads/products/bimik-bundled-093_msemna.png",
        bytes: include_bytes!("../resources/product-images/bimik-bundled-093_msemna.png"),
    },
];
