CREATE TABLE businesses (id serial PRIMARY KEY,name varchar(255) NOT NULL,slug varchar(255) NOT NULL UNIQUE,business_type varchar(40) NOT NULL DEFAULT 'custom',logo text,currency varchar(3) NOT NULL DEFAULT 'MAD',locale varchar(20) NOT NULL DEFAULT 'fr-MA',timezone varchar(100) NOT NULL DEFAULT 'Africa/Casablanca',tax_settings jsonb NOT NULL DEFAULT '{}',receipt_settings jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
INSERT INTO businesses(id,name,slug,business_type) SELECT 1,'Bimik Cafe','bimik-cafe','cafe' WHERE EXISTS(SELECT 1 FROM users UNION ALL SELECT 1 FROM products UNION ALL SELECT 1 FROM sales LIMIT 1);
SELECT setval(pg_get_serial_sequence('businesses','id'),coalesce((SELECT max(id) FROM businesses),1),EXISTS(SELECT 1 FROM businesses));
CREATE TABLE branches(id serial PRIMARY KEY,business_id integer NOT NULL REFERENCES businesses(id),name varchar(255) NOT NULL,code varchar(40) NOT NULL,address text,phone varchar(50),active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(business_id,code));
INSERT INTO branches(id,business_id,name,code) SELECT 1,1,'Principal','MAIN' WHERE EXISTS(SELECT 1 FROM businesses WHERE id=1); SELECT setval(pg_get_serial_sequence('branches','id'),coalesce((SELECT max(id) FROM branches),1),EXISTS(SELECT 1 FROM branches));
CREATE TABLE business_features(business_id integer NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,feature varchar(50) NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(business_id,feature));
INSERT INTO business_features SELECT 1,feature,now() FROM (VALUES ('pos'),('inventory'),('tables'),('kitchen'),('qr_menu'),('takeaway')) defaults(feature) WHERE EXISTS(SELECT 1 FROM businesses WHERE id=1);

ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE users ADD COLUMN business_id integer REFERENCES businesses(id),ADD COLUMN branch_id integer REFERENCES branches(id);
UPDATE users SET business_id=1,branch_id=1; ALTER TABLE users ALTER COLUMN business_id SET NOT NULL; ALTER TABLE users ALTER COLUMN business_id SET DEFAULT 1; ALTER TABLE users ALTER COLUMN branch_id SET DEFAULT 1; CREATE INDEX users_business_idx ON users(business_id);
ALTER TABLE users ADD CONSTRAINT users_role_check CHECK(role IN ('patron','worker','owner','admin','manager','cashier','waiter','kitchen','stock_manager'));
ALTER TABLE categories ADD COLUMN business_id integer REFERENCES businesses(id),ADD COLUMN is_public boolean NOT NULL DEFAULT true; UPDATE categories SET business_id=1; ALTER TABLE categories ALTER COLUMN business_id SET NOT NULL; ALTER TABLE categories ALTER COLUMN business_id SET DEFAULT 1; CREATE INDEX categories_business_idx ON categories(business_id);
ALTER TABLE products ADD COLUMN business_id integer REFERENCES businesses(id),ADD COLUMN sku varchar(100),ADD COLUMN barcode varchar(100),ADD COLUMN unit varchar(30) NOT NULL DEFAULT 'piece',ADD COLUMN tax_rate numeric(6,3) NOT NULL DEFAULT 0,ADD COLUMN is_public boolean NOT NULL DEFAULT true,ADD COLUMN available boolean NOT NULL DEFAULT true; UPDATE products SET business_id=1; ALTER TABLE products ALTER COLUMN business_id SET NOT NULL; ALTER TABLE products ALTER COLUMN business_id SET DEFAULT 1; CREATE INDEX products_business_idx ON products(business_id); CREATE UNIQUE INDEX products_business_sku_unique ON products(business_id,sku) WHERE sku IS NOT NULL; CREATE UNIQUE INDEX products_business_barcode_unique ON products(business_id,barcode) WHERE barcode IS NOT NULL;
DROP INDEX IF EXISTS cash_register_sessions_one_open_idx; ALTER TABLE cash_register_sessions ADD COLUMN business_id integer REFERENCES businesses(id),ADD COLUMN branch_id integer REFERENCES branches(id); UPDATE cash_register_sessions SET business_id=1,branch_id=1; ALTER TABLE cash_register_sessions ALTER COLUMN business_id SET NOT NULL; ALTER TABLE cash_register_sessions ALTER COLUMN business_id SET DEFAULT 1; ALTER TABLE cash_register_sessions ALTER COLUMN branch_id SET DEFAULT 1; CREATE UNIQUE INDEX cash_register_one_open_business_branch_idx ON cash_register_sessions(business_id,branch_id) WHERE status='open';
ALTER TABLE sales ADD COLUMN business_id integer REFERENCES businesses(id),ADD COLUMN branch_id integer REFERENCES branches(id),ADD COLUMN client_id uuid,ADD COLUMN order_id integer; UPDATE sales SET business_id=1,branch_id=1; ALTER TABLE sales ALTER COLUMN business_id SET NOT NULL; ALTER TABLE sales ALTER COLUMN business_id SET DEFAULT 1; ALTER TABLE sales ALTER COLUMN branch_id SET DEFAULT 1; CREATE UNIQUE INDEX sales_business_client_unique ON sales(business_id,client_id) WHERE client_id IS NOT NULL; CREATE INDEX sales_business_created_idx ON sales(business_id,created_at);
ALTER TABLE stock_movements ADD COLUMN business_id integer REFERENCES businesses(id),ADD COLUMN branch_id integer REFERENCES branches(id),ADD COLUMN client_id uuid; UPDATE stock_movements SET business_id=1,branch_id=1; ALTER TABLE stock_movements ALTER COLUMN business_id SET NOT NULL; ALTER TABLE stock_movements ALTER COLUMN business_id SET DEFAULT 1; ALTER TABLE stock_movements ALTER COLUMN branch_id SET DEFAULT 1; CREATE UNIQUE INDEX stock_business_client_unique ON stock_movements(business_id,client_id) WHERE client_id IS NOT NULL;
ALTER TABLE settings DROP CONSTRAINT IF EXISTS settings_key_unique; DROP INDEX IF EXISTS settings_key_unique; ALTER TABLE settings ADD COLUMN business_id integer REFERENCES businesses(id); UPDATE settings SET business_id=1; ALTER TABLE settings ALTER COLUMN business_id SET NOT NULL; ALTER TABLE settings ALTER COLUMN business_id SET DEFAULT 1; CREATE UNIQUE INDEX settings_business_key_unique ON settings(business_id,key);

CREATE TABLE units(id serial PRIMARY KEY,business_id integer REFERENCES businesses(id),code varchar(30) NOT NULL,name varchar(80) NOT NULL,precision integer NOT NULL DEFAULT 0,active boolean NOT NULL DEFAULT true,UNIQUE(business_id,code));
INSERT INTO units(business_id,code,name,precision) VALUES (NULL,'piece','Piece',0),(NULL,'kg','Kilogram',3),(NULL,'gram','Gram',0),(NULL,'liter','Liter',3),(NULL,'ml','Milliliter',0),(NULL,'pack','Pack',0),(NULL,'box','Box',0);
CREATE TABLE customers(id serial PRIMARY KEY,business_id integer NOT NULL REFERENCES businesses(id),name varchar(255) NOT NULL,phone varchar(50),email varchar(255),address text,notes text,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now()); CREATE INDEX customers_business_idx ON customers(business_id);
CREATE TABLE suppliers(id serial PRIMARY KEY,business_id integer NOT NULL REFERENCES businesses(id),name varchar(255) NOT NULL,contact varchar(255),phone varchar(50),email varchar(255),address text,notes text,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now()); CREATE INDEX suppliers_business_idx ON suppliers(business_id);
CREATE TABLE rooms(id serial PRIMARY KEY,business_id integer NOT NULL REFERENCES businesses(id),branch_id integer NOT NULL REFERENCES branches(id),name varchar(120) NOT NULL,sort_order integer NOT NULL DEFAULT 0,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE restaurant_tables(id serial PRIMARY KEY,business_id integer NOT NULL REFERENCES businesses(id),branch_id integer NOT NULL REFERENCES branches(id),room_id integer NOT NULL REFERENCES rooms(id),table_number varchar(30) NOT NULL,name varchar(120) NOT NULL,capacity integer NOT NULL,status varchar(30) NOT NULL DEFAULT 'available',qr_token_hash varchar(64) NOT NULL,qr_token_hint varchar(12) NOT NULL,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(business_id,branch_id,table_number),UNIQUE(qr_token_hash));
CREATE TABLE product_variants(id serial PRIMARY KEY,business_id integer NOT NULL REFERENCES businesses(id),product_id integer NOT NULL REFERENCES products(id) ON DELETE CASCADE,name varchar(120) NOT NULL,sku varchar(100),barcode varchar(100),price_delta numeric(12,2) NOT NULL DEFAULT 0,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE product_modifiers(id serial PRIMARY KEY,business_id integer NOT NULL REFERENCES businesses(id),product_id integer NOT NULL REFERENCES products(id) ON DELETE CASCADE,name varchar(120) NOT NULL,price numeric(12,2) NOT NULL DEFAULT 0,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE orders(id serial PRIMARY KEY,business_id integer NOT NULL REFERENCES businesses(id),branch_id integer REFERENCES branches(id),client_id uuid NOT NULL,order_number varchar(50) NOT NULL,source varchar(30) NOT NULL,type varchar(30) NOT NULL,table_id integer REFERENCES restaurant_tables(id),customer_id integer REFERENCES customers(id),user_id integer REFERENCES users(id),status varchar(30) NOT NULL DEFAULT 'pending',subtotal numeric(12,2) NOT NULL DEFAULT 0,discount numeric(12,2) NOT NULL DEFAULT 0,tax numeric(12,2) NOT NULL DEFAULT 0,total numeric(12,2) NOT NULL DEFAULT 0,payment_status varchar(20) NOT NULL DEFAULT 'unpaid',sync_status varchar(20) NOT NULL DEFAULT 'synced',notes text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(business_id,client_id),UNIQUE(business_id,order_number)); CREATE INDEX orders_business_status_idx ON orders(business_id,status,created_at);
CREATE TABLE order_items(id serial PRIMARY KEY,order_id integer NOT NULL REFERENCES orders(id) ON DELETE CASCADE,product_id integer NOT NULL REFERENCES products(id),variant_id integer REFERENCES product_variants(id),quantity numeric(12,3) NOT NULL,unit_price numeric(12,2) NOT NULL,discount numeric(12,2) NOT NULL DEFAULT 0,tax numeric(12,2) NOT NULL DEFAULT 0,total numeric(12,2) NOT NULL,notes text,preparation_status varchar(20),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE order_item_modifiers(order_item_id integer NOT NULL REFERENCES order_items(id) ON DELETE CASCADE,modifier_id integer NOT NULL REFERENCES product_modifiers(id),name varchar(120) NOT NULL,price numeric(12,2) NOT NULL,PRIMARY KEY(order_item_id,modifier_id));
ALTER TABLE sales ADD CONSTRAINT sales_order_id_fk FOREIGN KEY(order_id) REFERENCES orders(id); CREATE UNIQUE INDEX sales_order_unique ON sales(order_id) WHERE order_id IS NOT NULL;
CREATE TABLE purchases(id serial PRIMARY KEY,business_id integer NOT NULL REFERENCES businesses(id),branch_id integer REFERENCES branches(id),supplier_id integer NOT NULL REFERENCES suppliers(id),reference varchar(100) NOT NULL,status varchar(30) NOT NULL DEFAULT 'draft',subtotal numeric(12,2) NOT NULL DEFAULT 0,tax numeric(12,2) NOT NULL DEFAULT 0,total numeric(12,2) NOT NULL DEFAULT 0,payment_status varchar(20) NOT NULL DEFAULT 'unpaid',received_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(business_id,reference));
CREATE TABLE purchase_items(id serial PRIMARY KEY,purchase_id integer NOT NULL REFERENCES purchases(id) ON DELETE CASCADE,product_id integer NOT NULL REFERENCES products(id),quantity numeric(12,3) NOT NULL,received_quantity numeric(12,3) NOT NULL DEFAULT 0,purchase_price numeric(12,2) NOT NULL,tax numeric(12,2) NOT NULL DEFAULT 0,total numeric(12,2) NOT NULL);
CREATE TABLE table_events(id bigserial PRIMARY KEY,business_id integer NOT NULL REFERENCES businesses(id),table_id integer NOT NULL REFERENCES restaurant_tables(id),type varchar(30) NOT NULL,status varchar(20) NOT NULL DEFAULT 'pending',created_at timestamptz NOT NULL DEFAULT now(),resolved_at timestamptz,resolved_by_user_id integer REFERENCES users(id));
CREATE TABLE sync_mutations(id bigserial PRIMARY KEY,business_id integer NOT NULL REFERENCES businesses(id),client_id uuid NOT NULL,entity_type varchar(40) NOT NULL,entity_id varchar(100),operation varchar(20) NOT NULL,payload jsonb NOT NULL,sync_status varchar(20) NOT NULL DEFAULT 'synced',error text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(business_id,client_id));

INSERT INTO orders(business_id,branch_id,client_id,order_number,source,type,user_id,status,subtotal,total,payment_status,created_at,updated_at)
SELECT 1,1,gen_random_uuid(),'LEGACY-'||s.id,'pos','retail',s.user_id,'completed',s.total,s.total,'paid',s.created_at,s.updated_at FROM sales s;
UPDATE sales s SET order_id=o.id FROM orders o WHERE o.order_number='LEGACY-'||s.id;
INSERT INTO order_items(order_id,product_id,quantity,unit_price,total,created_at,updated_at)
SELECT s.order_id,si.product_id,si.quantity,si.unit_price,si.total,si.created_at,si.updated_at FROM sale_items si JOIN sales s ON s.id=si.sale_id;
