import assert from 'node:assert/strict'
import test from 'node:test'
import { File } from 'node:buffer'
import fs from 'node:fs'
import path from 'node:path'
import { createMenuPdfFormData, selectMenuPdf, tryBeginUpload } from './menu-upload.ts'
import { publicMenuUrl } from './public-menu-url.ts'
import { formatActivationCodeWhileTyping, normalizeActivationCodeInput } from './utils/activationCode.ts'
import { CorePosPrintError, getPrinterErrorCode, isPrinterConfigurationError } from './utils/printerErrors.ts'
test('real File uses canonical pdf field and original name',()=>{const file=new File([Buffer.from('%PDF-1.7')],'menu-test.pdf',{type:'application/pdf'});const data=createMenuPdfFormData(file as unknown as globalThis.File);assert.equal(data.get('pdf') instanceof Blob,true);assert.equal((data.get('pdf') as File).name,'menu-test.pdf');assert.deepEqual([...data.keys()],['pdf'])})
test('FormData is binary and defines no manual Content-Type header',()=>{const file=new File(['pdf'],'fixture.pdf',{type:'application/pdf'});const data=createMenuPdfFormData(file as unknown as globalThis.File);assert.equal(data instanceof FormData,true);assert.equal('headers' in data,false);assert.notEqual(data.get('pdf'),JSON.stringify(file))})
test('selecting or removing a file clears stale errors',()=>{const valid=new File(['pdf'],'fixture.pdf',{type:'application/pdf'});assert.deepEqual(selectMenuPdf(valid as unknown as globalThis.File),{file:valid,error:null});assert.deepEqual(selectMenuPdf(null),{file:null,error:null})})
test('invalid files are rejected and lock prevents double submission',()=>{const invalid=new File(['x'],'fixture.txt',{type:'text/plain'});assert.match(selectMenuPdf(invalid as unknown as globalThis.File).error??'',/PDF valide/);const lock={current:false};assert.equal(tryBeginUpload(lock),true);assert.equal(tryBeginUpload(lock),false)})
test('QR URL uses the public origin and only the opaque table token',()=>{const token='A'.repeat(43),url=publicMenuUrl(token,'https://pos.example.test/','https://tauri.localhost');assert.equal(url,`https://pos.example.test/m/${token}`);assert.equal(url.includes('workspace'),false);assert.equal(url.includes('tenant'),false)})
test('QR URL never falls back to localhost or the Tauri origin',()=>{const token='A'.repeat(43);assert.throws(()=>publicMenuUrl(token,undefined,'http://127.0.0.1:5173'));assert.throws(()=>publicMenuUrl(token,undefined,'https://tauri.localhost'))})
test('normal login source has no workspace selector or tenant input',()=>{const source=fs.readFileSync(path.join(import.meta.dirname,'pages','LoginPage.tsx'),'utf8');assert.doesNotMatch(source,/workspaceInput|chooseWorkspace|setWorkspaceSlug|getWorkspaceSlug/);assert.doesNotMatch(source,/login\.workspace(?:['"]|Continue|Placeholder|Checking|Invalid|NotFound)/)})
test('activation input formats the CP code without touching legacy credentials',()=>{assert.equal(formatActivationCodeWhileTyping('cpabcdEFGHjkmnpqrs'),'CP-ABCD-EFGH-JKMN-PQRS');assert.equal(formatActivationCodeWhileTyping('act_legacy-value'),'act_legacy-value');assert.equal(normalizeActivationCodeInput(' cp-abcd efgh-jkmn-pqrs '),'CP-ABCD-EFGH-JKMN-PQRS');assert.equal(normalizeActivationCodeInput('CP-ABCD-EFGH-JKMN-PQRI'),'CP-ABCD-EFGH-JKMN-PQRI')})
for(const code of ['PRINTER_NOT_CONFIGURED','PRINTER_NOT_FOUND','PRINTER_OFFLINE','PRINT_BRIDGE_UNAVAILABLE','PRINT_PERMISSION_DENIED','PRINT_FAILED'] as const)test(`maps ${code} from structured print errors`,()=>assert.equal(getPrinterErrorCode(new CorePosPrintError(code)),code))
test('maps legacy Tauri payloads and keeps unexpected failures distinguishable',()=>{assert.equal(getPrinterErrorCode('{"code":"PRINTER_NOT_FOUND","message":"hidden"}'),'PRINTER_NOT_FOUND');assert.equal(getPrinterErrorCode(new Error('unexpected spooler state')),'PRINT_FAILED');assert.equal(isPrinterConfigurationError(new CorePosPrintError('PRINTER_NOT_CONFIGURED')),true);assert.equal(isPrinterConfigurationError(new CorePosPrintError('PRINTER_OFFLINE')),false)})
