import type {DatabaseSync} from 'node:sqlite';
import type {FastifyInstance,FastifyReply,FastifyRequest} from 'fastify';
import {z} from 'zod';
const now=()=>new Date().toISOString();
const one=(db:DatabaseSync,sql:string,...args:any[])=>db.prepare(sql).get(...args) as any;
const all=(db:DatabaseSync,sql:string,...args:any[])=>db.prepare(sql).all(...args) as any[];
const incoming=z.object({client_id:z.string().uuid(),product_sync_id:z.string().uuid(),type:z.enum(['in','out','correction','purchase']),delta:z.number().int().refine(x=>x!==0),note:z.string().nullable(),user_email:z.string().email(),branch_code:z.string().max(40).nullable(),created_at:z.string().datetime()}).strict();
const compare=(a:string,b:string)=>{const pos=(v:string)=>{const i=v.lastIndexOf('|'),stamp=i<0?v:v.slice(0,i),id=i<0?0:Number(v.slice(i+1));return {stamp:Date.parse(stamp),id:Number.isInteger(id)?id:0}};const x=pos(a),y=pos(b);return x.stamp-y.stamp||x.id-y.id};

export function registerLocalStockMovementSync(app:FastifyInstance,db:DatabaseSync,guard:(r:FastifyRequest,p:FastifyReply)=>Promise<unknown>,user:(r:FastifyRequest)=>any,tx:<T>(fn:()=>T)=>T){
 app.get('/api/sync/stock-movements/state',{preHandler:guard},async()=>({data:{cursor:one(db,"select value from sync_state where key='stock_movement_cursor'")?.value??null}}));
 app.get('/api/sync/stock-movements/outbox',{preHandler:guard},async r=>{const businessId=user(r).business_id;return{data:all(db,"select m.client_id,m.product_id,m.type,m.before_stock,m.after_stock,m.note,m.created_at,p.sync_id product_sync_id,u.email user_email,b.code branch_code from stock_movements m join master_sync_entities p on p.entity_type='products' and p.local_id=m.product_id join users u on u.id=m.user_id left join branches b on b.id=m.branch_id where m.business_id=? and m.client_id is not null and m.type in('increase','decrease','correction','purchase','sale','order_cancel','purchase_return','sale_return','adjustment_in','adjustment_out') and exists(select 1 from sync_mutations s where s.business_id=m.business_id and s.client_id=m.client_id and s.sync_status in('pending','failed')) order by m.id limit 100",businessId).map(m=>({client_id:m.client_id,product_sync_id:m.product_sync_id,type:['increase','purchase','order_cancel','sale_return','adjustment_in'].includes(m.type)?'in':['decrease','sale','purchase_return','adjustment_out'].includes(m.type)?'out':'correction',delta:Number(m.after_stock)-Number(m.before_stock),note:m.note,user_email:m.user_email,branch_code:m.branch_code,created_at:new Date(m.created_at).toISOString()}))}});
 app.post('/api/sync/stock-movements/apply',{preHandler:guard},async r=>{const u=user(r),input=z.object({cursor:z.string().nullable().optional(),movements:z.array(incoming).max(500)}).parse(r.body),old=one(db,"select value from sync_state where key='stock_movement_cursor'")?.value as string|undefined;if(input.cursor&&old&&compare(input.cursor,old)<=0)return{message:'Already reconciled.'};tx(()=>{db.prepare("update master_sync_runtime set value='1' where key='remote_apply'").run();try{for(const m of input.movements){const seen=one(db,'select id from stock_movements where business_id=? and client_id=?',u.business_id,m.client_id);if(seen){db.prepare("update sync_mutations set sync_status='synced',last_error=null,updated_at=? where business_id=? and client_id=?").run(now(),u.business_id,m.client_id);continue}const product=one(db,"select p.id,p.stock from products p join master_sync_entities s on s.entity_type='products' and s.local_id=p.id where p.business_id=? and s.sync_id=?",u.business_id,m.product_sync_id);const operator=one(db,'select id from users where business_id=? and lower(email)=lower(?)',u.business_id,m.user_email);const branch=m.branch_code?one(db,'select id from branches where business_id=? and code=?',u.business_id,m.branch_code):null;if(!product||!operator||(m.branch_code&&!branch))throw Object.assign(new Error('Stock movement dependency is unavailable locally.'),{statusCode:409,code:'SYNC_DEPENDENCY_MISSING'});const before=Number(product.stock),after=before+m.delta;if(after<0)throw Object.assign(new Error('Remote stock movement would make inventory negative.'),{statusCode:409,code:'STOCK_MOVEMENT_CONFLICT'});const kind=m.type==='in'?'increase':m.type==='out'?'decrease':m.type==='purchase'?'purchase':'correction';db.prepare('update products set stock=?,updated_at=? where id=? and business_id=?').run(after,m.created_at,product.id,u.business_id);db.prepare('insert into stock_movements(business_id,branch_id,product_id,user_id,type,quantity,before_stock,after_stock,note,created_at,updated_at,client_id) values(?,?,?,?,?,?,?,?,?,?,?,?)').run(u.business_id,branch?.id??null,product.id,operator.id,kind,Math.abs(m.delta),before,after,m.note,m.created_at,m.created_at,m.client_id);db.prepare("insert into sync_mutations(business_id,client_id,entity_type,entity_id,operation,payload_json,sync_status,created_at,updated_at) values(?,?,'stock_movement',?,'apply','{}','synced',?,?) on conflict(business_id,client_id) do update set sync_status='synced',last_error=null,updated_at=excluded.updated_at").run(u.business_id,m.client_id,String(product.id),now(),now())}if(input.cursor)db.prepare("insert into sync_state(key,value,updated_at) values('stock_movement_cursor',?,?) on conflict(key) do update set value=excluded.value,updated_at=excluded.updated_at").run(input.cursor,now())}finally{db.prepare("update master_sync_runtime set value='0' where key='remote_apply'").run()}});return{message:'Applied.'}});
}
