import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import bcrypt from 'bcryptjs';
import {openLocalDatabase} from './database.js';
import {ensureLocalPaths,resolveLocalPaths} from './paths.js';
import {buildLocalApp} from './server.js';

process.env.LICENSE_MODE='development';

test('stock event stays in SQLite across restart and remote apply is idempotent without outbox feedback',{concurrency:false},async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'corepos-stock-local-')),paths=ensureLocalPaths(resolveLocalPaths({BIMIK_DATA_DIR:root})),stamp=new Date().toISOString();let db:any,app:any;try{
  db=openLocalDatabase(paths);db.prepare("insert into businesses(id,name,slug,business_type,currency,locale,timezone,tax_settings_json,receipt_settings_json,created_at,updated_at) values(1,'Local','local','cafe','MAD','fr-MA','Africa/Casablanca','{}','{}',?,?)").run(stamp,stamp);db.prepare("insert into branches(id,business_id,name,code,active,created_at,updated_at) values(1,1,'Main','MAIN',1,?,?)").run(stamp,stamp);const hash=await bcrypt.hash('secret',4);db.prepare("insert into users(id,name,email,password,role,is_active,business_id,branch_id,created_at,updated_at) values(1,'Patron','local@test.invalid',?,'owner',1,1,1,?,?)").run(hash,stamp,stamp);const product=Number(db.prepare("insert into products(business_id,name,purchase_price_cents,sale_price_cents,stock,min_stock,track_stock,is_active,is_public,available,created_at,updated_at) values(1,'Local stock',100,200,4,0,1,1,1,1,?,?)").run(stamp,stamp).lastInsertRowid),productSync='85000000-0000-4000-8000-000000000001';db.prepare("insert into master_sync_entities(entity_type,local_id,sync_id,sync_status) values('products',?,?,'synced')").run(product,productSync);app=await buildLocalApp({paths,database:db});let login=await app.inject({method:'POST',url:'/api/login',payload:{email:'local@test.invalid',password:'secret'}}),auth={authorization:`Bearer ${login.json().data.access_token}`};const localChange=await app.inject({method:'POST',url:`/api/products/${product}/stock/increase`,headers:auth,payload:{quantity:10,note:'offline'}});assert.equal(localChange.statusCode,200,localChange.body);const queued=(await app.inject({method:'GET',url:'/api/sync/stock-movements/outbox',headers:auth})).json().data;assert.equal(queued.length,1);assert.equal(queued[0].delta,10);const id=queued[0].client_id;await app.close();app=null;db.close();db=null;db=openLocalDatabase(paths);app=await buildLocalApp({paths,database:db});login=await app.inject({method:'POST',url:'/api/login',payload:{email:'local@test.invalid',password:'secret'}});auth={authorization:`Bearer ${login.json().data.access_token}`};assert.equal((await app.inject({method:'GET',url:'/api/sync/stock-movements/outbox',headers:auth})).json().data[0].client_id,id);
  const remote={client_id:'85000000-0000-4000-8000-000000000002',product_sync_id:productSync,type:'in',delta:3,note:'remote',user_email:'local@test.invalid',branch_code:'MAIN',created_at:new Date().toISOString()},body={cursor:`${remote.created_at}|1`,movements:[remote]};assert.equal((await app.inject({method:'POST',url:'/api/sync/stock-movements/apply',headers:auth,payload:body})).statusCode,200);assert.equal(db.prepare('select stock from products where id=?').get(product).stock,17);assert.equal((await app.inject({method:'POST',url:'/api/sync/stock-movements/apply',headers:auth,payload:body})).statusCode,200);assert.equal(db.prepare('select stock from products where id=?').get(product).stock,17);assert.equal(db.prepare('select count(*) n from stock_movements where client_id=?').get(remote.client_id).n,1);assert.equal(db.prepare("select count(*) n from sync_mutations where entity_type='stock_movement' and sync_status in('pending','failed')").get().n,1);
 }finally{if(app)await app.close();if(db)db.close();fs.rmSync(root,{recursive:true,force:true});}
});
