import type {DatabaseSync} from 'node:sqlite';
import type {FastifyInstance,FastifyReply,FastifyRequest} from 'fastify';
import {z} from 'zod';

export const universalV1Entities=['categories','units','customers'] as const;
type Entity=typeof universalV1Entities[number];
const entitySchema=z.enum(universalV1Entities),now=()=>new Date().toISOString();
const one=(db:DatabaseSync,sql:string,...values:any[])=>db.prepare(sql).get(...values) as any;
const schemas:Record<Entity,z.ZodTypeAny>={
 categories:z.object({name:z.string().trim().min(1).max(255),image:z.string().nullable().optional(),is_public:z.boolean()}).strict(),
 units:z.object({code:z.string().trim().min(1).max(50),name:z.string().trim().min(1).max(255),precision:z.number().int().min(0).max(6),active:z.boolean()}).strict(),
 customers:z.object({name:z.string().trim().min(1).max(255),phone:z.string().nullable().optional(),email:z.string().email().nullable().optional(),address:z.string().nullable().optional(),notes:z.string().nullable().optional(),active:z.boolean()}).strict(),
};
const change=z.object({entity_type:entitySchema,sync_id:z.string().uuid(),server_id:z.number().int().positive(),deleted:z.boolean(),updated_at:z.string(),data:z.record(z.string(),z.unknown()).nullable()}).strict();
const compare=(a:string,b:string)=>{const parse=(v:string)=>{const i=v.lastIndexOf('|');return[Date.parse(i<0?v:v.slice(0,i)),Number(i<0?0:v.slice(i+1))]};const x=parse(a),y=parse(b);return x[0]-y[0]||x[1]-y[1]};
function row(db:DatabaseSync,entity:Entity,id:number,businessId:number){if(entity==='categories')return one(db,'select * from categories where id=? and business_id=?',id,businessId);if(entity==='units')return one(db,'select * from units where id=? and business_id=?',id,businessId);return one(db,'select * from customers where id=? and business_id=?',id,businessId)}
function remove(db:DatabaseSync,entity:Entity,id:number,businessId:number){if(entity==='categories')return db.prepare('delete from categories where id=? and business_id=?').run(id,businessId);if(entity==='units')return db.prepare('delete from units where id=? and business_id=?').run(id,businessId);return db.prepare('delete from customers where id=? and business_id=?').run(id,businessId)}
function write(db:DatabaseSync,entity:Entity,id:number|undefined,businessId:number,data:any,stamp:string){const d:any=schemas[entity].parse(data);if(entity==='categories'){if(id)db.prepare('update categories set name=?,image=?,is_public=?,updated_at=? where id=? and business_id=?').run(d.name,d.image??null,Number(d.is_public),stamp,id,businessId);else id=Number(db.prepare('insert into categories(business_id,name,image,is_public,created_at,updated_at) values(?,?,?,?,?,?)').run(businessId,d.name,d.image??null,Number(d.is_public),stamp,stamp).lastInsertRowid)}else if(entity==='units'){if(id)db.prepare('update units set code=?,name=?,precision=?,active=?,updated_at=? where id=? and business_id=?').run(d.code,d.name,d.precision,Number(d.active),stamp,id,businessId);else id=Number(db.prepare('insert into units(business_id,code,name,precision,active,created_at,updated_at) values(?,?,?,?,?,?,?)').run(businessId,d.code,d.name,d.precision,Number(d.active),stamp,stamp).lastInsertRowid)}else{if(id)db.prepare('update customers set name=?,phone=?,email=?,address=?,notes=?,active=?,updated_at=? where id=? and business_id=?').run(d.name,d.phone??null,d.email??null,d.address??null,d.notes??null,Number(d.active),stamp,id,businessId);else id=Number(db.prepare('insert into customers(business_id,name,phone,email,address,notes,active,created_at,updated_at) values(?,?,?,?,?,?,?,?,?)').run(businessId,d.name,d.phone??null,d.email??null,d.address??null,d.notes??null,Number(d.active),stamp,stamp).lastInsertRowid)}return id!}
export function registerLocalUniversalV1Sync(app:FastifyInstance,db:DatabaseSync,guard:(r:FastifyRequest,p:FastifyReply)=>Promise<unknown>,user:(r:FastifyRequest)=>any,tx:<T>(f:()=>T)=>T){
 app.get('/api/sync/v1/state',{preHandler:guard},async()=>({data:{cursor:one(db,"select value from sync_state where key='universal_v1_cursor'")?.value??null}}));
 app.get('/api/sync/v1/outbox',{preHandler:guard},async request=>{const businessId=user(request).business_id,mutations=db.prepare("select * from sync_mutations where business_id=? and entity_type in ('categories','units','customers') and sync_status in ('pending','failed') order by id limit 100").all(businessId) as any[];return{data:mutations.map(m=>{const kind=entitySchema.parse(m.entity_type),id=Number(m.entity_id),mapping=one(db,'select sync_id,server_updated_at from master_sync_entities where entity_type=? and local_id=?',kind,id);return{client_id:m.client_id,entity_type:kind,sync_id:mapping?.sync_id,operation:m.operation,base_updated_at:mapping?.server_updated_at??null,data:m.operation==='delete'?null:row(db,kind,id,businessId)}}).filter(m=>m.sync_id)}});
 app.post('/api/sync/v1/outbox/:clientId/retry',{preHandler:guard},async request=>{const businessId=user(request).business_id,input=z.object({error:z.string().min(1).max(255)}).parse(request.body);db.prepare("update sync_mutations set sync_status='failed',attempts=attempts+1,last_error=?,updated_at=? where business_id=? and client_id=? and entity_type in ('categories','units','customers') and sync_status in ('pending','failed')").run(input.error,now(),businessId,(request.params as any).clientId);return{message:'Retry recorded.'}});
 app.post('/api/sync/v1/outbox/:clientId/conflict',{preHandler:guard},async request=>{const businessId=user(request).business_id,clientId=z.string().uuid().parse((request.params as any).clientId);tx(()=>{const mutation=one(db,"select entity_type,entity_id from sync_mutations where business_id=? and client_id=? and entity_type in ('categories','units','customers')",businessId,clientId);if(!mutation)return;db.prepare("update sync_mutations set sync_status='conflict',last_error='MASTER_DATA_CONFLICT',updated_at=? where business_id=? and client_id=?").run(now(),businessId,clientId);db.prepare("update master_sync_entities set sync_status='conflict' where entity_type=? and local_id=?").run(mutation.entity_type,Number(mutation.entity_id))});return{message:'Conflict recorded.'}});
 app.post('/api/sync/v1/apply',{preHandler:guard},async request=>{const businessId=user(request).business_id,input=z.object({cursor:z.string().nullable().optional(),changes:z.array(change).max(500)}).parse(request.body),old=one(db,"select value from sync_state where key='universal_v1_cursor'")?.value;if(input.cursor&&old&&compare(input.cursor,old)<=0)return{message:'Already reconciled.'};tx(()=>{db.prepare("update master_sync_runtime set value='1' where key='remote_apply'").run();try{for(const remote of input.changes){const local=one(db,'select local_id from master_sync_entities where entity_type=? and sync_id=?',remote.entity_type,remote.sync_id)?.local_id as number|undefined;if(remote.deleted){if(local){remove(db,remote.entity_type,local,businessId);db.prepare("update master_sync_entities set tombstoned=1,sync_status='synced' where entity_type=? and local_id=?").run(remote.entity_type,local)}continue}const id=write(db,remote.entity_type,local,businessId,remote.data,remote.updated_at);db.prepare("insert into master_sync_entities(entity_type,local_id,sync_id,server_id,server_updated_at,sync_status,tombstoned) values(?,?,?,?,?,'synced',0) on conflict(entity_type,local_id) do update set sync_id=excluded.sync_id,server_id=excluded.server_id,server_updated_at=excluded.server_updated_at,sync_status='synced',tombstoned=0").run(remote.entity_type,id,remote.sync_id,remote.server_id,remote.updated_at)}if(input.cursor)db.prepare("insert into sync_state(key,value,updated_at) values('universal_v1_cursor',?,?) on conflict(key) do update set value=excluded.value,updated_at=excluded.updated_at").run(input.cursor,now())}finally{db.prepare("update master_sync_runtime set value='0' where key='remote_apply'").run()}});return{message:'Applied.'}});
}
