import { sql } from 'drizzle-orm';
import { boolean, check, date, index, integer, jsonb, numeric, pgTable, serial, text, timestamp, uniqueIndex, uuid, varchar } from 'drizzle-orm/pg-core';
const timestamps = { createdAt: timestamp('created_at',{withTimezone:true}).notNull().defaultNow(), updatedAt: timestamp('updated_at',{withTimezone:true}).notNull().defaultNow() };
export const businesses=pgTable('businesses',{id:serial('id').primaryKey(),name:varchar('name',{length:255}).notNull(),slug:varchar('slug',{length:255}).notNull(),businessType:varchar('business_type',{length:40}).notNull(),logo:text('logo'),currency:varchar('currency',{length:3}).notNull(),locale:varchar('locale',{length:20}).notNull(),timezone:varchar('timezone',{length:100}).notNull(),taxSettings:jsonb('tax_settings').notNull(),receiptSettings:jsonb('receipt_settings').notNull(),...timestamps});
export const branches=pgTable('branches',{id:serial('id').primaryKey(),businessId:integer('business_id').notNull().references(()=>businesses.id),name:varchar('name',{length:255}).notNull(),code:varchar('code',{length:40}).notNull(),active:boolean('active').notNull(),...timestamps});
export const businessFeatures=pgTable('business_features',{businessId:integer('business_id').notNull().references(()=>businesses.id),feature:varchar('feature',{length:50}).notNull(),createdAt:timestamp('created_at',{withTimezone:true}).notNull()});
export const users = pgTable('users',{ id:serial('id').primaryKey(), businessId:integer('business_id').notNull().default(1).references(()=>businesses.id),branchId:integer('branch_id').references(()=>branches.id),name:varchar('name',{length:255}).notNull(), email:varchar('email',{length:255}).notNull(), password:varchar('password',{length:255}).notNull(), role:varchar('role',{length:20}).notNull().default('worker'), isActive:boolean('is_active').notNull().default(true), ...timestamps },t=>[uniqueIndex('users_email_unique').on(t.email),check('users_role_check',sql`${t.role} in ('patron','worker','owner','admin','manager','cashier','seller','waiter','kitchen','stock_manager')`)]);
export const categories = pgTable('categories',{ id:serial('id').primaryKey(),businessId:integer('business_id').notNull().default(1).references(()=>businesses.id), name:varchar('name',{length:255}).notNull(), image:text('image'),isPublic:boolean('is_public').notNull().default(true), ...timestamps });
export const products = pgTable('products',{ id:serial('id').primaryKey(),businessId:integer('business_id').notNull().default(1).references(()=>businesses.id), categoryId:integer('category_id').references(()=>categories.id,{onDelete:'set null'}), name:varchar('name',{length:255}).notNull(),sku:varchar('sku',{length:100}),barcode:varchar('barcode',{length:100}),unit:varchar('unit',{length:30}).notNull().default('piece'),taxRate:numeric('tax_rate',{precision:6,scale:3}).notNull().default('0'), purchasePrice:numeric('purchase_price',{precision:12,scale:2}).notNull().default('0'), salePrice:numeric('sale_price',{precision:12,scale:2}).notNull(), stock:numeric('stock',{precision:14,scale:3,mode:'number'}).notNull().default(0), minStock:numeric('min_stock',{precision:14,scale:3,mode:'number'}).notNull().default(0), trackStock:boolean('track_stock').notNull().default(true), image:text('image'), isActive:boolean('is_active').notNull().default(true),isPublic:boolean('is_public').notNull().default(true),available:boolean('available').notNull().default(true), ...timestamps },t=>[index('products_category_idx').on(t.categoryId)]);
export const cashRegisterSessions = pgTable('cash_register_sessions',{
  id:serial('id').primaryKey(),businessId:integer('business_id').notNull().default(1).references(()=>businesses.id),branchId:integer('branch_id').references(()=>branches.id), businessDate:date('business_date').notNull(), status:varchar('status',{length:10}).notNull().default('open'),
  openedAt:timestamp('opened_at',{withTimezone:true}).notNull().defaultNow(), openedByUserId:integer('opened_by_user_id').notNull().references(()=>users.id),
  openingCash:numeric('opening_cash',{precision:12,scale:2}).notNull(), openingNote:text('opening_note'),
  closedAt:timestamp('closed_at',{withTimezone:true}), closedByUserId:integer('closed_by_user_id').references(()=>users.id),
  expectedCash:numeric('expected_cash',{precision:12,scale:2}), actualCash:numeric('actual_cash',{precision:12,scale:2}),
  difference:numeric('difference',{precision:12,scale:2}), closingNote:text('closing_note'), ...timestamps,
},t=>[
  check('cash_register_sessions_status_check',sql`${t.status} in ('open','closed')`),
  check('cash_register_sessions_opening_cash_check',sql`${t.openingCash} >= 0`),
  index('cash_register_sessions_business_date_idx').on(t.businessDate),
  uniqueIndex('cash_register_one_open_business_branch_idx').on(t.businessId,t.branchId).where(sql`${t.status} = 'open'`),
]);
export const sales = pgTable('sales',{ id:serial('id').primaryKey(),businessId:integer('business_id').notNull().default(1).references(()=>businesses.id),branchId:integer('branch_id').references(()=>branches.id),clientId:uuid('client_id'),orderId:integer('order_id'), userId:integer('user_id').notNull().references(()=>users.id), cashRegisterSessionId:integer('cash_register_session_id').references(()=>cashRegisterSessions.id,{onDelete:'set null'}), paymentMethod:varchar('payment_method',{length:50}).notNull().default('cash'), note:text('note'), total:numeric('total',{precision:12,scale:2}).notNull().default('0'), profit:numeric('profit',{precision:12,scale:2}).notNull().default('0'), ...timestamps },t=>[index('sales_user_created_idx').on(t.userId,t.createdAt),index('sales_cash_register_session_idx').on(t.cashRegisterSessionId)]);
export const saleItems = pgTable('sale_items',{ id:serial('id').primaryKey(), saleId:integer('sale_id').notNull().references(()=>sales.id,{onDelete:'cascade'}), productId:integer('product_id').notNull().references(()=>products.id), quantity:integer('quantity').notNull(), unitPrice:numeric('unit_price',{precision:12,scale:2}).notNull(), purchasePrice:numeric('purchase_price',{precision:12,scale:2}).notNull().default('0'), total:numeric('total',{precision:12,scale:2}).notNull(), profit:numeric('profit',{precision:12,scale:2}).notNull(), ...timestamps },t=>[index('sale_items_sale_idx').on(t.saleId)]);
export const stockMovements = pgTable('stock_movements',{ id:serial('id').primaryKey(),businessId:integer('business_id').notNull().default(1).references(()=>businesses.id),branchId:integer('branch_id').references(()=>branches.id),clientId:uuid('client_id'), productId:integer('product_id').notNull().references(()=>products.id), userId:integer('user_id').notNull().references(()=>users.id), type:varchar('type',{length:30}).notNull(), quantity:numeric('quantity',{precision:14,scale:3,mode:'number'}).notNull(), beforeStock:numeric('before_stock',{precision:14,scale:3,mode:'number'}).notNull(), afterStock:numeric('after_stock',{precision:14,scale:3,mode:'number'}).notNull(), note:text('note'), ...timestamps },t=>[index('stock_product_created_idx').on(t.productId,t.createdAt)]);
export const settings = pgTable('settings',{ id:serial('id').primaryKey(),businessId:integer('business_id').notNull().default(1).references(()=>businesses.id), key:varchar('key',{length:255}).notNull(), value:text('value'), ...timestamps });
export const refreshTokens = pgTable('refresh_tokens',{ id:serial('id').primaryKey(), userId:integer('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}), tokenHash:varchar('token_hash',{length:64}).notNull(), expiresAt:timestamp('expires_at',{withTimezone:true}).notNull(), revokedAt:timestamp('revoked_at',{withTimezone:true}), createdAt:timestamp('created_at',{withTimezone:true}).notNull().defaultNow() },t=>[uniqueIndex('refresh_token_hash_unique').on(t.tokenHash),index('refresh_user_idx').on(t.userId)]);
export const menuImportSessions = pgTable('menu_import_sessions',{
  id:uuid('id').primaryKey(), userId:integer('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),
  preview:jsonb('preview').notNull(), result:jsonb('result'), status:varchar('status',{length:20}).notNull().default('previewed'),
  createdAt:timestamp('created_at',{withTimezone:true}).notNull().defaultNow(), confirmedAt:timestamp('confirmed_at',{withTimezone:true}),
},t=>[index('menu_import_sessions_user_idx').on(t.userId),check('menu_import_sessions_status_check',sql`${t.status} in ('previewed','confirmed')`)]);
