import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import test from 'node:test';
import Fastify from 'fastify';
import pg from 'pg';

const url=process.env.TEST_DATABASE_URL;
if(url&&!decodeURIComponent(new URL(url).pathname).endsWith('_test'))throw new Error('Disposable _test database required');
process.env.DATABASE_URL=url??'postgresql://unused@localhost/unused_test';process.env.CONTROL_PLANE_DATABASE_URL=process.env.DATABASE_URL;process.env.JWT_SECRET='master-sync-test-secret-at-least-32-characters';process.env.NODE_ENV='test';process.env.SAAS_TENANCY_MODE='shared';
const enabled=Boolean(url),pool=new pg.Pool({connectionString:url});let app:ReturnType<typeof Fastify>;
const ids={customer:'30000000-0000-4000-8000-000000000001',vendor:'30000000-0000-4000-8000-000000000002',license:'30000000-0000-4000-8000-000000000003',certificate:'30000000-0000-4000-8000-000000000004'};
type Device={installation_id:string;public_key:string;privateKey:crypto.KeyObject};
const stable=(v:any):string=>Array.isArray(v)?`[${v.map(stable).join(',')}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(',')}}`:JSON.stringify(v);
function device():Device{const key=crypto.generateKeyPairSync('ed25519');return{installation_id:crypto.randomUUID(),public_key:JSON.stringify(key.publicKey.export({format:'jwk'})),privateKey:key.privateKey}}
function signed(action:string,d:Device,m?:any){const nonce=crypto.randomUUID(),requested_at=new Date().toISOString(),raw={license_id:ids.license,certificate_id:ids.certificate,installation_id:d.installation_id,device_public_key:d.public_key,nonce,requested_at};const line=(x:any)=>x==null?'':String(x);const payload=['desktop-master-sync-v1',action,raw.license_id,raw.certificate_id,raw.installation_id,raw.device_public_key,nonce,requested_at,line(m?.client_id),line(m?.entity_type),line(m?.sync_id),line(m?.operation),line(m?.base_updated_at),m?stable(m.data):''].join('\n');return{...raw,device_proof:crypto.sign(null,Buffer.from(payload),d.privateKey).toString('base64url')}}
async function seed(d:Device){await pool.query('truncate license_customers,businesses,saas_tenants restart identity cascade');await pool.query("insert into license_customers(id,name) values($1,'Master sync')",[ids.customer]);await pool.query("insert into vendor_businesses(id,customer_id,name,business_type,status) values($1,$2,'Master sync','cafe','active')",[ids.vendor,ids.customer]);await pool.query("insert into licenses(id,customer_id,vendor_business_id,business_type,status,allowed_features,max_devices,expires_at) values($1,$2,$3,'cafe','active','[\"pos\"]',5,now()+interval '30 days')",[ids.license,ids.customer,ids.vendor]);await pool.query("insert into businesses(name,slug,business_type,currency,locale,timezone,vendor_business_id) values('Master','master','cafe','MAD','fr-MA','Africa/Casablanca',$1)",[ids.vendor]);const key=crypto.createHash('sha256').update(d.public_key).digest('hex');const did=crypto.randomUUID();await pool.query("insert into license_devices(id,license_id,installation_id,device_public_key,device_fingerprint,channel,status) values($1,$2,$3,$4,$5,'desktop','active')",[did,ids.license,d.installation_id,d.public_key,key]);await pool.query("insert into license_activations(license_id,device_id,certificate_id,kind,status,request_nonce) values($1,$2,$3,'offline','approved',$4)",[ids.license,did,ids.certificate,crypto.randomUUID()])}
async function push(d:Device,m:any){return app.inject({method:'POST',url:'/api/desktop-sync/master-data/push',payload:{device:signed('push',d,m),mutation:m}})}
test.before(async()=>{if(!enabled)return;const mod=await import('./desktop-master-data.js');app=Fastify();app.setErrorHandler((e:any,_r:any,reply:any)=>reply.code(e.statusCode??500).send({message:e.message,code:e.code}));await mod.registerDesktopMasterDataSync(app,{pool,controlPool:pool});await app.ready()});test.after(async()=>{if(enabled){await app.close();await pool.end()}});
test('master data shared tenancy: all entities, pull cursor, tombstones, replay, conflict and device binding',{skip:!enabled},async()=>{const d=device();await seed(d);const cat=crypto.randomUUID(),product=crypto.randomUUID();const entities:any[]=[
 ['branches',{name:'Main',code:'MAIN',address:null,phone:null,active:true}],['settings',{key:'ticket_header',value:'A'}],['categories',{name:'Food',image:null,is_public:true}],['units',{code:'pc',name:'Piece',precision:0,active:true}],['customers',{name:'Customer',phone:null,email:null,address:null,notes:null,active:true}],['suppliers',{name:'Supplier',contact:null,phone:null,email:null,address:null,notes:null,active:true}],
 ['products',{name:'Coffee',sku:null,barcode:null,unit:'pc',tax_rate:0,purchase_price:1,sale_price:2,stock:0,min_stock:0,track_stock:false,image:null,is_active:true,is_public:true,available:true,category_sync_id:cat}],['product_variants',{name:'Large',sku:null,barcode:null,price_delta:1,active:true,product_sync_id:product}],['product_modifiers',{name:'Milk',price:1,active:true,product_sync_id:product}]
 ];
 for(const [entity,data] of entities){const sync_id=entity==='categories'?cat:entity==='products'?product:crypto.randomUUID(),m={client_id:crypto.randomUUID(),entity_type:entity,sync_id,operation:'upsert',base_updated_at:null,data};const first=await push(d,m);assert.equal(first.statusCode,201,first.body);const replay=await push(d,m);assert.equal(replay.statusCode,200,replay.body)}
 const firstPull=await app.inject({method:'GET',url:'/api/desktop-sync/master-data/pull',query:signed('pull',d)});assert.equal(firstPull.statusCode,200,firstPull.body);assert.equal(firstPull.json().data.changes.length,9);const cursor=firstPull.json().data.cursor;const caught=await app.inject({method:'GET',url:'/api/desktop-sync/master-data/pull',query:{...signed('pull',d),cursor}});assert.equal(caught.json().data.changes.length,0);assert.equal(caught.json().data.cursor,cursor);
 const productChange=firstPull.json().data.changes.find((x:any)=>x.sync_id===product);const update={client_id:crypto.randomUUID(),entity_type:'products',sync_id:product,operation:'upsert',base_updated_at:productChange.updated_at,data:{...productChange.data,name:'Coffee local',category_sync_id:cat}};assert.equal((await push(d,update)).statusCode,201);await pool.query("update products set name='Coffee hosted',updated_at=now() where business_id=1 and name='Coffee local'");const conflict={...update,client_id:crypto.randomUUID(),data:{...update.data,name:'must preserve'}};assert.equal((await push(d,conflict)).statusCode,409);
 const del={client_id:crypto.randomUUID(),entity_type:'customers',sync_id:firstPull.json().data.changes.find((x:any)=>x.entity_type==='customers').sync_id,operation:'delete',base_updated_at:null,data:null};assert.equal((await push(d,del)).statusCode,201);const after=await app.inject({method:'GET',url:'/api/desktop-sync/master-data/pull',query:signed('pull',d)});assert.ok(after.json().data.changes.some((x:any)=>x.sync_id===del.sync_id&&x.deleted));await pool.query("update license_devices set status='revoked' where license_id=$1",[ids.license]);assert.equal((await app.inject({method:'GET',url:'/api/desktop-sync/master-data/pull',query:signed('pull',d)})).statusCode,403);
});
