import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import bcrypt from 'bcryptjs';
import Fastify from 'fastify';
import pg from 'pg';
import {openLocalDatabase} from '../local/database.js';
import {ensureLocalPaths,resolveLocalPaths} from '../local/paths.js';
import {buildLocalApp} from '../local/server.js';
import {fingerprint} from '../license/crypto.js';

const url=process.env.TEST_DATABASE_URL;if(url&&!decodeURIComponent(new URL(url).pathname).endsWith('_test'))throw new Error('Disposable _test database required');
process.env.DATABASE_URL=url??'postgresql://unused@localhost/unused_test';process.env.CONTROL_PLANE_DATABASE_URL=process.env.DATABASE_URL;process.env.JWT_SECRET='stock-sync-test-secret-at-least-32-characters';process.env.NODE_ENV='test';process.env.LICENSE_MODE='development';process.env.SAAS_TENANCY_MODE='shared';
const enabled=Boolean(url),pool=new pg.Pool({connectionString:url});let host:ReturnType<typeof Fastify>;
const ids={customer:'70000000-0000-4000-8000-000000000001',vendor:'70000000-0000-4000-8000-000000000002',license:'70000000-0000-4000-8000-000000000003',certificate:'70000000-0000-4000-8000-000000000004'};
type Device={installation_id:string;public_key:string;privateKey:crypto.KeyObject};
function newDevice():Device{const k=crypto.generateKeyPairSync('ed25519');return{installation_id:crypto.randomUUID(),public_key:JSON.stringify(k.publicKey.export({format:'jwk'})),privateKey:k.privateKey}}
const signed=(action:string,d:Device,m?:any)=>{const nonce=crypto.randomUUID(),requested_at=new Date().toISOString(),raw={license_id:ids.license,certificate_id:ids.certificate,installation_id:d.installation_id,device_public_key:d.public_key,nonce,requested_at},line=(x:any)=>x==null?'':String(x),payload=['desktop-stock-sync-v1',action,raw.license_id,raw.certificate_id,raw.installation_id,raw.device_public_key,nonce,requested_at,line(m?.client_id),line(m?.product_sync_id),line(m?.type),line(m?.delta),line(m?.note),line(m?.created_at),line(m?.user_email?.toLowerCase()),line(m?.branch_code)].join('\n');return{...raw,device_proof:crypto.sign(null,Buffer.from(payload),d.privateKey).toString('base64url')}};
async function seedHosted(d:Device){await pool.query('truncate license_customers,businesses,saas_tenants restart identity cascade');await pool.query("insert into license_customers(id,name) values($1,'Stock sync')",[ids.customer]);await pool.query("insert into vendor_businesses(id,customer_id,name,business_type,status) values($1,$2,'Stock sync','cafe','active')",[ids.vendor,ids.customer]);await pool.query("insert into licenses(id,customer_id,vendor_business_id,business_type,status,allowed_features,max_devices,expires_at) values($1,$2,$3,'cafe','active','[\"pos\"]',3,now()+interval '30 days')",[ids.license,ids.customer,ids.vendor]);await pool.query("insert into businesses(name,slug,business_type,currency,locale,timezone,vendor_business_id) values('Stock runtime','stock-runtime','cafe','MAD','fr-MA','Africa/Casablanca',$1)",[ids.vendor]);await pool.query("insert into branches(business_id,name,code,active) values(1,'Main','MAIN',true)");await pool.query("insert into users(business_id,branch_id,name,email,password,role,is_active) values(1,1,'Patron','stock@test.invalid','$2b$04$9ndB7M.v5RKAEp2pKGMSTeE9WsUo8RXvv2A10vWArkjBHv.Lvta9W','patron',true)");const deviceId=crypto.randomUUID();await pool.query("insert into license_devices(id,license_id,installation_id,device_public_key,device_fingerprint,channel,status) values($1,$2,$3,$4,$5,'desktop','active')",[deviceId,ids.license,d.installation_id,d.public_key,fingerprint(d.public_key)]);await pool.query("insert into license_activations(license_id,device_id,certificate_id,kind,status,request_nonce) values($1,$2,$3,'offline','approved',$4)",[ids.license,deviceId,ids.certificate,crypto.randomUUID()]);}
test.before(async()=>{if(enabled){const mod=await import('./desktop-stock-movements.js');host=Fastify();host.setErrorHandler((e:any,_r:any,r:any)=>r.code(e.statusCode??500).send({message:e.message,code:e.code}));await mod.registerDesktopStockMovementSync(host,{pool,controlPool:pool});await host.ready()}});test.after(async()=>{if(enabled){await host.close();await pool.end()}});

test('stock movement SQLite outbox, replay safety, bidirectional pull, and revoked device',{skip:!enabled,concurrency:false},async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'corepos-stock-sync-')),paths=ensureLocalPaths(resolveLocalPaths({BIMIK_DATA_DIR:root})),d=newDevice();let db:any,desktop:any;try{
  await seedHosted(d);const stamp=new Date().toISOString();const hostedProduct=(await pool.query("insert into products(business_id,name,purchase_price,sale_price,stock,min_stock,track_stock,is_active,is_public,available,created_at,updated_at) values(1,'Stock item',1,2,5,0,true,true,true,true,now(),now()) returning id")).rows[0],productSync=(await pool.query("select sync_id from master_sync_rows where business_id=1 and entity_type='products' and entity_id=$1",[hostedProduct.id])).rows[0].sync_id;
  db=openLocalDatabase(paths);db.prepare("insert into businesses(id,name,slug,business_type,currency,locale,timezone,tax_settings_json,receipt_settings_json,vendor_business_id,created_at,updated_at) values(1,'Stock','stock','cafe','MAD','fr-MA','Africa/Casablanca','{}','{}',?,?,?)").run(ids.vendor,stamp,stamp);db.prepare("insert into branches(id,business_id,name,code,active,created_at,updated_at) values(1,1,'Main','MAIN',1,?,?)").run(stamp,stamp);const pw=await bcrypt.hash('secret',4);db.prepare("insert into users(id,name,email,password,role,is_active,business_id,branch_id,created_at,updated_at) values(1,'Patron','stock@test.invalid',?,'patron',1,1,1,?,?)").run(pw,stamp,stamp);const localProduct=Number(db.prepare("insert into products(business_id,name,purchase_price_cents,sale_price_cents,stock,min_stock,track_stock,is_active,is_public,available,created_at,updated_at) values(1,'Stock item',100,200,5,0,1,1,1,1,?,?)").run(stamp,stamp).lastInsertRowid);db.prepare("insert into master_sync_entities(entity_type,local_id,sync_id,server_id,server_updated_at,sync_status) values('products',?,?,? ,?,'synced')").run(localProduct,productSync,hostedProduct.id,stamp);
  desktop=await buildLocalApp({paths,database:db});let login=await desktop.inject({method:'POST',url:'/api/login',payload:{email:'stock@test.invalid',password:'secret'}}),auth={authorization:`Bearer ${login.json().data.access_token}`};const added=await desktop.inject({method:'POST',url:`/api/products/${localProduct}/stock/increase`,headers:auth,payload:{quantity:10,note:'offline receipt'}});assert.equal(added.statusCode,200,added.body);const firstOut=(await desktop.inject({method:'GET',url:'/api/sync/stock-movements/outbox',headers:auth})).json().data;assert.equal(firstOut.length,1);const event=firstOut[0];await desktop.close();desktop=null;db.close();db=null;assert.ok(fs.existsSync(paths.database));db=openLocalDatabase(paths);desktop=await buildLocalApp({paths,database:db});login=await desktop.inject({method:'POST',url:'/api/login',payload:{email:'stock@test.invalid',password:'secret'}});auth={authorization:`Bearer ${login.json().data.access_token}`};assert.equal((await desktop.inject({method:'GET',url:'/api/sync/stock-movements/outbox',headers:auth})).json().data[0].client_id,event.client_id);
  const push=()=>host.inject({method:'POST',url:'/api/desktop-sync/stock-movements/push',payload:{device:signed('push',d,event),mutation:event}});assert.equal((await push()).statusCode,201);assert.equal(Number((await pool.query('select stock from products where id=$1',[hostedProduct.id])).rows[0].stock),15);assert.equal((await push()).statusCode,200);assert.equal(Number((await pool.query('select stock from products where id=$1',[hostedProduct.id])).rows[0].stock),15);assert.equal((await pool.query('select count(*)::int n from stock_movements where client_id=$1',[event.client_id])).rows[0].n,1);
  const remoteId=crypto.randomUUID();await pool.query("update products set stock=18 where id=$1",[hostedProduct.id]);await pool.query("insert into stock_movements(business_id,branch_id,product_id,user_id,type,quantity,before_stock,after_stock,note,client_id,created_at,updated_at) values(1,1,$1,1,'in',3,15,18,'hosted receipt',$2,now(),now())",[hostedProduct.id,remoteId]);const pull=async(cursor:string|null=null)=>host.inject({method:'GET',url:'/api/desktop-sync/stock-movements/pull',query:{...signed('pull',d),cursor:cursor??''}});const remotePull=await pull();assert.equal(remotePull.statusCode,200,remotePull.body);assert.ok(remotePull.json().data.movements.some((m:any)=>m.client_id===remoteId));const localApply=async(data:any)=>desktop.inject({method:'POST',url:'/api/sync/stock-movements/apply',headers:auth,payload:data});const applied=await localApply(remotePull.json().data);assert.equal(applied.statusCode,200,applied.body);assert.equal(db.prepare('select stock from products where id=?').get(localProduct).stock,18);const second=await localApply(remotePull.json().data);assert.equal(second.statusCode,200,second.body);assert.equal(db.prepare('select stock from products where id=?').get(localProduct).stock,18);assert.equal(db.prepare('select count(*) n from stock_movements where client_id=?').get(remoteId).n,1);
  await pool.query("update license_devices set status='revoked' where license_id=$1",[ids.license]);const denied=await host.inject({method:'GET',url:'/api/desktop-sync/stock-movements/pull',query:signed('pull',d)});assert.equal(denied.statusCode,403);assert.equal(denied.json().code,'DEVICE_REVOKED');
 }finally{if(desktop)await desktop.close();if(db)db.close();fs.rmSync(root,{recursive:true,force:true})}
});
