import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import test from 'node:test';
import Fastify from 'fastify';
import pg from 'pg';
import {fingerprint} from '../license/crypto.js';

const url=process.env.TEST_DATABASE_URL;if(url&&!decodeURIComponent(new URL(url).pathname).endsWith('_test'))throw new Error('Disposable _test database required');
process.env.DATABASE_URL=url??'postgresql://unused@localhost/unused_test';process.env.CONTROL_PLANE_DATABASE_URL=process.env.DATABASE_URL;process.env.SAAS_TENANT_DATABASE_URL_TEMPLATE=process.env.DATABASE_URL.replace(/\/[^/]+$/,'/{database}');process.env.SAAS_DATABASE_ADMIN_URL=process.env.DATABASE_URL.replace(/\/[^/]+$/,'/postgres');process.env.JWT_SECRET='stock-dpt-test-secret-at-least-32-characters';process.env.NODE_ENV='test';process.env.SAAS_TENANCY_MODE='database_per_tenant';
const enabled=Boolean(url),control=new pg.Pool({connectionString:url}),dbA='corepos_stock_dpt_a_test',dbB='corepos_stock_dpt_b_test',urlA=url?new URL(url):null,urlB=url?new URL(url):null;
if(urlA)urlA.pathname=`/${dbA}`;if(urlB)urlB.pathname=`/${dbB}`;const a=new pg.Pool({connectionString:urlA?.toString()}),b=new pg.Pool({connectionString:urlB?.toString()});
const ids={customer:'71000000-0000-4000-8000-000000000001',vendorA:'71000000-0000-4000-8000-000000000002',vendorB:'71000000-0000-4000-8000-000000000005',tenantA:'71000000-0000-4000-8000-000000000003',tenantB:'71000000-0000-4000-8000-000000000006',license:'71000000-0000-4000-8000-000000000004',certificate:'71000000-0000-4000-8000-000000000007'};
const deviceKeys=crypto.generateKeyPairSync('ed25519'),installation=crypto.randomUUID(),publicKey=JSON.stringify(deviceKeys.publicKey.export({format:'jwk'})),productSync='72000000-0000-4000-8000-000000000001',clientId='72000000-0000-4000-8000-000000000002';
const sign=(action:string,m?:any)=>{const nonce=crypto.randomUUID(),requested_at=new Date().toISOString(),raw={license_id:ids.license,certificate_id:ids.certificate,installation_id:installation,device_public_key:publicKey,nonce,requested_at},line=(x:any)=>x==null?'':String(x),payload=['desktop-stock-sync-v1',action,raw.license_id,raw.certificate_id,raw.installation_id,raw.device_public_key,nonce,requested_at,line(m?.client_id),line(m?.product_sync_id),line(m?.type),line(m?.delta),line(m?.note),line(m?.created_at),line(m?.user_email?.toLowerCase()),line(m?.branch_code)].join('\n');return{...raw,device_proof:crypto.sign(null,Buffer.from(payload),deviceKeys.privateKey).toString('base64url')}};
let app:ReturnType<typeof Fastify>;
test.before(async()=>{if(!enabled)return;await control.query(`drop database if exists ${dbA} with (force)`);await control.query(`drop database if exists ${dbB} with (force)`);await control.query(`create database ${dbA}`);await control.query(`create database ${dbB}`);const {migrateTenantDatabase}=await import('../saas/tenant-provisioning.js');await migrateTenantDatabase(a);await migrateTenantDatabase(b);await control.query('truncate license_customers,saas_tenants restart identity cascade');await control.query("insert into license_customers(id,name) values($1,'Stock DPT')",[ids.customer]);for(const[vendor,tenant,slug,database,pool]of[[ids.vendorA,ids.tenantA,'stock-dpt-a',dbA,a],[ids.vendorB,ids.tenantB,'stock-dpt-b',dbB,b]] as const){await control.query("insert into vendor_businesses(id,customer_id,name,business_type,status) values($1,$2,$3,'cafe','active')",[vendor,ids.customer,slug]);await control.query('insert into saas_tenants(id,vendor_business_id,slug,database_name,status) values($1,$2,$3,$4,$5)',[tenant,vendor,slug,database,'active']);await pool.query("insert into businesses(name,slug,business_type,currency,locale,timezone,vendor_business_id) values($1,$2,'cafe','MAD','fr-MA','Africa/Casablanca',$3)",[slug,slug,vendor]);await pool.query("insert into branches(business_id,name,code,active) values(1,'Main','MAIN',true)");await pool.query("insert into users(business_id,branch_id,name,email,password,role,is_active) values(1,1,'Owner','stock@dpt.test','$2b$04$9ndB7M.v5RKAEp2pKGMSTeE9WsUo8RXvv2A10vWArkjBHv.Lvta9W','owner',true)");const p=(await pool.query("insert into products(business_id,name,purchase_price,sale_price,stock,min_stock,track_stock,is_active,is_public,available) values(1,'Stock',1,2,5,0,true,true,true,true) returning id")).rows[0];await pool.query("update master_sync_rows set sync_id=$1 where business_id=1 and entity_type='products' and entity_id=$2",[productSync,p.id])}await control.query("insert into licenses(id,customer_id,vendor_business_id,business_type,status,allowed_features,max_devices,expires_at) values($1,$2,$3,'cafe','active','[\"pos\"]',2,now()+interval '30 days')",[ids.license,ids.customer,ids.vendorA]);const did=crypto.randomUUID();await control.query("insert into license_devices(id,license_id,installation_id,device_public_key,device_fingerprint,channel,status) values($1,$2,$3,$4,$5,'desktop','active')",[did,ids.license,installation,publicKey,fingerprint(publicKey)]);await control.query("insert into license_activations(license_id,device_id,certificate_id,kind,status,request_nonce) values($1,$2,$3,'offline','approved',$4)",[ids.license,did,ids.certificate,crypto.randomUUID()]);const mod=await import('./desktop-stock-movements.js');app=Fastify();app.setErrorHandler((e:any,_r:any,r:any)=>r.code(e.statusCode??500).send({message:e.message,code:e.code}));await mod.registerDesktopStockMovementSync(app,{pool:control,controlPool:control});await app.ready()});
test.after(async()=>{if(enabled){if(app)await app.close();const {closeTenantPools}=await import('../saas/tenant-context.js');await closeTenantPools();await a.end();await b.end();await control.query(`drop database if exists ${dbA} with (force)`);await control.query(`drop database if exists ${dbB} with (force)`);await control.end()}});
test('stock sync resolves the licensed database-per-tenant runtime and isolates another tenant',{skip:!enabled,concurrency:false},async()=>{const mutation={client_id:clientId,product_sync_id:productSync,type:'in',delta:10,note:'desktop',created_at:new Date().toISOString(),user_email:'stock@dpt.test',branch_code:'MAIN'},response=await app.inject({method:'POST',url:'/api/desktop-sync/stock-movements/push',payload:{device:sign('push',mutation),mutation}});assert.equal(response.statusCode,201,response.body);assert.equal(Number((await a.query('select stock from products where business_id=1')).rows[0].stock),15);assert.equal(Number((await b.query('select stock from products where business_id=1')).rows[0].stock),5);assert.equal((await b.query('select count(*)::int n from stock_movements')).rows[0].n,0)});
