import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import test from 'node:test';
import Fastify from 'fastify';
import pg from 'pg';
import {fingerprint} from '../license/crypto.js';
import {registerDesktopSalesSync} from './desktop-sales.js';

const url=process.env.TEST_DATABASE_URL;
if(url&&!decodeURIComponent(new URL(url).pathname).endsWith('_test'))throw Error('Disposable _test database required');
process.env.DATABASE_URL=url??'postgresql://unused@localhost/unused_test';
process.env.CONTROL_PLANE_DATABASE_URL=process.env.DATABASE_URL;
process.env.JWT_SECRET='linked-sales-test-secret-at-least-32-characters';
process.env.NODE_ENV='test';
process.env.LICENSE_MODE='development';
process.env.SAAS_TENANCY_MODE='shared';
const enabled=Boolean(url),pool=new pg.Pool({connectionString:url});
const ids={customer:'73000000-0000-4000-8000-000000000001',vendor:'73000000-0000-4000-8000-000000000002',license:'73000000-0000-4000-8000-000000000003',certificate:'73000000-0000-4000-8000-000000000004'};
type Device={installation_id:string;public_key:string;privateKey:crypto.KeyObject};
const device=():Device=>{const key=crypto.generateKeyPairSync('ed25519');return{installation_id:crypto.randomUUID(),public_key:JSON.stringify(key.publicKey.export({format:'jwk'})),privateKey:key.privateKey}};
const signed=(action:string,d:Device,m?:any)=>{const nonce=crypto.randomUUID(),requested_at=new Date().toISOString(),raw={license_id:ids.license,certificate_id:ids.certificate,installation_id:d.installation_id,device_public_key:d.public_key,nonce,requested_at},line=(value:any)=>value==null?'':String(value),payload=['desktop-sales-sync-v1',action,raw.license_id,raw.certificate_id,raw.installation_id,raw.device_public_key,nonce,requested_at,line(m?.client_id),line(m?.operation),line(m?.base_updated_at),m?JSON.stringify(m.data):''].join('\n');return{...raw,device_proof:crypto.sign(null,Buffer.from(payload),d.privateKey).toString('base64url')}};
let host:any;

test.before(async()=>{if(enabled){host=Fastify();host.setErrorHandler((error:any,_request:any,reply:any)=>reply.code(error.statusCode??500).send({message:error.message,code:error.code}));await registerDesktopSalesSync(host,{pool,controlPool:pool});await host.ready();}});
test.after(async()=>{if(enabled){await host.close();await pool.end();}});

test('linked sale uses every authoritative order line for duplicate products without another stock movement',{skip:!enabled,concurrency:false},async()=>{
  const d=device();
  await pool.query('truncate license_customers,businesses,saas_tenants restart identity cascade');
  await pool.query("insert into license_customers(id,name) values($1,'Linked lines')",[ids.customer]);
  await pool.query("insert into vendor_businesses(id,customer_id,name,business_type,status) values($1,$2,'Linked lines','cafe','active')",[ids.vendor,ids.customer]);
  await pool.query("insert into licenses(id,customer_id,vendor_business_id,business_type,status,allowed_features,max_devices,expires_at) values($1,$2,$3,'cafe','active','[\"pos\"]',2,now()+interval '30 days')",[ids.license,ids.customer,ids.vendor]);
  await pool.query("insert into businesses(name,slug,business_type,currency,locale,timezone,vendor_business_id) values('Linked lines','linked-lines','cafe','MAD','fr-MA','Africa/Casablanca',$1)",[ids.vendor]);
  await pool.query("insert into branches(business_id,name,code,active) values(1,'Main','MAIN',true);insert into users(business_id,branch_id,name,email,password,role,is_active) values(1,1,'Owner','owner@linked.test','$2b$04$9ndB7M.v5RKAEp2pKGMSTeE9WsUo8RXvv2A10vWArkjBHv.Lvta9W','owner',true)");
  const product=(await pool.query("insert into products(business_id,name,purchase_price,sale_price,stock,min_stock,track_stock,is_active,is_public,available) values(1,'Coffee',2,10,0,0,true,true,true,true) returning id")).rows[0];
  const productSync=(await pool.query("select sync_id from master_sync_rows where business_id=1 and entity_type='products' and entity_id=$1",[product.id])).rows[0].sync_id;
  const deviceId=crypto.randomUUID();
  await pool.query("insert into license_devices(id,license_id,installation_id,device_public_key,device_fingerprint,channel,status) values($1,$2,$3,$4,$5,'desktop','active')",[deviceId,ids.license,d.installation_id,d.public_key,fingerprint(d.public_key)]);
  await pool.query("insert into license_activations(license_id,device_id,certificate_id,kind,status,request_nonce) values($1,$2,$3,'offline','approved',$4)",[ids.license,deviceId,ids.certificate,crypto.randomUUID()]);
  const session=(await pool.query("insert into cash_register_sessions(business_id,branch_id,business_date,status,opened_by_user_id,opening_cash) values(1,1,current_date,'open',1,0) returning id")).rows[0];
  const orderClientId=crypto.randomUUID(),order=(await pool.query("insert into orders(business_id,branch_id,client_id,order_number,source,type,user_id,status,subtotal,discount,tax,total,payment_status,sync_status) values(1,1,$1,'DUPLICATE-LINES','pos','retail',1,'pending',20,3,0,17,'unpaid','synced') returning id",[orderClientId])).rows[0];
  await pool.query("insert into order_items(order_id,product_id,quantity,unit_price,discount,tax,total) values($1,$2,1,10,2,0,8),($1,$2,1,10,1,0,9)",[order.id,product.id]);
  await pool.query("insert into stock_movements(business_id,branch_id,product_id,user_id,type,quantity,before_stock,after_stock,note,client_id) values(1,1,$1,1,'sale',2,2,0,'Order already applied',$2)",[product.id,crypto.randomUUID()]);
  const mutation={client_id:crypto.randomUUID(),operation:'create',data:{branch_code:'MAIN',user_email:'owner@linked.test',payment_method:'cash',note:'linked order',order_client_id:orderClientId,cash_register_session_server_id:Number(session.id),items:[{product_sync_id:productSync,quantity:2}]}};
  const push=()=>host.inject({method:'POST',url:'/api/desktop-sync/sales/push',payload:{device:signed('push',d,mutation),mutation}});
  assert.equal((await push()).statusCode,201);
  assert.equal((await push()).statusCode,200);
  const sale=(await pool.query('select * from sales where client_id=$1',[mutation.client_id])).rows[0];
  assert.equal(Number(sale.total),17);
  assert.equal(Number(sale.order_id),Number(order.id));
  assert.equal(Number(sale.cash_register_session_id),Number(session.id));
  assert.equal((await pool.query('select count(*)::int n from sales where client_id=$1',[mutation.client_id])).rows[0].n,1);
  assert.equal(Number((await pool.query('select stock from products where id=$1',[product.id])).rows[0].stock),0);
  assert.equal((await pool.query("select count(*)::int n from stock_movements where product_id=$1 and type='sale'",[product.id])).rows[0].n,1);
  const orderLines=(await pool.query('select quantity,unit_price,discount,total from order_items where order_id=$1 order by id',[order.id])).rows.map((line:any)=>({quantity:Number(line.quantity),unit:Number(line.unit_price),discount:Number(line.discount),total:Number(line.total)}));
  const saleLines=(await pool.query('select quantity,unit_price,total from sale_items where sale_id=$1 order by id',[sale.id])).rows.map((line:any)=>({quantity:Number(line.quantity),unit:Number(line.unit_price),total:Number(line.total)}));
  assert.deepEqual(orderLines,[{quantity:1,unit:10,discount:2,total:8},{quantity:1,unit:10,discount:1,total:9}]);
  assert.deepEqual(saleLines,orderLines.map(({quantity,unit,total})=>({quantity,unit,total})));
});
