import crypto from 'node:crypto';
import type {FastifyInstance} from 'fastify';
import type pg from 'pg';
import {z} from 'zod';
import {config} from '../config.js';
import {activationRequestIsFresh} from '../license/policy.js';
import {fingerprint} from '../license/crypto.js';
import {tenantRuntime,type TenantRecord} from '../saas/tenant-context.js';

const entities=['branches','settings','categories','units','products','product_variants','product_modifiers','customers','suppliers'] as const;
const entitySchema=z.enum(entities);type Entity=typeof entities[number];
type Device={licenseId:string;certificateId:string;installationId:string;publicKey:string;nonce:string;requestedAt:string;proof:string};
type Runtime={pool:pg.Pool;businessId:number};
const deviceSchema=z.object({license_id:z.string().uuid(),certificate_id:z.string().uuid(),installation_id:z.string().uuid(),device_public_key:z.string().min(40).max(5000),nonce:z.string().uuid(),requested_at:z.string().datetime(),device_proof:z.string().min(40).max(500)}).strict();
const mutationSchema=z.object({client_id:z.string().uuid(),entity_type:entitySchema,sync_id:z.string().uuid(),operation:z.enum(['upsert','delete']),base_updated_at:z.string().datetime().nullable(),data:z.record(z.string(),z.unknown()).nullable()}).strict();
const stable=(value:unknown):string=>Array.isArray(value)?`[${value.map(stable).join(',')}]`:value&&typeof value==='object'?`{${Object.keys(value as object).sort().map(k=>`${JSON.stringify(k)}:${stable((value as Record<string,unknown>)[k])}`).join(',')}}`:JSON.stringify(value);
const proofPayload=(action:string,d:Device,m?:z.infer<typeof mutationSchema>)=>['desktop-master-sync-v1',action,d.licenseId,d.certificateId,d.installationId,d.publicKey,d.nonce,d.requestedAt,m?.client_id??'',m?.entity_type??'',m?.sync_id??'',m?.operation??'',m?.base_updated_at??'',m?stable(m.data):''].join('\n');
const verify=(key:string,payload:string,signature:string)=>{try{return crypto.verify(null,Buffer.from(payload),crypto.createPublicKey({key:JSON.parse(key),format:'jwk'}),Buffer.from(signature,'base64url'))}catch{return false}};
const fail=(message:string,statusCode:number,code:string)=>Object.assign(new Error(message),{statusCode,code});
type Cursor={updatedAt:string;id:number};
const parseCursor=(value:unknown):Cursor|null=>{if(typeof value!=='string'||!value)return null;const p=value.lastIndexOf('|'),updatedAt=p<0?value:value.slice(0,p),id=p<0?0:Number(value.slice(p+1));return Number.isNaN(Date.parse(updatedAt))||!Number.isInteger(id)||id<0?null:{updatedAt,id}};

export async function registerDesktopMasterDataSync(app:FastifyInstance,{pool,controlPool}:{pool:pg.Pool;controlPool:pg.Pool}){
  async function runtime(raw:unknown,action:string,mutation?:z.infer<typeof mutationSchema>):Promise<Runtime>{
    const parsed=deviceSchema.safeParse(raw);if(!parsed.success)throw fail('Invalid desktop sync request.',422,'SYNC_INPUT_INVALID');const d:Device={licenseId:parsed.data.license_id,certificateId:parsed.data.certificate_id,installationId:parsed.data.installation_id,publicKey:parsed.data.device_public_key,nonce:parsed.data.nonce,requestedAt:parsed.data.requested_at,proof:parsed.data.device_proof};
    if(!activationRequestIsFresh(d.requestedAt))throw fail('Sync request timestamp is outside the allowed window.',422,'SYNC_REQUEST_STALE');
    if(!verify(d.publicKey,proofPayload(action,d,mutation),d.proof))throw fail('Device sync proof is invalid.',403,'DEVICE_PROOF_INVALID');
    const binding=(await controlPool.query(`select d.id device_id,d.status device_status,d.channel,d.device_public_key,d.device_fingerprint,l.status license_status,l.expires_at,vb.id vendor_business_id,vb.status vendor_business_status,t.id tenant_id,t.control_business_id,t.slug,t.database_name,t.status tenant_status
      from license_devices d join licenses l on l.id=d.license_id join vendor_businesses vb on vb.id=l.vendor_business_id left join saas_tenants t on t.vendor_business_id=vb.id
      where d.license_id=$1 and d.installation_id=$2 and d.id in(select device_id from license_activations where license_id=$1 and certificate_id=$3 and status='approved') limit 1`,[d.licenseId,d.installationId,d.certificateId])).rows[0];
    if(!binding||binding.channel!=='desktop'||binding.device_status!=='active')throw fail('Desktop device is not active.',403,'DEVICE_REVOKED');
    if(binding.device_public_key!==d.publicKey||binding.device_fingerprint!==fingerprint(d.publicKey))throw fail('Device identity mismatch.',403,'DEVICE_IDENTITY_MISMATCH');
    if(binding.license_status!=='active'||binding.vendor_business_status!=='active'||(binding.expires_at&&Date.parse(binding.expires_at)<=Date.now()))throw fail('License is not active.',403,'LICENSE_INACTIVE');
    let operational=pool;if(config.SAAS_TENANCY_MODE==='database_per_tenant'){if(!binding.tenant_id||binding.tenant_status!=='active')throw fail('Tenant runtime is unavailable.',403,'TENANT_INACTIVE');operational=tenantRuntime({id:binding.tenant_id,vendorBusinessId:binding.vendor_business_id,controlBusinessId:binding.control_business_id,slug:binding.slug,databaseName:binding.database_name,status:binding.tenant_status} as TenantRecord).pool}
    const business=(await operational.query('select id from businesses where vendor_business_id=$1 limit 1',[binding.vendor_business_id])).rows[0];if(!business)throw fail('Licensed Business runtime is unavailable.',409,'BUSINESS_RUNTIME_UNAVAILABLE');
    await controlPool.query('update license_devices set last_seen_at=now() where id=$1',[binding.device_id]);return{pool:operational,businessId:business.id};
  }
  app.get('/api/desktop-sync/master-data/pull',async request=>{const raw=request.query as Record<string,unknown>,{cursor:rawCursor,...device}=raw,ctx=await runtime(device,'pull'),cursor=parseCursor(rawCursor);const rows=(await ctx.pool.query(`select r.id,r.entity_type,r.entity_id,r.sync_id,
      case r.entity_type
        when 'products' then r.payload || jsonb_build_object('category_sync_id',(select sync_id::text from master_sync_rows x where x.business_id=r.business_id and x.entity_type='categories' and x.entity_id=nullif(r.payload->>'category_id','')::int))
        when 'product_variants' then r.payload || jsonb_build_object('product_sync_id',(select sync_id::text from master_sync_rows x where x.business_id=r.business_id and x.entity_type='products' and x.entity_id=(r.payload->>'product_id')::int))
        when 'product_modifiers' then r.payload || jsonb_build_object('product_sync_id',(select sync_id::text from master_sync_rows x where x.business_id=r.business_id and x.entity_type='products' and x.entity_id=(r.payload->>'product_id')::int))
        else r.payload end payload,r.deleted,r.updated_at,to_char(r.updated_at at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"') sync_updated_at from master_sync_rows r where r.business_id=$1 and ($2::timestamptz is null or r.updated_at>$2::timestamptz or(r.updated_at=$2::timestamptz and r.id>$3)) order by r.updated_at,r.id limit 500`,[ctx.businessId,cursor?.updatedAt??null,cursor?.id??0])).rows;const last=rows.at(-1),next=last?`${last.sync_updated_at}|${last.id}`:(typeof rawCursor==='string'&&rawCursor?rawCursor:null);return{data:{changes:rows.map(row=>({entity_type:row.entity_type,sync_id:row.sync_id,server_id:Number(row.entity_id),deleted:row.deleted,updated_at:new Date(row.updated_at).toISOString(),data:row.payload})),cursor:next}};});
  app.post('/api/desktop-sync/master-data/push',async(request,reply)=>{const body=z.object({device:deviceSchema,mutation:mutationSchema}).strict().parse(request.body),ctx=await runtime(body.device,'push',body.mutation),client=await ctx.pool.connect();try{await client.query('begin');const seen=(await client.query('select payload,sync_status from sync_mutations where business_id=$1 and client_id=$2 for update',[ctx.businessId,body.mutation.client_id])).rows[0];if(seen){await client.query('commit');return reply.code(seen.payload?.outcome==='conflict'?409:200).send({data:seen.payload,replayed:true})}
      const current=(await client.query('select * from master_sync_rows where business_id=$1 and entity_type=$2 and sync_id=$3 for update',[ctx.businessId,body.mutation.entity_type,body.mutation.sync_id])).rows[0];
      if(current&&body.mutation.base_updated_at&&new Date(current.updated_at).getTime()!==Date.parse(body.mutation.base_updated_at)){const outcome={outcome:'conflict',updated_at:new Date(current.updated_at).toISOString()};await client.query("insert into sync_mutations(business_id,client_id,entity_type,entity_id,operation,payload,sync_status,error) values($1,$2,$3,$4,$5,$6,'conflict','MASTER_DATA_CONFLICT')",[ctx.businessId,body.mutation.client_id,body.mutation.entity_type,String(current.entity_id),body.mutation.operation,outcome]);await client.query('commit');return reply.code(409).send({data:outcome})}
      const data=body.mutation.data??{} as Record<string,any>;let entityId=current?.entity_id as number|undefined;
      const dependency=async(type:Entity,syncId:unknown)=>{if(!syncId)return null;const row=(await client.query('select entity_id from master_sync_rows where business_id=$1 and entity_type=$2 and sync_id=$3 and deleted=false',[ctx.businessId,type,String(syncId)])).rows[0];if(!row)throw fail('Synchronized dependency is unavailable.',409,'SYNC_DEPENDENCY_MISSING');return row.entity_id as number};
      if(body.mutation.operation==='delete'){if(entityId){const tables:Record<Entity,string>={branches:'branches',settings:'settings',categories:'categories',units:'units',products:'products',product_variants:'product_variants',product_modifiers:'product_modifiers',customers:'customers',suppliers:'suppliers'};await client.query(`delete from ${tables[body.mutation.entity_type]} where id=$1 and business_id=$2`,[entityId,ctx.businessId])}}
      else {const e=body.mutation.entity_type;if(e==='branches'){entityId?await client.query('update branches set name=$1,code=$2,address=$3,phone=$4,active=$5,updated_at=now() where id=$6 and business_id=$7',[data.name,data.code,data.address??null,data.phone??null,Boolean(data.active),entityId,ctx.businessId]):entityId=(await client.query('insert into branches(business_id,name,code,address,phone,active) values($1,$2,$3,$4,$5,$6) returning id',[ctx.businessId,data.name,data.code,data.address??null,data.phone??null,Boolean(data.active)])).rows[0].id}
        else if(e==='settings'){entityId?await client.query('update settings set key=$1,value=$2,updated_at=now() where id=$3 and business_id=$4',[data.key,data.value??null,entityId,ctx.businessId]):entityId=(await client.query('insert into settings(business_id,key,value) values($1,$2,$3) returning id',[ctx.businessId,data.key,data.value??null])).rows[0].id}
        else if(e==='categories'){entityId?await client.query('update categories set name=$1,image=$2,is_public=$3,updated_at=now() where id=$4 and business_id=$5',[data.name,data.image??null,Boolean(data.is_public),entityId,ctx.businessId]):entityId=(await client.query('insert into categories(business_id,name,image,is_public) values($1,$2,$3,$4) returning id',[ctx.businessId,data.name,data.image??null,Boolean(data.is_public)])).rows[0].id}
        else if(e==='units'){entityId?await client.query('update units set code=$1,name=$2,precision=$3,active=$4,updated_at=now() where id=$5 and business_id=$6',[data.code,data.name,Number(data.precision),Boolean(data.active),entityId,ctx.businessId]):entityId=(await client.query('insert into units(business_id,code,name,precision,active) values($1,$2,$3,$4,$5) returning id',[ctx.businessId,data.code,data.name,Number(data.precision),Boolean(data.active)])).rows[0].id}
        else if(e==='products'){const category=await dependency('categories',data.category_sync_id);const v=[category,data.name,data.sku??null,data.barcode??null,data.unit??'piece',data.tax_rate??0,data.purchase_price??0,data.sale_price??0,data.stock??0,data.min_stock??0,Boolean(data.track_stock),data.image??null,Boolean(data.is_active),Boolean(data.is_public),Boolean(data.available)];entityId?await client.query('update products set category_id=$1,name=$2,sku=$3,barcode=$4,unit=$5,tax_rate=$6,purchase_price=$7,sale_price=$8,stock=$9,min_stock=$10,track_stock=$11,image=$12,is_active=$13,is_public=$14,available=$15,updated_at=now() where id=$16 and business_id=$17',[...v,entityId,ctx.businessId]):entityId=(await client.query('insert into products(business_id,category_id,name,sku,barcode,unit,tax_rate,purchase_price,sale_price,stock,min_stock,track_stock,image,is_active,is_public,available) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) returning id',[ctx.businessId,...v])).rows[0].id}
        else if(e==='product_variants'||e==='product_modifiers'){const product=await dependency('products',data.product_sync_id);if(e==='product_variants'){const v=[product,data.name,data.sku??null,data.barcode??null,data.price_delta??0,Boolean(data.active)];entityId?await client.query('update product_variants set product_id=$1,name=$2,sku=$3,barcode=$4,price_delta=$5,active=$6,updated_at=now() where id=$7 and business_id=$8',[...v,entityId,ctx.businessId]):entityId=(await client.query('insert into product_variants(business_id,product_id,name,sku,barcode,price_delta,active) values($1,$2,$3,$4,$5,$6,$7) returning id',[ctx.businessId,...v])).rows[0].id}else{const v=[product,data.name,data.price??0,Boolean(data.active)];entityId?await client.query('update product_modifiers set product_id=$1,name=$2,price=$3,active=$4,updated_at=now() where id=$5 and business_id=$6',[...v,entityId,ctx.businessId]):entityId=(await client.query('insert into product_modifiers(business_id,product_id,name,price,active) values($1,$2,$3,$4,$5) returning id',[ctx.businessId,...v])).rows[0].id}}
        else {const cols=e==='customers'?['name','phone','email','address','notes','active']:['name','contact','phone','email','address','notes','active'];const values=cols.map(k=>k==='active'?Boolean(data[k]):data[k]??null);if(entityId)await client.query(`update ${e} set ${cols.map((k,i)=>`${k}=$${i+1}`).join(',')},updated_at=now() where id=$${cols.length+1} and business_id=$${cols.length+2}`,[...values,entityId,ctx.businessId]);else entityId=(await client.query(`insert into ${e}(business_id,${cols.join(',')}) values($1,${cols.map((_,i)=>`$${i+2}`).join(',')}) returning id`,[ctx.businessId,...values])).rows[0].id}
        await client.query('update master_sync_rows set sync_id=$1 where business_id=$2 and entity_type=$3 and entity_id=$4',[body.mutation.sync_id,ctx.businessId,e,entityId]);}
      const row=(await client.query('select entity_id,sync_id,payload,deleted,updated_at from master_sync_rows where business_id=$1 and entity_type=$2 and sync_id=$3',[ctx.businessId,body.mutation.entity_type,body.mutation.sync_id])).rows[0];const outcome={outcome:'applied',change:{entity_type:body.mutation.entity_type,sync_id:row.sync_id,server_id:Number(row.entity_id),deleted:row.deleted,updated_at:new Date(row.updated_at).toISOString(),data:row.payload}};await client.query("insert into sync_mutations(business_id,client_id,entity_type,entity_id,operation,payload,sync_status) values($1,$2,$3,$4,$5,$6,'synced')",[ctx.businessId,body.mutation.client_id,body.mutation.entity_type,String(entityId??current?.entity_id),body.mutation.operation,outcome]);await client.query('commit');return reply.code(201).send({data:outcome});
    }catch(error){await client.query('rollback');throw error}finally{client.release()}});
}
