import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import test from 'node:test';
import Fastify from 'fastify';
import type {FastifyReply,FastifyRequest} from 'fastify';
import pg from 'pg';

const controlUrl=process.env.TEST_DATABASE_URL;
if(process.env.REQUIRE_POSTGRES_INTEGRATION==='true'&&!controlUrl)throw new Error('TEST_DATABASE_URL required');
if(controlUrl&&!decodeURIComponent(new URL(controlUrl).pathname).endsWith('_test'))throw new Error('Disposable _test database required');
const tenantDatabase='corepos_cash_sync_tenant_test';
const tenantUrl=`postgresql://postgres:corepos_test_password@127.0.0.1:55433/${tenantDatabase}`;
process.env.DATABASE_URL=controlUrl??'postgresql://unused@localhost/unused_test';
process.env.CONTROL_PLANE_DATABASE_URL=process.env.DATABASE_URL;
process.env.SAAS_TENANCY_MODE='database_per_tenant';
process.env.SAAS_TENANT_DATABASE_URL_TEMPLATE='postgresql://postgres:corepos_test_password@127.0.0.1:55433/{database}';
process.env.SAAS_DATABASE_ADMIN_URL='postgresql://postgres:corepos_test_password@127.0.0.1:55433/postgres';
process.env.SAAS_TENANT_DB_OWNER='postgres';process.env.JWT_SECRET='cash-sync-dpt-secret-at-least-32-characters';process.env.NODE_ENV='test';
const enabled=Boolean(controlUrl),control=new pg.Pool({connectionString:controlUrl});
const ids={customer:'20000000-0000-4000-8000-000000000001',vendor:'20000000-0000-4000-8000-000000000002',license:'20000000-0000-4000-8000-000000000003',certificate:'20000000-0000-4000-8000-000000000004',tenant:'20000000-0000-4000-8000-000000000005'};
type Device={installation:string;key:string;privateKey:crypto.KeyObject};
const hash=(key:string)=>crypto.createHash('sha256').update(key).digest('hex');
let app:ReturnType<typeof Fastify>,tenant:pg.Pool,device:Device;
function prove(d:Device,clientId:string){const nonce=crypto.randomUUID(),requested=new Date().toISOString();const payload=['desktop-sync-v1','push',ids.license,ids.certificate,d.installation,d.key,nonce,requested,clientId,'open','1','','cashier@dpt.test','MAIN','12','',requested,'','',''].join('\n');return{license_id:ids.license,certificate_id:ids.certificate,installation_id:d.installation,device_public_key:d.key,nonce,requested_at:requested,device_proof:crypto.sign(null,Buffer.from(payload),d.privateKey).toString('base64url'),requested}}
test.before(async()=>{if(!enabled)return;await control.query(`drop database if exists ${tenantDatabase} with (force)`);await control.query(`create database ${tenantDatabase}`);tenant=new pg.Pool({connectionString:tenantUrl});const {migrateTenantDatabase}=await import('../saas/tenant-provisioning.js');await migrateTenantDatabase(tenant);const keys=crypto.generateKeyPairSync('ed25519');device={installation:crypto.randomUUID(),key:JSON.stringify(keys.publicKey.export({format:'jwk'})),privateKey:keys.privateKey};await control.query('truncate license_customers, saas_tenants restart identity cascade');await control.query("insert into license_customers(id,name) values($1,'DPT customer')",[ids.customer]);await control.query("insert into vendor_businesses(id,customer_id,name,business_type,status) values($1,$2,'DPT business','cafe','active')",[ids.vendor,ids.customer]);await control.query("insert into licenses(id,customer_id,vendor_business_id,business_type,status,allowed_features,max_devices,expires_at) values($1,$2,$3,'cafe','active','[\"pos\"]',2,now()+interval '30 days')",[ids.license,ids.customer,ids.vendor]);await control.query("insert into saas_tenants(id,vendor_business_id,slug,database_name,status) values($1,$2,'cash-sync-dpt',$3,'active')",[ids.tenant,ids.vendor,tenantDatabase]);await tenant.query("insert into businesses(name,slug,business_type,currency,locale,timezone,vendor_business_id) values('DPT runtime','dpt-runtime','cafe','MAD','fr-MA','Africa/Casablanca',$1)",[ids.vendor]);await tenant.query("insert into branches(business_id,name,code,active) values(1,'Main','MAIN',true);insert into users(business_id,branch_id,name,email,password,role,is_active) values(1,1,'Cashier','cashier@dpt.test','$2b$04$9ndB7M.v5RKAEp2pKGMSTeE9WsUo8RXvv2A10vWArkjBHv.Lvta9W','cashier',true)");const deviceId=crypto.randomUUID();await control.query("insert into license_devices(id,license_id,installation_id,device_public_key,device_fingerprint,channel,status) values($1,$2,$3,$4,$5,'desktop','active')",[deviceId,ids.license,device.installation,device.key,hash(device.key)]);await control.query("insert into license_activations(license_id,device_id,certificate_id,kind,status,request_nonce) values($1,$2,$3,'offline','approved',$4)",[ids.license,deviceId,ids.certificate,crypto.randomUUID()]);const module=await import('./desktop-cash-register.js');app=Fastify();app.setErrorHandler((error:Error,_request:FastifyRequest,reply:FastifyReply)=>{const value=error as Error&{statusCode?:number;code?:string};reply.code(value.statusCode??500).send({message:value.message,code:value.code})});await module.registerDesktopCashRegisterSync(app,{pool:control,controlPool:control});await app.ready()});
test.after(async()=>{if(!enabled)return;await app.close();await tenant.end();await control.query(`drop database if exists ${tenantDatabase} with (force)`);await control.end()});
test('device-bound sync selects the database-per-tenant runtime',{skip:!enabled},async()=>{const clientId=crypto.randomUUID(),proof=prove(device,clientId),{requested,...signed}=proof,mutation={client_id:clientId,operation:'open',local_session_id:1,user_email:'cashier@dpt.test',branch_code:'MAIN',opening_cash:12,opening_note:null,opened_at:requested};const result=await app.inject({method:'POST',url:'/api/desktop-sync/cash-registers/push',payload:{device:signed,mutation}});assert.equal(result.statusCode,201,result.body);assert.equal((await tenant.query('select count(*)::int n from cash_register_sessions')).rows[0].n,1)});
