import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import test from 'node:test';
import pg from 'pg';
import Fastify from 'fastify';
import cookie from '@fastify/cookie';
import {offlineProofPayload,type OfflineRequest} from '@bimik/shared-types';
import {verifyCertificate} from './crypto.js';
import {issueActivationCode} from './activation-codes.js';

const url=process.env.TEST_DATABASE_URL;
if(url&&!decodeURIComponent(new URL(url).pathname).endsWith('_test'))throw new Error('Disposable _test database required');
if(process.env.REQUIRE_POSTGRES_INTEGRATION==='true'&&!url)throw new Error('TEST_DATABASE_URL required');
const keys=crypto.generateKeyPairSync('ed25519');
const publicKey=keys.publicKey.export({type:'spki',format:'pem'}).toString();
process.env.LICENSE_SIGNING_PRIVATE_KEY=keys.privateKey.export({type:'pkcs8',format:'pem'}).toString();
process.env.VENDOR_ADMIN_TOKEN=crypto.randomBytes(32).toString('hex');
process.env.DATABASE_URL=url??'postgresql://unused@localhost/unused_test';
process.env.JWT_SECRET='isolated-licensing-tests-secret-32-characters';
process.env.NODE_ENV='test';
const headers={authorization:`Bearer ${process.env.VENDOR_ADMIN_TOKEN}`};
const pool=new pg.Pool({connectionString:url});
const app=Fastify();
app.setErrorHandler((err:unknown,_request,reply)=>{const value=err as {statusCode?:number;code?:string;message?:string};return reply.code(value.statusCode??500).send({message:value.message,code:value.code})});
test.before(async()=>{if(!url)return;await app.register(cookie);const {registerLicenseRoutes}=await import('./routes.js');await registerLicenseRoutes(app,{pool,operationalPool:pool,authenticate:async(_r,p)=>{p.code(401).send()},resolveUser:async()=>null});await app.ready()});
test.after(async()=>{await app.close();await pool.end()});
async function license(type:'library'|'cafe',slots=2){const c=(await pool.query("insert into license_customers(name) values('Isolated licensing test') returning id")).rows[0];const b=(await pool.query("insert into vendor_businesses(customer_id,name,business_type,status) values($1,'Isolated business',$2,'active') returning id",[c.id,type])).rows[0];return (await pool.query("insert into licenses(customer_id,vendor_business_id,plan_id,status,business_type,allowed_features,max_devices,max_desktop_devices,expires_at,offline_validity_days) values($1,$2,(select id from license_plans where code='business'),'active',$3,'[\"pos\"]',$4,$4,now()+interval '30 days',30) returning *",[c.id,b.id,type,slots])).rows[0]}
function request(version:1|2=2){const d=crypto.generateKeyPairSync('ed25519');const facts={installation_id:crypto.randomUUID(),device_public_key:JSON.stringify(d.publicKey.export({format:'jwk'})),device_name:'CorePOS test device',app_version:'2.0.8',nonce:crypto.randomUUID(),requested_at:new Date().toISOString()};const req=version===1?{...facts,version:1 as const,business_type:'cafe' as const}:{...facts,version:2 as const,platform:'win32'};return {keys:d,body:{...req,device_proof:crypto.sign(null,Buffer.from(offlineProofPayload(req)),d.privateKey).toString('base64url')} satisfies OfflineRequest}}
test('Vendor v2 candidates include library; issue is signed, device bound, quota controlled and replay protected',{skip:!url},async()=>{const l=await license('library',1),req=request();const candidates=await app.inject({method:'POST',url:'/api/vendor/offline-activations/candidates',headers,payload:req.body});assert.equal(candidates.statusCode,200,candidates.body);assert.ok(candidates.json().data.some((v:{id:string})=>v.id===l.id));const issue=()=>app.inject({method:'POST',url:'/api/vendor/offline-activations/issue',headers,payload:{license_id:l.id,request:req.body}});const result=await issue();assert.equal(result.statusCode,201,result.body);const signed=result.json().data;assert.equal(signed.certificate.business_type,'library');assert.equal(signed.certificate.installation_id,req.body.installation_id);assert.deepEqual(signed.certificate.features,['pos']);assert.equal(verifyCertificate(signed.certificate,signed.signature,publicKey),true);assert.equal((await issue()).statusCode,409);const second=request();assert.equal((await app.inject({method:'POST',url:'/api/vendor/offline-activations/issue',headers,payload:{license_id:l.id,request:second.body}})).statusCode,409);const excluded=(await app.inject({method:'POST',url:'/api/vendor/offline-activations/candidates',headers,payload:second.body})).json().data;assert.equal(excluded.some((v:{id:string})=>v.id===l.id),false)});
test('Vendor v1 rejects cafe/library mismatch and still accepts cafe/cafe',{skip:!url},async()=>{const lib=await license('library'),cafe=await license('cafe'),req=request(1);const mismatch=await app.inject({method:'POST',url:'/api/vendor/offline-activations/issue',headers,payload:{license_id:lib.id,request:req.body}});assert.equal(mismatch.statusCode,422,mismatch.body);assert.equal(mismatch.json().code,'LICENSE_BUSINESS_TYPE_MISMATCH');assert.equal((await pool.query('select count(*)::int n from license_devices where license_id=$1',[lib.id])).rows[0].n,0);const match=await app.inject({method:'POST',url:'/api/vendor/offline-activations/issue',headers,payload:{license_id:cafe.id,request:req.body}});assert.equal(match.statusCode,201,match.body)});
for(const type of ['library','cafe'] as const)test(`Vendor one-time online code issues ${type} identity once`,{skip:!url},async()=>{const l=await license(type),client=await pool.connect();let code:string;try{code=(await issueActivationCode({client,licenseId:l.id,channel:'desktop',licenseExpiresAt:l.expires_at})).plaintext}finally{client.release()}const d=request(),{version:_v,platform:_p,device_proof:_proof,...facts}=d.body as Extract<OfflineRequest,{version:2}>;const raw={...facts,license_key:code};const proof=['device-activate-v1',code,raw.installation_id,raw.device_public_key,raw.device_name,raw.app_version,raw.nonce,raw.requested_at].join('\n');const body={...raw,device_proof:crypto.sign(null,Buffer.from(proof),d.keys.privateKey).toString('base64url')};const result=await app.inject({method:'POST',url:'/api/license/device-activate',payload:body});assert.equal(result.statusCode,201,result.body);assert.equal(result.json().data.certificate.business_type,type);assert.equal(verifyCertificate(result.json().data.certificate,result.json().data.signature,publicKey),true);assert.equal((await app.inject({method:'POST',url:'/api/license/device-activate',payload:body})).statusCode,409)});
