type Language = 'fr' | 'en' | 'ar'

type MerchantTranslations = Record<Language, Record<string, string>>

export const merchantI18n: MerchantTranslations = {
  fr: {
    'common.close':'Fermer','common.details':'Détails','common.create':'Créer','common.name':'Nom','common.phone':'Téléphone','common.email':'E-mail','common.reference':'Référence','common.quantity':'Quantité','common.reason':'Motif','common.actions':'Actions','common.profit':'Bénéfice','common.user':'Utilisateur','common.product':'Produit','common.unit':'Unité','common.minutes':'min','common.table':'Table','common.items':'article(s)','common.received':'Reçu','common.returned':'Retourné','common.previewReprint':'Aperçu / Réimprimer',
    'sidebar.navigation':'Navigation principale','sidebar.closeMenu':'Fermer le menu','protected.loading':'Chargement du compte…',
    'customers.title':'Clients','customers.subtitle':'Historique d’achat strictement rattaché à votre commerce.','customers.noContact':'Aucune coordonnée','customers.purchases':'achats','customers.lastPurchase':'Dernier achat {date}','customers.noPurchase':'Aucun achat','customers.empty':'Aucun client.',
    'suppliers.title':'Fournisseurs','suppliers.subtitle':'Contacts, achats reçus et retours.','suppliers.noContact':'Aucune coordonnée','suppliers.purchasesReceived':'{purchases} achats · {received} reçus','suppliers.receivedAmount':'Reçu {amount}','suppliers.returnsAmount':'Retours {amount}','suppliers.last':'Dernier {date}','suppliers.empty':'Aucun fournisseur.',
    'purchases.title':'Achats','purchases.subtitle':'Commandes fournisseurs, réceptions et retours.','purchases.supplier':'Fournisseur','purchases.purchasePrice':'Prix d’achat','purchases.receive':'Réceptionner','purchases.empty':'Aucun achat.','purchases.detailTitle':'Achat {reference}','purchases.supplierReturn':'Retour fournisseur','purchases.confirmReturn':'Confirmer le retour','purchases.status.ordered':'Commandé','purchases.status.received':'Reçu','purchases.status.cancelled':'Annulé','purchases.status.draft':'Brouillon',
    'sales.title':'Ventes','sales.subtitle':'Historique des ventes, détails et réimpression de ticket.','sales.loading':'Chargement des ventes…','sales.sale':'Vente','sales.payment':'Paiement','sales.empty':'Aucune vente.','sales.detailTitle':'Vente #{id}','sales.worker':'Employé','sales.return':'Retour','sales.selectionRequired':'Sélectionnez au moins un article et indiquez le motif.','sales.returnQuantity':'Quantité retour {product}','sales.returnTitle':'Retour / remboursement','sales.returnHelp':'Le stock suivi sera restauré. La vente originale restera inchangée.','sales.confirmReturn':'Confirmer le retour',
    'kitchen.title':'Cuisine','kitchen.subtitle':'Préparation des commandes sur place, à emporter et en livraison.','kitchen.loadError':'Impossible de charger les commandes cuisine.','kitchen.updateError':'La mise à jour de la commande a échoué.','kitchen.emptyTitle':'Aucune commande en cuisine.','kitchen.emptyHelp':'Les nouvelles préparations apparaîtront automatiquement.','kitchen.laneNew':'Nouvelles','kitchen.lanePreparing':'En préparation','kitchen.laneReady':'Prêtes','kitchen.acceptPrepare':'Accepter / Préparer','kitchen.markReady':'Marquer prête','kitchen.markServed':'Marquer servie','kitchen.note':'Note : {note}',
    'order.status.pending':'En attente','order.status.accepted':'Acceptée','order.status.preparing':'En préparation','order.status.ready':'Prête','order.status.served':'Servie','order.status.completed':'Terminée','order.status.cancelled':'Annulée','order.type.retail':'Vente comptoir','order.type.dine_in':'Sur place','order.type.takeaway':'À emporter','order.type.delivery':'Livraison','order.source.pos':'POS','order.source.employee_table':'Table','order.source.qr_table':'Table QR','order.source.web':'Web','order.source.mobile':'Mobile',
    'ordersMgmt.title':'Commandes','ordersMgmt.subtitle':'Suivi des ventes, commandes de table, QR et livraisons.','ordersMgmt.filterAll':'Toutes','ordersMgmt.filterPaid':'Payées','ordersMgmt.searchAria':'Rechercher une commande','ordersMgmt.searchPlaceholder':'N° commande, table, source','ordersMgmt.emptyTitle':'Aucune commande pour le moment.','ordersMgmt.emptyHelp':'Les commandes POS, table et QR apparaîtront ici.','ordersMgmt.paid':'Payée','ordersMgmt.toCollect':'À encaisser','ordersMgmt.noTable':'Sans table','ordersMgmt.note':'Note : {note}','ordersMgmt.orderNote':'Note commande : {note}','ordersMgmt.subtotal':'Sous-total','ordersMgmt.discount':'Remise','ordersMgmt.taxes':'Taxes','ordersMgmt.remaining':'Reste à payer','ordersMgmt.addProducts':'Ajouter des produits','ordersMgmt.viewTable':'Voir la table','ordersMgmt.accept':'Accepter','ordersMgmt.prepare':'Préparer','ordersMgmt.markReady':'Marquer prête','ordersMgmt.serve':'Servir','ordersMgmt.complete':'Terminer','ordersMgmt.paymentMode':'Mode de paiement','ordersMgmt.collecting':'Encaissement…','ordersMgmt.collect':'Encaisser',
    'tables.title':'Salles et tables','tables.subtitle':'Plan de salle, commandes et demandes de service.','tables.loadError':'Impossible de charger la salle.','tables.printAllQr':'Imprimer tous les QR','tables.createRoomTable':'Créer une salle / une table','tables.newRoom':'Nouvelle salle','tables.addRoom':'Ajouter la salle','tables.newTable':'Nouvelle table','tables.room':'Salle','tables.number':'Numéro','tables.addTable':'Ajouter la table','tables.empty':'Aucune table configurée.','tables.places':'{count} places','tables.callWaiter':'Appel serveur','tables.billRequested':'Addition demandée','tables.handle':'Traiter','tables.handleBill':'Traiter l’addition','tables.addProducts':'Ajouter des produits','tables.openOrder':'Ouvrir une commande','tables.pay':'Encaisser','tables.qrTitle':'QR de la table','tables.bill':'Addition','tables.subtotal':'Sous-total','tables.discounts':'Remises','tables.taxes':'Taxes','tables.printQr':'Imprimer QR','tables.download':'Télécharger','tables.copy':'Copier','tables.open':'Ouvrir','tables.regenerate':'Régénérer','tables.qrAlt':'QR de la table','tables.status.available':'Libre','tables.status.occupied':'Occupée','tables.status.ordering':'Commande en cours','tables.status.waiting':'En attente','tables.status.preparing':'En préparation','tables.status.ready':'Prête','tables.status.served':'Servie','tables.status.bill_requested':'Addition demandée','tables.status.reserved':'Réservée',
    'publicMenu.unavailable':'Menu indisponible.','publicMenu.waiterCalled':'Un serveur a été appelé.','publicMenu.billSent':'Votre demande d’addition a été envoyée.','publicMenu.orderSent':'Commande {order} envoyée à {table}.','publicMenu.loading':'Chargement du menu…','publicMenu.callWaiter':'Appeler un serveur','publicMenu.requestBill':'Demander l’addition','publicMenu.categories':'Catégories','publicMenu.available':'Disponible','publicMenu.unavailableProduct':'Indisponible','publicMenu.noProducts':'Aucun produit disponible dans cette catégorie.','publicMenu.cart':'Panier · {count}','publicMenu.chooseVariant':'Choisissez une variante','publicMenu.included':'Inclus','publicMenu.extras':'Suppléments','publicMenu.kitchenNote':'Note pour la cuisine','publicMenu.kitchenPlaceholder':'Cuisson, allergie, préférence…','publicMenu.add':'Ajouter · {amount}','publicMenu.yourOrder':'Votre commande','publicMenu.sendOrder':'Envoyer la commande','publicMenu.sending':'Envoi…',
    'restaurantReceipt.ticket':'Ticket #{id} · {order}','restaurantReceipt.subtotal':'Sous-total','restaurantReceipt.discount':'Remise','restaurantReceipt.taxes':'Taxes','restaurantReceipt.payment':'Paiement','restaurantReceipt.total':'Total','restaurantReceipt.cashier':'Caissier : {name}','restaurantReceipt.print':'Imprimer / Réimprimer',
    'categories.loading':'Chargement des catégories…','categories.edit':'Modifier catégorie','categories.add':'Ajouter catégorie','categories.name':'Nom','categories.image':'Image','categories.preview':'Aperçu','categories.categoryAlt':'Catégorie','categories.imageTooLarge':'L’image ne doit pas dépasser 5 Mo.','categories.updated':'Catégorie modifiée.','categories.created':'Catégorie ajoutée.','categories.deleted':'Catégorie supprimée.','categories.confirmDelete':'Supprimer {name} ?',
    'menu.pages':'{count} page(s)','menu.ignoredSummary':'Éléments ignorés/non reconnus ({count})','menu.page':'Page {page} — {text}','menu.duplicate':'Doublon {kind}','menu.review':'À vérifier','menu.result':'Catégories créées : {categoriesCreated}, réutilisées : {categoriesReused}, ignorées : {categoriesIgnored}. Produits créés : {productsCreated}, modifiés : {productsUpdated}, ignorés : {productsIgnored}, échecs : {productsFailed}.',
    'stock.newInventory':'Nouvel inventaire','stock.inventoryPhysical':'Inventaire physique','stock.inventorySuccess':'Inventaire confirmé et mouvements créés.','stock.inventoryTitle':'Inventaire #{id}','stock.inventoryHelp':'Saisissez le stock compté. La confirmation créera les ajustements.','stock.expected':'Attendu','stock.counted':'Compté','stock.difference':'Écart','stock.confirmAdjustments':'Confirmer les ajustements',
    'settings.userUpdated':'Utilisateur modifié.','settings.userCreated':'Utilisateur ajouté.','settings.confirmDeleteUser':'Supprimer {name} ?','settings.loadingUsers':'Chargement des utilisateurs…','settings.editUser':'Modifier utilisateur','settings.addUser':'Ajouter utilisateur','settings.password':'Mot de passe','settings.passwordOptional':'Laisser vide pour ne pas changer','settings.saving':'Enregistrement…','settings.saved':'Paramètres enregistrés.','settings.loadingSettings':'Chargement des paramètres…','settings.sections':'Sections des paramètres','settings.saveSettings':'Enregistrer les paramètres','settings.autoPrint':'Imprimer automatiquement après commande','settings.openReceipt':'Ouvrir ticket après commande'
  },
  en: {
    'common.close':'Close','common.details':'Details','common.create':'Create','common.name':'Name','common.phone':'Phone','common.email':'Email','common.reference':'Reference','common.quantity':'Quantity','common.reason':'Reason','common.actions':'Actions','common.profit':'Profit','common.user':'User','common.product':'Product','common.unit':'Unit','common.minutes':'min','common.table':'Table','common.items':'item(s)','common.received':'Received','common.returned':'Returned','common.previewReprint':'Preview / Reprint',
    'sidebar.navigation':'Main navigation','sidebar.closeMenu':'Close menu','protected.loading':'Loading account…',
    'customers.title':'Customers','customers.subtitle':'Purchase history strictly linked to your business.','customers.noContact':'No contact details','customers.purchases':'purchases','customers.lastPurchase':'Last purchase {date}','customers.noPurchase':'No purchases','customers.empty':'No customers.',
    'suppliers.title':'Suppliers','suppliers.subtitle':'Contacts, received purchases and returns.','suppliers.noContact':'No contact details','suppliers.purchasesReceived':'{purchases} purchases · {received} received','suppliers.receivedAmount':'Received {amount}','suppliers.returnsAmount':'Returns {amount}','suppliers.last':'Last {date}','suppliers.empty':'No suppliers.',
    'purchases.title':'Purchases','purchases.subtitle':'Supplier orders, receipts and returns.','purchases.supplier':'Supplier','purchases.purchasePrice':'Purchase price','purchases.receive':'Receive','purchases.empty':'No purchases.','purchases.detailTitle':'Purchase {reference}','purchases.supplierReturn':'Supplier return','purchases.confirmReturn':'Confirm return','purchases.status.ordered':'Ordered','purchases.status.received':'Received','purchases.status.cancelled':'Cancelled','purchases.status.draft':'Draft',
    'sales.title':'Sales','sales.subtitle':'Sales history, details and receipt reprinting.','sales.loading':'Loading sales…','sales.sale':'Sale','sales.payment':'Payment','sales.empty':'No sales.','sales.detailTitle':'Sale #{id}','sales.worker':'Employee','sales.return':'Return','sales.selectionRequired':'Select at least one item and enter a reason.','sales.returnQuantity':'Return quantity {product}','sales.returnTitle':'Return / refund','sales.returnHelp':'Tracked stock will be restored. The original sale will remain unchanged.','sales.confirmReturn':'Confirm return',
    'kitchen.title':'Kitchen','kitchen.subtitle':'Prepare dine-in, takeaway and delivery orders.','kitchen.loadError':'Unable to load kitchen orders.','kitchen.updateError':'The order update failed.','kitchen.emptyTitle':'No orders in the kitchen.','kitchen.emptyHelp':'New preparations will appear automatically.','kitchen.laneNew':'New','kitchen.lanePreparing':'Preparing','kitchen.laneReady':'Ready','kitchen.acceptPrepare':'Accept / Prepare','kitchen.markReady':'Mark ready','kitchen.markServed':'Mark served','kitchen.note':'Note: {note}',
    'order.status.pending':'Pending','order.status.accepted':'Accepted','order.status.preparing':'Preparing','order.status.ready':'Ready','order.status.served':'Served','order.status.completed':'Completed','order.status.cancelled':'Cancelled','order.type.retail':'Retail','order.type.dine_in':'Dine in','order.type.takeaway':'Takeaway','order.type.delivery':'Delivery','order.source.pos':'POS','order.source.employee_table':'Table','order.source.qr_table':'QR Table','order.source.web':'Web','order.source.mobile':'Mobile',
    'ordersMgmt.title':'Orders','ordersMgmt.subtitle':'Track sales, table orders, QR and deliveries.','ordersMgmt.filterAll':'All','ordersMgmt.filterPaid':'Paid','ordersMgmt.searchAria':'Search orders','ordersMgmt.searchPlaceholder':'Order no., table, source','ordersMgmt.emptyTitle':'No orders yet.','ordersMgmt.emptyHelp':'POS, table and QR orders will appear here.','ordersMgmt.paid':'Paid','ordersMgmt.toCollect':'To collect','ordersMgmt.noTable':'No table','ordersMgmt.note':'Note: {note}','ordersMgmt.orderNote':'Order note: {note}','ordersMgmt.subtotal':'Subtotal','ordersMgmt.discount':'Discount','ordersMgmt.taxes':'Taxes','ordersMgmt.remaining':'Remaining','ordersMgmt.addProducts':'Add products','ordersMgmt.viewTable':'View table','ordersMgmt.accept':'Accept','ordersMgmt.prepare':'Prepare','ordersMgmt.markReady':'Mark ready','ordersMgmt.serve':'Serve','ordersMgmt.complete':'Complete','ordersMgmt.paymentMode':'Payment method','ordersMgmt.collecting':'Collecting…','ordersMgmt.collect':'Collect payment',
    'tables.title':'Rooms and tables','tables.subtitle':'Floor plan, orders and service requests.','tables.loadError':'Unable to load the room.','tables.printAllQr':'Print all QR codes','tables.createRoomTable':'Create room / table','tables.newRoom':'New room','tables.addRoom':'Add room','tables.newTable':'New table','tables.room':'Room','tables.number':'Number','tables.addTable':'Add table','tables.empty':'No tables configured.','tables.places':'{count} seats','tables.callWaiter':'Waiter call','tables.billRequested':'Bill requested','tables.handle':'Handle','tables.handleBill':'Handle bill','tables.addProducts':'Add products','tables.openOrder':'Open order','tables.pay':'Collect payment','tables.qrTitle':'Table QR','tables.bill':'Bill','tables.subtotal':'Subtotal','tables.discounts':'Discounts','tables.taxes':'Taxes','tables.printQr':'Print QR','tables.download':'Download','tables.copy':'Copy','tables.open':'Open','tables.regenerate':'Regenerate','tables.qrAlt':'Table QR','tables.status.available':'Available','tables.status.occupied':'Occupied','tables.status.ordering':'Ordering','tables.status.waiting':'Waiting','tables.status.preparing':'Preparing','tables.status.ready':'Ready','tables.status.served':'Served','tables.status.bill_requested':'Bill requested','tables.status.reserved':'Reserved',
    'publicMenu.unavailable':'Menu unavailable.','publicMenu.waiterCalled':'A waiter has been called.','publicMenu.billSent':'Your bill request has been sent.','publicMenu.orderSent':'Order {order} sent to {table}.','publicMenu.loading':'Loading menu…','publicMenu.callWaiter':'Call waiter','publicMenu.requestBill':'Request bill','publicMenu.categories':'Categories','publicMenu.available':'Available','publicMenu.unavailableProduct':'Unavailable','publicMenu.noProducts':'No products available in this category.','publicMenu.cart':'Cart · {count}','publicMenu.chooseVariant':'Choose a variant','publicMenu.included':'Included','publicMenu.extras':'Extras','publicMenu.kitchenNote':'Kitchen note','publicMenu.kitchenPlaceholder':'Cooking, allergy, preference…','publicMenu.add':'Add · {amount}','publicMenu.yourOrder':'Your order','publicMenu.sendOrder':'Send order','publicMenu.sending':'Sending…',
    'restaurantReceipt.ticket':'Receipt #{id} · {order}','restaurantReceipt.subtotal':'Subtotal','restaurantReceipt.discount':'Discount','restaurantReceipt.taxes':'Taxes','restaurantReceipt.payment':'Payment','restaurantReceipt.total':'Total','restaurantReceipt.cashier':'Cashier: {name}','restaurantReceipt.print':'Print / Reprint',
    'categories.loading':'Loading categories…','categories.edit':'Edit category','categories.add':'Add category','categories.name':'Name','categories.image':'Image','categories.preview':'Preview','categories.categoryAlt':'Category','categories.imageTooLarge':'The image must not exceed 5 MB.','categories.updated':'Category updated.','categories.created':'Category added.','categories.deleted':'Category deleted.','categories.confirmDelete':'Delete {name}?',
    'menu.pages':'{count} page(s)','menu.ignoredSummary':'Ignored/unrecognized items ({count})','menu.page':'Page {page} — {text}','menu.duplicate':'Duplicate {kind}','menu.review':'Review','menu.result':'Categories created: {categoriesCreated}, reused: {categoriesReused}, ignored: {categoriesIgnored}. Products created: {productsCreated}, updated: {productsUpdated}, ignored: {productsIgnored}, failures: {productsFailed}.',
    'stock.newInventory':'New inventory count','stock.inventoryPhysical':'Physical inventory','stock.inventorySuccess':'Inventory confirmed and movements created.','stock.inventoryTitle':'Inventory #{id}','stock.inventoryHelp':'Enter the counted stock. Confirmation will create the adjustments.','stock.expected':'Expected','stock.counted':'Counted','stock.difference':'Difference','stock.confirmAdjustments':'Confirm adjustments',
    'settings.userUpdated':'User updated.','settings.userCreated':'User added.','settings.confirmDeleteUser':'Delete {name}?','settings.loadingUsers':'Loading users…','settings.editUser':'Edit user','settings.addUser':'Add user','settings.password':'Password','settings.passwordOptional':'Leave blank to keep the current password','settings.saving':'Saving…','settings.saved':'Settings saved.','settings.loadingSettings':'Loading settings…','settings.sections':'Settings sections','settings.saveSettings':'Save settings','settings.autoPrint':'Print automatically after order','settings.openReceipt':'Open receipt after order'
  },
  ar: {
    'common.close':'إغلاق','common.details':'التفاصيل','common.create':'إنشاء','common.name':'الاسم','common.phone':'الهاتف','common.email':'البريد الإلكتروني','common.reference':'المرجع','common.quantity':'الكمية','common.reason':'السبب','common.actions':'الإجراءات','common.profit':'الربح','common.user':'المستخدم','common.product':'المنتج','common.unit':'الوحدة','common.minutes':'د','common.table':'طاولة','common.items':'عنصر','common.received':'مستلم','common.returned':'مرتجع','common.previewReprint':'معاينة / إعادة الطباعة',
    'sidebar.navigation':'التنقل الرئيسي','sidebar.closeMenu':'إغلاق القائمة','protected.loading':'جارٍ تحميل الحساب…',
    'customers.title':'العملاء','customers.subtitle':'سجل المشتريات مرتبط حصريًا بنشاطك.','customers.noContact':'لا توجد معلومات اتصال','customers.purchases':'مشتريات','customers.lastPurchase':'آخر شراء {date}','customers.noPurchase':'لا توجد مشتريات','customers.empty':'لا يوجد عملاء.',
    'suppliers.title':'الموردون','suppliers.subtitle':'جهات الاتصال والمشتريات المستلمة والمرتجعات.','suppliers.noContact':'لا توجد معلومات اتصال','suppliers.purchasesReceived':'{purchases} مشتريات · {received} مستلمة','suppliers.receivedAmount':'المستلم {amount}','suppliers.returnsAmount':'المرتجعات {amount}','suppliers.last':'آخر عملية {date}','suppliers.empty':'لا يوجد موردون.',
    'purchases.title':'المشتريات','purchases.subtitle':'طلبات الموردين والاستلام والمرتجعات.','purchases.supplier':'المورد','purchases.purchasePrice':'سعر الشراء','purchases.receive':'استلام','purchases.empty':'لا توجد مشتريات.','purchases.detailTitle':'شراء {reference}','purchases.supplierReturn':'إرجاع للمورد','purchases.confirmReturn':'تأكيد الإرجاع','purchases.status.ordered':'مطلوب','purchases.status.received':'مستلم','purchases.status.cancelled':'ملغى','purchases.status.draft':'مسودة',
    'sales.title':'المبيعات','sales.subtitle':'سجل المبيعات والتفاصيل وإعادة طباعة الفواتير.','sales.loading':'جارٍ تحميل المبيعات…','sales.sale':'بيع','sales.payment':'الدفع','sales.empty':'لا توجد مبيعات.','sales.detailTitle':'بيع #{id}','sales.worker':'الموظف','sales.return':'إرجاع','sales.selectionRequired':'اختر عنصرًا واحدًا على الأقل وأدخل سبب الإرجاع.','sales.returnQuantity':'كمية الإرجاع {product}','sales.returnTitle':'إرجاع / استرداد','sales.returnHelp':'سيتم إرجاع المخزون المتتبع، وستبقى عملية البيع الأصلية دون تغيير.','sales.confirmReturn':'تأكيد الإرجاع',
    'kitchen.title':'المطبخ','kitchen.subtitle':'تحضير الطلبات داخل المحل وللأخذ والتوصيل.','kitchen.loadError':'تعذر تحميل طلبات المطبخ.','kitchen.updateError':'فشل تحديث الطلب.','kitchen.emptyTitle':'لا توجد طلبات في المطبخ.','kitchen.emptyHelp':'ستظهر التحضيرات الجديدة تلقائيًا.','kitchen.laneNew':'جديدة','kitchen.lanePreparing':'قيد التحضير','kitchen.laneReady':'جاهزة','kitchen.acceptPrepare':'قبول / تحضير','kitchen.markReady':'تحديد كجاهزة','kitchen.markServed':'تحديد كمقدّمة','kitchen.note':'ملاحظة: {note}',
    'order.status.pending':'قيد الانتظار','order.status.accepted':'مقبول','order.status.preparing':'قيد التحضير','order.status.ready':'جاهز','order.status.served':'مقدّم','order.status.completed':'مكتمل','order.status.cancelled':'ملغى','order.type.retail':'بيع مباشر','order.type.dine_in':'داخل المحل','order.type.takeaway':'للأخذ','order.type.delivery':'توصيل','order.source.pos':'POS','order.source.employee_table':'طاولة','order.source.qr_table':'طاولة QR','order.source.web':'ويب','order.source.mobile':'هاتف',
    'ordersMgmt.title':'الطلبات','ordersMgmt.subtitle':'متابعة المبيعات وطلبات الطاولات وQR والتوصيل.','ordersMgmt.filterAll':'الكل','ordersMgmt.filterPaid':'مدفوعة','ordersMgmt.searchAria':'البحث عن طلب','ordersMgmt.searchPlaceholder':'رقم الطلب، الطاولة، المصدر','ordersMgmt.emptyTitle':'لا توجد طلبات حاليًا.','ordersMgmt.emptyHelp':'ستظهر هنا طلبات POS والطاولات وQR.','ordersMgmt.paid':'مدفوع','ordersMgmt.toCollect':'بانتظار التحصيل','ordersMgmt.noTable':'بدون طاولة','ordersMgmt.note':'ملاحظة: {note}','ordersMgmt.orderNote':'ملاحظة الطلب: {note}','ordersMgmt.subtotal':'المجموع الفرعي','ordersMgmt.discount':'الخصم','ordersMgmt.taxes':'الضرائب','ordersMgmt.remaining':'المتبقي للدفع','ordersMgmt.addProducts':'إضافة منتجات','ordersMgmt.viewTable':'عرض الطاولة','ordersMgmt.accept':'قبول','ordersMgmt.prepare':'تحضير','ordersMgmt.markReady':'تحديد كجاهز','ordersMgmt.serve':'تقديم','ordersMgmt.complete':'إنهاء','ordersMgmt.paymentMode':'طريقة الدفع','ordersMgmt.collecting':'جارٍ التحصيل…','ordersMgmt.collect':'تحصيل',
    'tables.title':'القاعات والطاولات','tables.subtitle':'مخطط القاعة والطلبات وطلبات الخدمة.','tables.loadError':'تعذر تحميل القاعة.','tables.printAllQr':'طباعة جميع رموز QR','tables.createRoomTable':'إنشاء قاعة / طاولة','tables.newRoom':'قاعة جديدة','tables.addRoom':'إضافة القاعة','tables.newTable':'طاولة جديدة','tables.room':'القاعة','tables.number':'الرقم','tables.addTable':'إضافة الطاولة','tables.empty':'لا توجد طاولات مهيأة.','tables.places':'{count} مقاعد','tables.callWaiter':'نداء النادل','tables.billRequested':'طلب الحساب','tables.handle':'معالجة','tables.handleBill':'معالجة الحساب','tables.addProducts':'إضافة منتجات','tables.openOrder':'فتح طلب','tables.pay':'تحصيل','tables.qrTitle':'QR الطاولة','tables.bill':'الحساب','tables.subtotal':'المجموع الفرعي','tables.discounts':'الخصومات','tables.taxes':'الضرائب','tables.printQr':'طباعة QR','tables.download':'تنزيل','tables.copy':'نسخ','tables.open':'فتح','tables.regenerate':'إعادة التوليد','tables.qrAlt':'QR الطاولة','tables.status.available':'متاحة','tables.status.occupied':'مشغولة','tables.status.ordering':'طلب جارٍ','tables.status.waiting':'قيد الانتظار','tables.status.preparing':'قيد التحضير','tables.status.ready':'جاهزة','tables.status.served':'مقدّمة','tables.status.bill_requested':'الحساب مطلوب','tables.status.reserved':'محجوزة',
    'publicMenu.unavailable':'القائمة غير متاحة.','publicMenu.waiterCalled':'تم استدعاء النادل.','publicMenu.billSent':'تم إرسال طلب الحساب.','publicMenu.orderSent':'تم إرسال الطلب {order} إلى {table}.','publicMenu.loading':'جارٍ تحميل القائمة…','publicMenu.callWaiter':'استدعاء النادل','publicMenu.requestBill':'طلب الحساب','publicMenu.categories':'الفئات','publicMenu.available':'متاح','publicMenu.unavailableProduct':'غير متاح','publicMenu.noProducts':'لا توجد منتجات متاحة في هذه الفئة.','publicMenu.cart':'السلة · {count}','publicMenu.chooseVariant':'اختر خيارًا','publicMenu.included':'مشمول','publicMenu.extras':'الإضافات','publicMenu.kitchenNote':'ملاحظة للمطبخ','publicMenu.kitchenPlaceholder':'الطهي، الحساسية، التفضيل…','publicMenu.add':'إضافة · {amount}','publicMenu.yourOrder':'طلبك','publicMenu.sendOrder':'إرسال الطلب','publicMenu.sending':'جارٍ الإرسال…',
    'restaurantReceipt.ticket':'فاتورة #{id} · {order}','restaurantReceipt.subtotal':'المجموع الفرعي','restaurantReceipt.discount':'الخصم','restaurantReceipt.taxes':'الضرائب','restaurantReceipt.payment':'الدفع','restaurantReceipt.total':'الإجمالي','restaurantReceipt.cashier':'أمين الصندوق: {name}','restaurantReceipt.print':'طباعة / إعادة الطباعة',
    'categories.loading':'جارٍ تحميل الفئات…','categories.edit':'تعديل الفئة','categories.add':'إضافة فئة','categories.name':'الاسم','categories.image':'الصورة','categories.preview':'معاينة','categories.categoryAlt':'فئة','categories.imageTooLarge':'يجب ألا يتجاوز حجم الصورة 5 ميغابايت.','categories.updated':'تم تعديل الفئة.','categories.created':'تمت إضافة الفئة.','categories.deleted':'تم حذف الفئة.','categories.confirmDelete':'حذف {name}؟',
    'menu.pages':'{count} صفحة','menu.ignoredSummary':'عناصر متجاهلة/غير معروفة ({count})','menu.page':'الصفحة {page} — {text}','menu.duplicate':'مكرر {kind}','menu.review':'للمراجعة','menu.result':'الفئات المنشأة: {categoriesCreated}، المعاد استخدامها: {categoriesReused}، المتجاهلة: {categoriesIgnored}. المنتجات المنشأة: {productsCreated}، المعدلة: {productsUpdated}، المتجاهلة: {productsIgnored}، الإخفاقات: {productsFailed}.',
    'stock.newInventory':'جرد جديد','stock.inventoryPhysical':'جرد فعلي','stock.inventorySuccess':'تم تأكيد الجرد وإنشاء حركات المخزون.','stock.inventoryTitle':'الجرد #{id}','stock.inventoryHelp':'أدخل المخزون المعدود. سيؤدي التأكيد إلى إنشاء التعديلات.','stock.expected':'المتوقع','stock.counted':'المعدود','stock.difference':'الفرق','stock.confirmAdjustments':'تأكيد التعديلات',
    'settings.userUpdated':'تم تعديل المستخدم.','settings.userCreated':'تمت إضافة المستخدم.','settings.confirmDeleteUser':'حذف {name}؟','settings.loadingUsers':'جارٍ تحميل المستخدمين…','settings.editUser':'تعديل المستخدم','settings.addUser':'إضافة مستخدم','settings.password':'كلمة المرور','settings.passwordOptional':'اتركه فارغًا للاحتفاظ بكلمة المرور الحالية','settings.saving':'جارٍ الحفظ…','settings.saved':'تم حفظ الإعدادات.','settings.loadingSettings':'جارٍ تحميل الإعدادات…','settings.sections':'أقسام الإعدادات','settings.saveSettings':'حفظ الإعدادات','settings.autoPrint':'الطباعة تلقائيًا بعد الطلب','settings.openReceipt':'فتح الفاتورة بعد الطلب'
  }
}
