import crypto from 'node:crypto';
import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import type pg from 'pg';
import argon2 from 'argon2';
import { z } from 'zod';
import { businessFeaturesSchema,businessSetupSchema,businessUpdateSchema,orderSchema,purchaseSchema,roomSchema,supplierSchema,tableSchema } from '@bimik/validation';
import type { FeatureKey,Permission,Role } from '@bimik/shared-types';
import { config } from '../config.js';
import { currentTenant } from '../saas/tenant-context.js';
import { hasFeatureEntitlement, resolveRuntimeBusinessIdentity } from '../license/control-plane.js';

type UserContext={id:number;businessId:number;branchId:number|null;role:Role};
type Dependencies={pool:pg.Pool;controlPool:pg.Pool;authenticate:(request:FastifyRequest,reply:FastifyReply)=>Promise<unknown>;resolveUser:(request:FastifyRequest)=>Promise<UserContext|null>};
const permissions:Record<Role,readonly Permission[]>={
  patron:['business.manage','users.manage','products.read','products.write','pos.use','cash.manage','orders.read','orders.write','tables.manage','kitchen.use','inventory.read','inventory.write','purchases.manage','suppliers.manage','customers.manage','reports.read'],
  owner:['business.manage','users.manage','products.read','products.write','pos.use','cash.manage','orders.read','orders.write','tables.manage','kitchen.use','inventory.read','inventory.write','purchases.manage','suppliers.manage','customers.manage','reports.read'],
  admin:['business.manage','users.manage','products.read','products.write','pos.use','cash.manage','orders.read','orders.write','tables.manage','kitchen.use','inventory.read','inventory.write','purchases.manage','suppliers.manage','customers.manage','reports.read'],
  manager:['products.read','products.write','pos.use','cash.manage','orders.read','orders.write','tables.manage','inventory.read','inventory.write','purchases.manage','suppliers.manage','customers.manage','reports.read'],
  worker:['products.read','pos.use','cash.manage','orders.read','orders.write'], cashier:['products.read','pos.use','cash.manage','orders.read','orders.write','customers.manage'], seller:['products.read','pos.use','orders.read','orders.write','customers.manage'],
  waiter:['products.read','orders.read','orders.write','tables.manage'], kitchen:['orders.read','kitchen.use'], stock_manager:['products.read','products.write','inventory.read','inventory.write','purchases.manage','suppliers.manage'],
};
const hash=(value:string)=>crypto.createHash('sha256').update(value).digest('hex');
const num=(value:unknown)=>Number(value??0);
const money=(value:number)=>Math.round((value+Number.EPSILON)*100)/100;
const id=z.coerce.number().int().positive();

export async function registerCoreV2Routes(app:FastifyInstance,{pool,controlPool,authenticate,resolveUser}:Dependencies){
  app.get('/api/setup/status',async()=>{
    if(config.SAAS_TENANCY_MODE==='database_per_tenant'&&!currentTenant()){
      return {data:{configured:false,requires_provisioning:false,requires_tenant_selection:true,business:null}};
    }
    const result=await pool.query('select b.id,b.name,b.slug,b.logo,b.business_type from businesses b order by b.id limit 1');
    const configured=Boolean(result.rows[0]);
    const development=process.env.LICENSE_MODE==='development'&&process.env.NODE_ENV!=='production';
    return {data:{configured,requires_provisioning:config.SAAS_TENANCY_MODE==='shared'&&!configured&&!development,requires_tenant_selection:false,business:result.rows[0]??null}};
  });
  app.post('/api/setup',{config:{rateLimit:{max:5,timeWindow:'1 minute'}}},async(request,reply)=>{const development=process.env.LICENSE_MODE==='development'&&process.env.NODE_ENV!=='production';if(!development)return reply.code(409).send({message:'Vendor provisioning is required.',code:'PROVISIONING_REQUIRED'});const input=businessSetupSchema.parse(request.body),client=await pool.connect();try{await client.query('begin');await client.query('lock table businesses in exclusive mode');if((await client.query('select 1 from businesses limit 1')).rowCount){await client.query('rollback');return reply.code(409).send({message:'Business setup is already complete.'})}const slugBase=input.business.name.toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'business';const business=(await client.query('insert into businesses(name,slug,business_type,logo,currency,locale,timezone) values($1,$2,$3,$4,$5,$6,$7) returning *',[input.business.name,slugBase,input.business.business_type,input.business.logo??null,input.business.currency.toUpperCase(),input.business.locale,input.business.timezone])).rows[0];const branch=(await client.query("insert into branches(business_id,name,code,address,phone) values($1,'Principal','MAIN',$2,$3) returning *",[business.id,input.business.address??null,input.business.phone??null])).rows[0];for(const feature of new Set(input.enabled_features))await client.query('insert into business_features(business_id,feature) values($1,$2)',[business.id,feature]);const password=await argon2.hash(input.admin.password);const owner=(await client.query("insert into users(business_id,branch_id,name,email,password,role,is_active) values($1,$2,$3,$4,$5,'owner',true) returning id,name,email,role,is_active",[business.id,branch.id,input.admin.name,input.admin.email.toLowerCase(),password])).rows[0];await client.query('commit');return reply.code(201).send({data:{business,branch,owner}})}catch(error){await client.query('rollback');throw error}finally{client.release()}});
  async function context(request:FastifyRequest,reply:FastifyReply,permission?:Permission,feature?:FeatureKey){
    await authenticate(request,reply); if(reply.sent)return null;
    const user=await resolveUser(request); if(!user)return reply.code(401).send({message:'Unauthenticated.'}) as never;
    if(permission&&!permissions[user.role]?.includes(permission))return reply.code(403).send({message:'Permission denied.'}) as never;
    if(feature){
      const enabled=await pool.query('select 1 from business_features where business_id=$1 and feature=$2',[user.businessId,feature]);
      if(!enabled.rowCount)return reply.code(403).send({message:`Feature '${feature}' is not enabled.`}) as never;
      const development=process.env.LICENSE_MODE==='development'&&process.env.NODE_ENV!=='production';
      if(!development){
        const identity=await resolveRuntimeBusinessIdentity(pool,user.businessId);
        const entitled=identity?await hasFeatureEntitlement(controlPool,identity.vendorBusinessId,feature):false;
        if(!entitled)return reply.code(403).send({message:'Ce module n’est pas inclus dans votre licence.',code:'LICENSE_ENTITLEMENT_REQUIRED'}) as never;
      }
    }
    return user;
  }
  const guarded=(permission?:Permission,feature?:FeatureKey)=>async(request:FastifyRequest,reply:FastifyReply)=>{await context(request,reply,permission,feature)};
  app.addHook('preHandler',async(request,reply)=>{
    if(request.method!=='PUT'||request.url.split('?')[0]!=='/api/business/current/features'||process.env.LICENSE_MODE==='development'&&process.env.NODE_ENV!=='production')return;
    await authenticate(request,reply);if(reply.sent)return;
    const user=await resolveUser(request);if(!user)return reply.code(401).send({message:'Unauthenticated.'});
    const requested=businessFeaturesSchema.parse(request.body).enabled_features;
    const identity=await resolveRuntimeBusinessIdentity(pool,user.businessId);
    const denied:string[]=[];
    for(const feature of requested){
      if(!identity||!(await hasFeatureEntitlement(controlPool,identity.vendorBusinessId,feature)))denied.push(feature);
    }
    if(denied.length)return reply.code(403).send({message:'Ce module n’est pas inclus dans votre licence.',code:'LICENSE_ENTITLEMENT_REQUIRED',features:denied});
  });
  async function businessDto(businessId:number,branchId:number|null){const business=(await pool.query('select * from businesses where id=$1',[businessId])).rows[0];const features=(await pool.query('select feature from business_features where business_id=$1 order by feature',[businessId])).rows.map(r=>r.feature);const branch=branchId?(await pool.query('select id,name,code from branches where id=$1 and business_id=$2',[branchId,businessId])).rows[0]??null:null;return {id:business.id,name:business.name,slug:business.slug,business_type:business.business_type,logo:business.logo,currency:business.currency,locale:business.locale,timezone:business.timezone,tax_settings:business.tax_settings,receipt_settings:business.receipt_settings,enabled_features:features,branch,created_at:business.created_at,updated_at:business.updated_at};}

  app.get('/api/business/current',{preHandler:guarded()},async request=>{const user=await resolveUser(request);return {data:await businessDto(user!.businessId,user!.branchId)}});
  app.put('/api/business/current',{preHandler:guarded('business.manage')},async(request)=>{const user=(await resolveUser(request))!;const input=businessUpdateSchema.parse(request.body);const keys=Object.keys(input);if(keys.length){const columns:Record<string,string>={name:'name',business_type:'business_type',currency:'currency',locale:'locale',timezone:'timezone'};const values=keys.map(k=>(input as any)[k]);await pool.query(`update businesses set ${keys.map((k,i)=>`${columns[k]}=$${i+1}`).join(',')},updated_at=now() where id=$${keys.length+1}`,[...values,user.businessId]);}return {data:await businessDto(user.businessId,user.branchId)}});
  app.put('/api/business/current/features',{preHandler:guarded('business.manage')},async(request,reply)=>{const user=(await resolveUser(request))!;const input=businessFeaturesSchema.parse(request.body);if(!input.enabled_features.includes('tables')&&(await pool.query("select 1 from orders where business_id=$1 and table_id is not null and status not in('completed','cancelled') limit 1",[user.businessId])).rowCount)return reply.code(409).send({message:'Close active table orders before disabling tables.'});if(!input.enabled_features.includes('purchases')&&(await pool.query("select 1 from purchases where business_id=$1 and status not in('received','cancelled') limit 1",[user.businessId])).rowCount)return reply.code(409).send({message:'Complete active purchases before disabling purchases.'});const client=await pool.connect();try{await client.query('begin');await client.query('delete from business_features where business_id=$1',[user.businessId]);for(const feature of input.enabled_features)await client.query('insert into business_features(business_id,feature) values($1,$2)',[user.businessId,feature]);await client.query('commit')}catch(error){await client.query('rollback');throw error}finally{client.release()}return {data:await businessDto(user.businessId,user.branchId)}});
  app.get('/api/branches',{preHandler:guarded('business.manage')},async request=>{const user=(await resolveUser(request))!;return {data:(await pool.query('select * from branches where business_id=$1 order by name',[user.businessId])).rows}});

  app.get('/api/customers',{preHandler:guarded('customers.manage','customers')},async request=>{const u=(await resolveUser(request))!;return {data:(await pool.query('select c.*,(select count(*)::int from orders o where o.customer_id=c.id and o.business_id=c.business_id) order_count,(select coalesce(sum(o.total),0) from orders o where o.customer_id=c.id and o.business_id=c.business_id and o.status=\'completed\') total_spent,(select max(o.created_at) from orders o where o.customer_id=c.id and o.business_id=c.business_id) last_purchase_at from customers c where c.business_id=$1 order by c.name',[u.businessId])).rows}});
  app.post('/api/customers',{preHandler:guarded('customers.manage','customers')},async(request,reply)=>{const u=(await resolveUser(request))!;const input=supplierSchema.pick({name:true,phone:true,email:true,address:true,notes:true,active:true}).parse(request.body);const result=await pool.query('insert into customers(business_id,name,phone,email,address,notes,active) values($1,$2,$3,$4,$5,$6,$7) returning *',[u.businessId,input.name,input.phone??null,input.email??null,input.address??null,input.notes??null,input.active]);return reply.code(201).send({data:result.rows[0]})});
  app.get('/api/suppliers',{preHandler:guarded('suppliers.manage','suppliers')},async request=>{const u=(await resolveUser(request))!;return {data:(await pool.query('select s.*,(select count(*)::int from purchases p where p.supplier_id=s.id and p.business_id=s.business_id) purchase_count,(select count(*)::int from purchases p where p.supplier_id=s.id and p.business_id=s.business_id and p.status=\'received\') received_count,(select coalesce(sum(p.total),0) from purchases p where p.supplier_id=s.id and p.business_id=s.business_id and p.status=\'received\') received_total,(select max(p.created_at) from purchases p where p.supplier_id=s.id and p.business_id=s.business_id) last_purchase_at,(select coalesce(sum(r.total),0) from purchase_returns r join purchases p on p.id=r.purchase_id where p.supplier_id=s.id and r.business_id=s.business_id) returned_total from suppliers s where s.business_id=$1 order by s.name',[u.businessId])).rows}});
  app.post('/api/suppliers',{preHandler:guarded('suppliers.manage','suppliers')},async(request,reply)=>{const u=(await resolveUser(request))!;const input=supplierSchema.parse(request.body);const result=await pool.query('insert into suppliers(business_id,name,contact,phone,email,address,notes,active) values($1,$2,$3,$4,$5,$6,$7,$8) returning *',[u.businessId,input.name,input.contact??null,input.phone??null,input.email??null,input.address??null,input.notes??null,input.active]);return reply.code(201).send({data:result.rows[0]})});

  async function orderDto(orderId:number,businessId:number){const order=(await pool.query('select o.*,t.name table_name,t.table_number,(select s.id from sales s where s.order_id=o.id limit 1) sale_id from orders o left join restaurant_tables t on t.id=o.table_id where o.id=$1 and o.business_id=$2',[orderId,businessId])).rows[0];if(!order)return null;const items=(await pool.query(`select oi.*,p.name product_name,pv.name variant_name,coalesce(json_agg(json_build_object('id',oim.modifier_id,'name',oim.name,'price',oim.price)) filter(where oim.modifier_id is not null),'[]') modifiers from order_items oi join products p on p.id=oi.product_id left join product_variants pv on pv.id=oi.variant_id left join order_item_modifiers oim on oim.order_item_id=oi.id where oi.order_id=$1 group by oi.id,p.name,pv.name order by oi.id`,[orderId])).rows;return {...order,subtotal:num(order.subtotal),discount:num(order.discount),tax:num(order.tax),total:num(order.total),items:items.map(i=>({...i,quantity:num(i.quantity),unit_price:num(i.unit_price),discount:num(i.discount),tax:num(i.tax),total:num(i.total)}))};}
  async function createOrder(input:z.infer<typeof orderSchema>,u:UserContext|null,publicTable?:any){
    const businessId=u?.businessId??publicTable.business_id,branchId=u?.branchId??publicTable.branch_id;
    const existing=(await pool.query('select id from orders where business_id=$1 and client_id=$2',[businessId,input.client_id])).rows[0];
    if(existing)return orderDto(existing.id,businessId);
    const client=await pool.connect();
    try{
      await client.query('begin');
      if(input.table_id){const table=(await client.query('select * from restaurant_tables where id=$1 and business_id=$2 and active=true for update',[input.table_id,businessId])).rows[0];if(!table)throw Object.assign(new Error('Table not found.'),{statusCode:422});if(u&&(await client.query("select 1 from orders where business_id=$1 and table_id=$2 and status not in('completed','cancelled') limit 1",[businessId,input.table_id])).rowCount)throw Object.assign(new Error('Cette table a déjà une commande active.'),{statusCode:409});}
      const productIds=input.items.map(i=>i.product_id);
      const productRows=(await client.query(`select * from products where business_id=$1 and id=any($2::int[]) and is_active=true and available=true${publicTable?' and is_public=true':''} for update`,[businessId,productIds])).rows;
      const byId=new Map(productRows.map(p=>[p.id,p]));
      if(byId.size!==new Set(productIds).size)throw Object.assign(new Error('Product unavailable.'),{statusCode:422});
      let subtotal=0;
      const lines=[];
      for(const item of input.items){
        const p=byId.get(item.product_id);
        const variant=item.variant_id?(await client.query('select * from product_variants where id=$1 and product_id=$2 and business_id=$3 and active=true',[item.variant_id,item.product_id,businessId])).rows[0]:null;
        const modifierRows=item.modifier_ids.length?(await client.query('select * from product_modifiers where business_id=$1 and product_id=$2 and id=any($3::int[]) and active=true',[businessId,item.product_id,item.modifier_ids])).rows:[];
        if(modifierRows.length!==new Set(item.modifier_ids).size)throw Object.assign(new Error('Modifier unavailable.'),{statusCode:422});
        if (item.unit_price !== undefined || item.tax !== 0 || item.discount !== 0) {
          throw Object.assign(new Error('Line prices, taxes, and discounts are calculated by the server.'),{statusCode:422});
        }
        const unit=money(num(p.sale_price)+num(variant?.price_delta)+modifierRows.reduce((sum,m)=>sum+num(m.price),0));
        const total=money(unit*item.quantity);
        subtotal+=total;
        lines.push({item,p,unit,total,modifiers:modifierRows});
      }
      if(input.tax!==0)throw Object.assign(new Error('Order tax is calculated by the server.'),{statusCode:422});
      if(input.discount>0&&(!u||!['patron','owner','admin','manager','cashier'].includes(u.role)))throw Object.assign(new Error('Manual discounts require cash management permission.'),{statusCode:403});
      const discount=money(input.discount);
      if(discount>subtotal)throw Object.assign(new Error('Discount cannot exceed the order subtotal.'),{statusCode:422});
      const tax=0,total=money(subtotal-discount);
      const orderNumber=`${new Date().toISOString().slice(0,10).replaceAll('-','')}-${crypto.randomBytes(4).toString('hex').toUpperCase()}`;
      const result=await client.query(`insert into orders(business_id,branch_id,client_id,order_number,source,type,table_id,customer_id,user_id,status,subtotal,discount,tax,total,payment_status,sync_status,notes) values($1,$2,$3,$4,$5,$6,$7,$8,$9,'pending',$10,$11,$12,$13,'unpaid','synced',$14) returning id`,[businessId,branchId,input.client_id,orderNumber,input.source,input.type,input.table_id??publicTable?.id??null,input.customer_id??null,u?.id??null,subtotal,discount,tax,total,input.notes??null]);
      for(const line of lines){
        const prep=input.type==='retail'?null:'pending';
        const itemResult=await client.query(`insert into order_items(order_id,product_id,variant_id,quantity,unit_price,discount,tax,total,notes,preparation_status) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning id`,[result.rows[0].id,line.item.product_id,line.item.variant_id??null,line.item.quantity,line.unit,line.item.discount,line.item.tax,line.total,line.item.notes??null,prep]);
        for(const modifier of line.modifiers)await client.query('insert into order_item_modifiers(order_item_id,modifier_id,name,price) values($1,$2,$3,$4)',[itemResult.rows[0].id,modifier.id,modifier.name,modifier.price]);
      }
      const stockUserId=u?.id??(await client.query("select id from users where business_id=$1 and role in ('owner','patron','admin') and is_active=true order by id limit 1",[businessId])).rows[0]?.id;
      for(const line of lines){
        if(!line.p.track_stock)continue;
        const changed=(await client.query('update products set stock=stock-$1,updated_at=now() where id=$2 and business_id=$3 and stock>=$1 returning stock',[line.item.quantity,line.item.product_id,businessId])).rows[0];
        if(!changed)throw Object.assign(new Error(`Insufficient stock for ${line.p.name}.`),{statusCode:409});
        if(stockUserId)await client.query("insert into stock_movements(business_id,branch_id,product_id,user_id,type,quantity,before_stock,after_stock,note) values($1,$2,$3,$4,'sale',$5,$6,$7,$8)",[businessId,branchId,line.item.product_id,stockUserId,line.item.quantity,num(changed.stock)+line.item.quantity,changed.stock,`Order ${orderNumber}`]);
      }
      if(input.table_id??publicTable?.id)await client.query("update restaurant_tables set status='occupied',updated_at=now() where id=$1",[input.table_id??publicTable.id]);
      await client.query('commit');
      return orderDto(result.rows[0].id,businessId);
    }catch(error){await client.query('rollback');throw error}finally{client.release()}
  }


  const appendOrderSchema=orderSchema.pick({items:true}).extend({client_id:z.string().uuid()});
  async function appendOrderItems(orderId:number,input:z.infer<typeof appendOrderSchema>,u:UserContext){
    const client=await pool.connect();
    try{
      await client.query('begin');
      const order=(await client.query('select * from orders where id=$1 and business_id=$2 for update',[orderId,u.businessId])).rows[0];
      if(!order)throw Object.assign(new Error('Order not found.'),{statusCode:404});
      const replay=(await client.query("select 1 from audit_logs where business_id=$1 and action='order.append' and entity_type='order_append' and entity_id=$2 limit 1",[u.businessId,input.client_id])).rowCount;
      if(replay){await client.query('rollback');return orderDto(orderId,u.businessId)}
      if(order.payment_status==='paid'||['completed','cancelled'].includes(order.status))throw Object.assign(new Error('Order can no longer be modified.'),{statusCode:409});
      const productIds=input.items.map(item=>item.product_id);
      const productRows=(await client.query('select * from products where business_id=$1 and id=any($2::int[]) and is_active=true and available=true for update',[u.businessId,productIds])).rows;
      const byId=new Map(productRows.map(product=>[product.id,product]));
      if(byId.size!==new Set(productIds).size)throw Object.assign(new Error('Product unavailable.'),{statusCode:422});
      let addedSubtotal=0;
      const lines=[];
      for(const item of input.items){
        const product=byId.get(item.product_id);
        const variant=item.variant_id?(await client.query('select * from product_variants where id=$1 and product_id=$2 and business_id=$3 and active=true',[item.variant_id,item.product_id,u.businessId])).rows[0]:null;
        if(item.variant_id&&!variant)throw Object.assign(new Error('Variant unavailable.'),{statusCode:422});
        const modifiers=item.modifier_ids.length?(await client.query('select * from product_modifiers where business_id=$1 and product_id=$2 and id=any($3::int[]) and active=true',[u.businessId,item.product_id,item.modifier_ids])).rows:[];
        if(modifiers.length!==new Set(item.modifier_ids).size)throw Object.assign(new Error('Modifier unavailable.'),{statusCode:422});
        if (item.unit_price !== undefined || item.tax !== 0 || item.discount !== 0) {
          throw Object.assign(new Error('Line prices, taxes, and discounts are calculated by the server.'),{statusCode:422});
        }
        const unit=money(num(product.sale_price)+num(variant?.price_delta)+modifiers.reduce((sum,modifier)=>sum+num(modifier.price),0));
        const total=money(unit*item.quantity);
        addedSubtotal+=total;
        lines.push({item,product,modifiers,unit,total});
      }
      for(const line of lines){
        const prep=order.type==='retail'?null:'pending';
        const itemResult=await client.query('insert into order_items(order_id,product_id,variant_id,quantity,unit_price,discount,tax,total,notes,preparation_status) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning id',[orderId,line.item.product_id,line.item.variant_id??null,line.item.quantity,line.unit,line.item.discount,line.item.tax,line.total,line.item.notes??null,prep]);
        for(const modifier of line.modifiers)await client.query('insert into order_item_modifiers(order_item_id,modifier_id,name,price) values($1,$2,$3,$4)',[itemResult.rows[0].id,modifier.id,modifier.name,modifier.price]);
      }
      for(const line of lines){
        if(!line.product.track_stock)continue;
        const changed=(await client.query('update products set stock=stock-$1,updated_at=now() where id=$2 and business_id=$3 and stock>=$1 returning stock',[line.item.quantity,line.item.product_id,u.businessId])).rows[0];
        if(!changed)throw Object.assign(new Error(`Insufficient stock for ${line.product.name}.`),{statusCode:409});
        await client.query("insert into stock_movements(business_id,branch_id,product_id,user_id,type,quantity,before_stock,after_stock,note) values($1,$2,$3,$4,'sale',$5,$6,$7,$8)",[u.businessId,order.branch_id,line.item.product_id,u.id,line.item.quantity,num(changed.stock)+line.item.quantity,changed.stock,`Order ${order.order_number}`]);
      }
      const nextSubtotal=num(order.subtotal)+addedSubtotal,nextTotal=Math.max(0,nextSubtotal-num(order.discount)+num(order.tax)),nextStatus=order.type==='retail'?order.status:'pending';
      await client.query('update orders set subtotal=$1,total=$2,status=$3,updated_at=now() where id=$4 and business_id=$5',[nextSubtotal,nextTotal,nextStatus,orderId,u.businessId]);
      if(order.table_id)await client.query("update restaurant_tables set status='occupied',updated_at=now() where id=$1 and business_id=$2",[order.table_id,u.businessId]);
      await client.query("insert into audit_logs(business_id,branch_id,user_id,action,entity_type,entity_id,description) values($1,$2,$3,'order.append','order_append',$4,$5)",[u.businessId,order.branch_id,u.id,input.client_id,`Appended ${lines.length} item line(s) to order ${order.order_number}`]);
      await client.query('commit');
      return orderDto(orderId,u.businessId);
    }catch(error){try{await client.query('rollback')}catch{}throw error}finally{client.release()}
  }

  app.get('/api/orders',{preHandler:guarded('orders.read','pos')},async request=>{const u=(await resolveUser(request))!;const rows=(await pool.query('select id from orders where business_id=$1 order by created_at desc limit 250',[u.businessId])).rows;return {data:await Promise.all(rows.map(r=>orderDto(r.id,u.businessId)))}});
  app.post('/api/orders',{preHandler:guarded('orders.write','pos')},async(request,reply)=>{const u=(await resolveUser(request))!;return reply.code(201).send({data:await createOrder(orderSchema.parse(request.body),u)})});
  app.post('/api/orders/:id/items',{preHandler:guarded('orders.write','pos')},async(request,reply)=>{const u=(await resolveUser(request))!,orderId=id.parse((request.params as any).id),input=appendOrderSchema.parse(request.body);return reply.code(201).send({data:await appendOrderItems(orderId,input,u)})});
  app.post('/api/sync/orders',{preHandler:guarded('orders.write','pos')},async(request)=>{const u=(await resolveUser(request))!;return {data:await createOrder(orderSchema.parse(request.body),u)}});
  app.post('/api/sync/orders/:id/items',{preHandler:guarded('orders.write','pos')},async(request)=>{const u=(await resolveUser(request))!,orderId=id.parse((request.params as any).id),input=appendOrderSchema.parse(request.body);return {data:await appendOrderItems(orderId,input,u)}});
  app.patch('/api/orders/:id/status',{preHandler:guarded('orders.write','pos')},async(request,reply)=>{
    const u=(await resolveUser(request))!;
    const orderId=id.parse((request.params as Record<string,unknown>).id);
    const requested=z.object({status:z.enum(['accepted','preparing','ready','served','cancelled'])}).parse(request.body).status;
    const order=(await pool.query('select status,payment_status,table_id,order_number,branch_id from orders where id=$1 and business_id=$2',[orderId,u.businessId])).rows[0];
    if(!order)return reply.code(404).send({message:'Order not found.'});
    if(order.payment_status==='paid'||['completed','cancelled'].includes(order.status))return reply.code(409).send({message:'Order can no longer be updated.'});
    if(requested==='cancelled'){
      const client=await pool.connect();
      try{
        await client.query('begin');
        const locked=(await client.query('select * from orders where id=$1 and business_id=$2 for update',[orderId,u.businessId])).rows[0];
        if(!locked||locked.payment_status!=='unpaid'||locked.status==='cancelled')throw Object.assign(new Error('Only an unpaid active order can be cancelled.'),{statusCode:409});
        const lines=(await client.query('select oi.product_id,oi.quantity,p.stock,p.track_stock,p.name from order_items oi join products p on p.id=oi.product_id where oi.order_id=$1 for update of p',[orderId])).rows;
        for(const line of lines){if(!line.track_stock)continue;const restored=(await client.query('update products set stock=stock+$1,updated_at=now() where id=$2 and business_id=$3 returning stock',[line.quantity,line.product_id,u.businessId])).rows[0];await client.query("insert into stock_movements(business_id,branch_id,product_id,user_id,type,quantity,before_stock,after_stock,note) values($1,$2,$3,$4,'order_cancel',$5,$6,$7,$8)",[u.businessId,locked.branch_id,line.product_id,u.id,line.quantity,num(restored.stock)-num(line.quantity),restored.stock,`Cancelled order ${locked.order_number}`]);}
        await client.query("update orders set status='cancelled',updated_at=now() where id=$1",[orderId]);
        if(locked.table_id)await client.query("update restaurant_tables set status='available',updated_at=now() where id=$1 and business_id=$2",[locked.table_id,u.businessId]);
        await client.query("insert into audit_logs(business_id,branch_id,user_id,action,entity_type,entity_id,description) values($1,$2,$3,'order.cancel','order',$4,$5)",[u.businessId,locked.branch_id,u.id,String(orderId),`Cancelled unpaid order ${locked.order_number}`]);
        await client.query('commit');
        return {data:await orderDto(orderId,u.businessId)};
      }catch(error){await client.query('rollback');throw error}finally{client.release()}
    }
    const transitions:Record<string,string[]>={pending:['accepted'],accepted:['preparing'],preparing:['ready'],ready:['served'],served:[]};
    if(!transitions[order.status]?.includes(requested))return reply.code(409).send({message:'Invalid order status transition.'});
    await pool.query('update orders set status=$1,updated_at=now() where id=$2 and business_id=$3',[requested,orderId,u.businessId]);
    return {data:await orderDto(orderId,u.businessId)};
  });
  app.post('/api/orders/:id/pay',{preHandler:guarded('cash.manage','pos')},async(request,reply)=>{const u=(await resolveUser(request))!,orderId=id.parse((request.params as any).id),payment=z.object({payment_method:z.enum(['cash','card','other']).default('cash')}).parse(request.body),client=await pool.connect();try{await client.query('begin');const order=(await client.query('select * from orders where id=$1 and business_id=$2 for update',[orderId,u.businessId])).rows[0];if(!order){await client.query('rollback');return reply.code(404).send({message:'Order not found.'})}const existing=(await client.query('select id from sales where order_id=$1 and business_id=$2',[orderId,u.businessId])).rows[0];if(existing){await client.query('rollback');return {data:{order:await orderDto(orderId,u.businessId),sale_id:existing.id,replayed:true}}}const register=(await client.query("select id from cash_register_sessions where business_id=$1 and branch_id is not distinct from $2 and status='open' order by opened_at desc limit 1",[u.businessId,u.branchId])).rows[0];if(!register){await client.query('rollback');return reply.code(409).send({message:'La caisse doit être ouverte avant encaissement.'})}const lines=(await client.query('select oi.*,p.purchase_price from order_items oi join products p on p.id=oi.product_id where oi.order_id=$1',[orderId])).rows,profit=lines.reduce((sum,line)=>sum+(num(line.unit_price)-num(line.purchase_price))*num(line.quantity)-num(line.discount),0),sale=(await client.query('insert into sales(business_id,branch_id,order_id,user_id,cash_register_session_id,payment_method,note,total,profit) values($1,$2,$3,$4,$5,$6,$7,$8,$9) returning id',[u.businessId,u.branchId,orderId,u.id,register.id,payment.payment_method,`Order ${order.order_number}`,order.total,profit])).rows[0];for(const line of lines)await client.query('insert into sale_items(sale_id,product_id,quantity,unit_price,purchase_price,total,profit) values($1,$2,$3,$4,$5,$6,$7)',[sale.id,line.product_id,num(line.quantity),line.unit_price,line.purchase_price,line.total,(num(line.unit_price)-num(line.purchase_price))*num(line.quantity)-num(line.discount)]);await client.query("update orders set payment_status='paid',status='completed',updated_at=now() where id=$1",[orderId]);if(order.table_id){await client.query("update restaurant_tables set status='available',updated_at=now() where id=$1 and business_id=$2",[order.table_id,u.businessId]);await client.query("update table_events set status='resolved',resolved_by_user_id=$1,resolved_at=now() where business_id=$2 and table_id=$3 and type='request_bill' and status='pending'",[u.id,u.businessId,order.table_id])}await client.query('commit');return {data:{order:await orderDto(orderId,u.businessId),sale_id:sale.id,replayed:false}}}catch(error){await client.query('rollback');throw error}finally{client.release()}});

  app.get('/api/rooms',{preHandler:guarded('tables.manage','tables')},async request=>{const u=(await resolveUser(request))!;return {data:(await pool.query('select * from rooms where business_id=$1 and branch_id=$2 order by sort_order,name',[u.businessId,u.branchId])).rows}});
  app.post('/api/rooms',{preHandler:guarded('tables.manage','tables')},async(request,reply)=>{const u=(await resolveUser(request))!;const input=roomSchema.parse(request.body);const row=(await pool.query('insert into rooms(business_id,branch_id,name,sort_order,active) values($1,$2,$3,$4,$5) returning *',[u.businessId,u.branchId,input.name,input.sort_order,input.active])).rows[0];return reply.code(201).send({data:row})});
  app.get('/api/tables',{preHandler:guarded('tables.manage','tables')},async request=>{const u=(await resolveUser(request))!;const missing=(await pool.query('select id from restaurant_tables where business_id=$1 and branch_id=$2 and qr_public_token is null',[u.businessId,u.branchId])).rows;for(const table of missing){const token=crypto.randomBytes(32).toString('base64url');await pool.query('update restaurant_tables set qr_public_token=$1 where id=$2 and business_id=$3 and qr_public_token is null',[token,table.id,u.businessId])}return {data:(await pool.query('select t.*,t.qr_public_token qr_token,r.name room_name from restaurant_tables t join rooms r on r.id=t.room_id where t.business_id=$1 and t.branch_id=$2 order by r.sort_order,t.table_number',[u.businessId,u.branchId])).rows}});
  app.post('/api/tables',{preHandler:guarded('tables.manage','tables')},async(request,reply)=>{const u=(await resolveUser(request))!;const input=tableSchema.parse(request.body);const room=(await pool.query('select 1 from rooms where id=$1 and business_id=$2 and branch_id=$3',[input.room_id,u.businessId,u.branchId])).rows[0];if(!room)return reply.code(422).send({message:'Room not found.'});const token=crypto.randomBytes(32).toString('base64url');const row=(await pool.query('insert into restaurant_tables(business_id,branch_id,room_id,table_number,name,capacity,status,qr_token_hash,qr_token_hint,qr_public_token,active) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) returning *',[u.businessId,u.branchId,input.room_id,input.table_number,input.name,input.capacity,input.status,hash(token),token.slice(-8),token,input.active])).rows[0];return reply.code(201).send({data:{...row,qr_token:token}})});
  app.post('/api/tables/:id/qr-token',{preHandler:guarded('tables.manage','qr_menu')},async(request,reply)=>{const u=(await resolveUser(request))!;const token=crypto.randomBytes(32).toString('base64url');const row=(await pool.query('update restaurant_tables set qr_public_token=$1,qr_token_hash=$2,qr_token_hint=$3,updated_at=now() where id=$4 and business_id=$5 returning *',[token,hash(token),token.slice(-8),id.parse((request.params as any).id),u.businessId])).rows[0];return row?{data:{...row,qr_token:token}}:reply.code(404).send({message:'Table not found.'})});
  app.get('/api/table-events',{preHandler:guarded('tables.manage','tables')},async request=>{const u=(await resolveUser(request))!;return {data:(await pool.query("select e.*,t.name table_name,t.table_number from table_events e join restaurant_tables t on t.id=e.table_id where e.business_id=$1 and e.status='pending' order by e.created_at",[u.businessId])).rows}});
  app.patch('/api/table-events/:id/resolve',{preHandler:guarded('tables.manage','tables')},async(request,reply)=>{const u=(await resolveUser(request))!;const row=(await pool.query("update table_events set status='resolved',resolved_by_user_id=$1,resolved_at=now() where id=$2 and business_id=$3 and status='pending' returning *",[u.id,id.parse((request.params as any).id),u.businessId])).rows[0];return row?{data:row}:reply.code(404).send({message:'Request not found.'})});

  app.get('/api/kitchen/orders',{preHandler:guarded('kitchen.use','kitchen')},async request=>{const u=(await resolveUser(request))!;const rows=(await pool.query("select id from orders where business_id=$1 and type<>'retail' and status not in('completed','cancelled') order by created_at",[u.businessId])).rows;return {data:await Promise.all(rows.map(r=>orderDto(r.id,u.businessId)))}});
  app.patch('/api/kitchen/items/:id',{preHandler:guarded('kitchen.use','kitchen')},async(request,reply)=>{const u=(await resolveUser(request))!;const status=z.object({status:z.enum(['pending','accepted','preparing','ready','served','cancelled'])}).parse(request.body).status;const row=(await pool.query('update order_items oi set preparation_status=$1,updated_at=now() from orders o where oi.id=$2 and oi.order_id=o.id and o.business_id=$3 returning oi.*,o.id order_id',[status,id.parse((request.params as any).id),u.businessId])).rows[0];if(!row)return reply.code(404).send({message:'Order item not found.'});const states=(await pool.query('select preparation_status from order_items where order_id=$1 and preparation_status is not null',[row.order_id])).rows.map(item=>item.preparation_status),orderStatus=states.every(value=>value==='served'||value==='cancelled')?'served':states.every(value=>['ready','served','cancelled'].includes(value))?'ready':states.some(value=>['accepted','preparing'].includes(value))?'preparing':'pending';await pool.query('update orders set status=$1,updated_at=now() where id=$2',[orderStatus,row.order_id]);return {data:row}});

  async function publicTable(slug:string,token:string,requiredFeatures=['qr_menu']){const row=(await pool.query(`select t.*,b.slug,b.name business_name,b.currency,r.name room_name from restaurant_tables t join businesses b on b.id=t.business_id join rooms r on r.id=t.room_id join business_features f on f.business_id=b.id and f.feature='qr_menu' where b.slug=$1 and (t.qr_public_token=$2 or t.qr_token_hash=$3) and t.active=true`,[slug,token,hash(token)])).rows[0];if(!row)return null;if(process.env.LICENSE_MODE==='development'&&process.env.NODE_ENV!=='production')return row;const entitled=await pool.query("select 1 from businesses b join vendor_businesses vb on vb.id=b.vendor_business_id join business_licenses bl on bl.business_id=b.id join licenses l on l.id=bl.license_id and l.vendor_business_id=vb.id where b.id=$1 and vb.status='active' and bl.status='active' and l.status='active' and (l.expires_at is null or l.expires_at>now()) and l.allowed_features ?& $2::text[]",[row.business_id,requiredFeatures]);return entitled.rowCount?row:null}
  app.get('/api/public/menu/:slug/table/:token',async(request,reply)=>{const p=request.params as any;const table=await publicTable(p.slug,p.token);if(!table)return reply.code(404).send({message:'Menu not found.'});const categories=(await pool.query('select * from categories where business_id=$1 and is_public=true order by name',[table.business_id])).rows;const products=(await pool.query('select * from products where business_id=$1 and is_public=true and is_active=true and available=true order by name',[table.business_id])).rows;const productIds=products.map(product=>product.id),variants=productIds.length?(await pool.query('select id,product_id,name,price_delta price from product_variants where business_id=$1 and product_id=any($2::int[]) and active=true order by id',[table.business_id,productIds])).rows:[],modifiers=productIds.length?(await pool.query('select id,product_id,name,price from product_modifiers where business_id=$1 and product_id=any($2::int[]) and active=true order by id',[table.business_id,productIds])).rows:[];return {data:{business:{name:table.business_name,slug:table.slug,currency:table.currency},table:{id:table.id,name:table.name,number:table.table_number,room:table.room_name},categories,products:products.map(product=>({...product,sale_price:num(product.sale_price),purchase_price:undefined,variants:variants.filter(v=>v.product_id===product.id).map(v=>({...v,price:num(v.price)})),modifiers:modifiers.filter(m=>m.product_id===product.id).map(m=>({...m,price:num(m.price)}))}))}}});
  app.post('/api/public/menu/:slug/table/:token/orders',{config:{rateLimit:{max:10,timeWindow:'1 minute'}}},async(request,reply)=>{const p=request.params as any;const table=await publicTable(p.slug,p.token,['qr_menu','pos']);if(!table)return reply.code(404).send({message:'Menu not found.'});const input=orderSchema.parse({...request.body as object,source:'qr_table',type:'dine_in',table_id:table.id});return reply.code(201).send({data:await createOrder(input,null,table)})});
  app.post('/api/public/menu/:slug/table/:token/events',{config:{rateLimit:{max:8,timeWindow:'1 minute'}}},async(request,reply)=>{const p=request.params as any;const table=await publicTable(p.slug,p.token);if(!table)return reply.code(404).send({message:'Menu not found.'});const type=z.object({type:z.enum(['call_waiter','request_bill'])}).parse(request.body).type;await pool.query('insert into table_events(business_id,table_id,type) values($1,$2,$3)',[table.business_id,table.id,type]);if(type==='request_bill')await pool.query("update restaurant_tables set status='bill_requested' where id=$1",[table.id]);return reply.code(202).send({message:'Request received.'})});

  app.get('/api/purchases',{preHandler:guarded('purchases.manage','purchases')},async request=>{const u=(await resolveUser(request))!;return {data:(await pool.query('select p.*,s.name supplier_name from purchases p join suppliers s on s.id=p.supplier_id where p.business_id=$1 order by p.created_at desc',[u.businessId])).rows}});
  app.post('/api/purchases',{preHandler:guarded('purchases.manage','purchases')},async(request,reply)=>{const u=(await resolveUser(request))!;const input=purchaseSchema.parse(request.body);const supplier=(await pool.query('select 1 from suppliers where id=$1 and business_id=$2',[input.supplier_id,u.businessId])).rows[0];if(!supplier)return reply.code(422).send({message:'Supplier not found.'});const productIds=input.items.map(i=>i.product_id);const valid=(await pool.query('select count(*)::int count from products where business_id=$1 and id=any($2::int[])',[u.businessId,productIds])).rows[0].count;if(valid!==new Set(productIds).size)return reply.code(422).send({message:'Product not found.'});const subtotal=input.items.reduce((s,i)=>s+i.quantity*i.purchase_price,0),total=subtotal+input.tax;const client=await pool.connect();try{await client.query('begin');const row=(await client.query('insert into purchases(business_id,branch_id,supplier_id,reference,status,subtotal,tax,total,payment_status) values($1,$2,$3,$4,$5,$6,$7,$8,$9) returning *',[u.businessId,u.branchId,input.supplier_id,input.reference,input.status,subtotal,input.tax,total,input.payment_status])).rows[0];for(const item of input.items)await client.query('insert into purchase_items(purchase_id,product_id,quantity,purchase_price,tax,total) values($1,$2,$3,$4,$5,$6)',[row.id,item.product_id,item.quantity,item.purchase_price,item.tax,item.quantity*item.purchase_price+item.tax]);await client.query('commit');return reply.code(201).send({data:row})}catch(error){await client.query('rollback');throw error}finally{client.release()}});
  app.post('/api/purchases/:id/receive',{preHandler:guarded('purchases.manage','purchases')},async(request,reply)=>{const u=(await resolveUser(request))!;const purchaseId=id.parse((request.params as any).id);const client=await pool.connect();try{await client.query('begin');const purchase=(await client.query("select * from purchases where id=$1 and business_id=$2 and status not in('received','cancelled') for update",[purchaseId,u.businessId])).rows[0];if(!purchase){await client.query('rollback');return reply.code(409).send({message:'Purchase cannot be received.'})}const items=(await client.query('select * from purchase_items where purchase_id=$1',[purchaseId])).rows;for(const item of items){const product=(await client.query('select * from products where id=$1 and business_id=$2 for update',[item.product_id,u.businessId])).rows[0];const quantity=num(item.quantity)-num(item.received_quantity);if(quantity<=0)continue;const before=product.stock,after=before+quantity;await client.query('update products set stock=$1,purchase_price=$2,updated_at=now() where id=$3',[after,item.purchase_price,item.product_id]);await client.query("insert into stock_movements(business_id,branch_id,product_id,user_id,type,quantity,before_stock,after_stock,note) values($1,$2,$3,$4,'purchase',$5,$6,$7,$8)",[u.businessId,u.branchId,item.product_id,u.id,quantity,before,after,`Purchase ${purchase.reference}`]);await client.query('update purchase_items set received_quantity=quantity where id=$1',[item.id])}await client.query("update purchases set status='received',received_at=now(),updated_at=now() where id=$1",[purchaseId]);await client.query('commit');return {data:(await pool.query('select * from purchases where id=$1',[purchaseId])).rows[0]}}catch(error){await client.query('rollback');throw error}finally{client.release()}});
  app.get('/api/purchases/:id',{preHandler:guarded('purchases.manage','purchases')},async(request,reply)=>{const u=(await resolveUser(request))!,purchaseId=id.parse((request.params as any).id),purchase=(await pool.query('select p.*,s.name supplier_name from purchases p join suppliers s on s.id=p.supplier_id where p.id=$1 and p.business_id=$2',[purchaseId,u.businessId])).rows[0];if(!purchase)return reply.code(404).send({message:'Purchase not found.'});return {data:{...purchase,items:(await pool.query('select i.*,p.name product_name,coalesce((select sum(quantity) from purchase_returns r where r.purchase_item_id=i.id),0) returned_quantity from purchase_items i join products p on p.id=i.product_id where i.purchase_id=$1',[purchaseId])).rows,returns:(await pool.query('select r.*,p.name product_name from purchase_returns r join products p on p.id=r.product_id where r.purchase_id=$1 order by r.created_at desc',[purchaseId])).rows}}});
  app.post('/api/purchases/:id/returns',{preHandler:guarded('purchases.manage','purchases')},async(request,reply)=>{const u=(await resolveUser(request))!,purchaseId=id.parse((request.params as any).id),input=z.object({purchase_item_id:z.number().int().positive(),quantity:z.coerce.number().positive(),reason:z.string().trim().min(2).max(500)}).parse(request.body),client=await pool.connect();try{await client.query('begin');const item=(await client.query('select i.*,p.stock,p.name product_name from purchase_items i join purchases x on x.id=i.purchase_id join products p on p.id=i.product_id where i.id=$1 and i.purchase_id=$2 and x.business_id=$3 for update of p',[input.purchase_item_id,purchaseId,u.businessId])).rows[0];if(!item){await client.query('rollback');return reply.code(404).send({message:'Purchase item not found.'})}const returned=num((await client.query('select coalesce(sum(quantity),0) quantity from purchase_returns where purchase_item_id=$1',[item.id])).rows[0].quantity),available=num(item.received_quantity)-returned;if(input.quantity>available)throw Object.assign(new Error(`Return quantity exceeds received quantity for ${item.product_name}.`),{statusCode:409});if(input.quantity>num(item.stock))throw Object.assign(new Error(`Insufficient current stock for ${item.product_name}.`),{statusCode:409});const total=input.quantity*num(item.purchase_price),before=num(item.stock),after=before-input.quantity,created=(await client.query('insert into purchase_returns(business_id,branch_id,purchase_id,purchase_item_id,product_id,user_id,quantity,reason,total) values($1,$2,$3,$4,$5,$6,$7,$8,$9) returning *',[u.businessId,u.branchId,purchaseId,item.id,item.product_id,u.id,input.quantity,input.reason,total])).rows[0];await client.query('update products set stock=$1,updated_at=now() where id=$2',[after,item.product_id]);await client.query("insert into stock_movements(business_id,branch_id,product_id,user_id,type,quantity,before_stock,after_stock,note) values($1,$2,$3,$4,'purchase_return',$5,$6,$7,$8)",[u.businessId,u.branchId,item.product_id,u.id,input.quantity,before,after,`Purchase return #${purchaseId}: ${input.reason}`]);await client.query('insert into audit_logs(business_id,branch_id,user_id,action,entity_type,entity_id,description) values($1,$2,$3,\'purchase.return\',\'purchase\',$4,$5)',[u.businessId,u.branchId,u.id,String(purchaseId),`${input.quantity} x ${item.product_name}: ${input.reason}`]);await client.query('commit');return reply.code(201).send({data:created})}catch(error){await client.query('rollback');throw error}finally{client.release()}});

  const returnSchema=z.object({reason:z.string().trim().min(2).max(500),refund_method:z.enum(['original','cash','card','other']).default('original'),items:z.array(z.object({sale_item_id:z.number().int().positive(),quantity:z.coerce.number().positive()})).min(1)});
  app.get('/api/sales/:id/returns',{preHandler:guarded('reports.read','pos')},async request=>{const u=(await resolveUser(request))!,saleId=id.parse((request.params as any).id);return {data:(await pool.query('select r.*,coalesce(json_agg(ri.*) filter(where ri.id is not null),\'[]\') items from sale_returns r left join sale_return_items ri on ri.return_id=r.id where r.business_id=$1 and r.sale_id=$2 group by r.id order by r.created_at desc',[u.businessId,saleId])).rows}});
  app.post('/api/sales/:id/returns',{preHandler:guarded('inventory.write','inventory')},async(request,reply)=>{const u=(await resolveUser(request))!,saleId=id.parse((request.params as any).id),input=returnSchema.parse(request.body),client=await pool.connect();try{await client.query('begin');const sale=(await client.query('select * from sales where id=$1 and business_id=$2 for update',[saleId,u.businessId])).rows[0];if(!sale){await client.query('rollback');return reply.code(404).send({message:'Sale not found.'})}let total=0;const lines=[];for(const requested of input.items){const item=(await client.query('select si.*,p.track_stock,p.name product_name from sale_items si join products p on p.id=si.product_id where si.id=$1 and si.sale_id=$2 and p.business_id=$3',[requested.sale_item_id,saleId,u.businessId])).rows[0];if(!item)throw Object.assign(new Error('Sale item not found.'),{statusCode:422});const returned=num((await client.query('select coalesce(sum(quantity),0) quantity from sale_return_items where sale_item_id=$1',[item.id])).rows[0].quantity);if(requested.quantity>num(item.quantity)-returned)throw Object.assign(new Error(`Return quantity exceeds remaining quantity for ${item.product_name}.`),{statusCode:409});const lineTotal=num(item.unit_price)*requested.quantity;total+=lineTotal;lines.push({item,quantity:requested.quantity,total:lineTotal})}const created=(await client.query('insert into sale_returns(business_id,branch_id,sale_id,user_id,reason,refund_method,total) values($1,$2,$3,$4,$5,$6,$7) returning *',[u.businessId,u.branchId,saleId,u.id,input.reason,input.refund_method,total])).rows[0];for(const line of lines){await client.query('insert into sale_return_items(return_id,sale_item_id,product_id,quantity,unit_price,total) values($1,$2,$3,$4,$5,$6)',[created.id,line.item.id,line.item.product_id,line.quantity,line.item.unit_price,line.total]);if(line.item.track_stock){const product=(await client.query('update products set stock=stock+$1,updated_at=now() where id=$2 and business_id=$3 returning stock',[line.quantity,line.item.product_id,u.businessId])).rows[0];await client.query("insert into stock_movements(business_id,branch_id,product_id,user_id,type,quantity,before_stock,after_stock,note) values($1,$2,$3,$4,'sale_return',$5,$6,$7,$8)",[u.businessId,u.branchId,line.item.product_id,u.id,line.quantity,num(product.stock)-line.quantity,product.stock,`Return sale #${saleId}: ${input.reason}`])}}await client.query('insert into audit_logs(business_id,branch_id,user_id,action,entity_type,entity_id,description) values($1,$2,$3,\'sale.return\',\'sale\',$4,$5)',[u.businessId,u.branchId,u.id,String(saleId),`Refund ${total}: ${input.reason}`]);await client.query('commit');return reply.code(201).send({data:{...created,items:lines}})}catch(error){await client.query('rollback');throw error}finally{client.release()}});

  app.get('/api/inventory-counts',{preHandler:guarded('inventory.read','inventory')},async request=>{const u=(await resolveUser(request))!;return {data:(await pool.query('select c.*,count(i.id)::int item_count,count(i.counted_stock)::int counted_count from inventory_counts c left join inventory_count_items i on i.count_id=c.id where c.business_id=$1 group by c.id order by c.created_at desc',[u.businessId])).rows}});
  app.post('/api/inventory-counts',{preHandler:guarded('inventory.write','inventory')},async(request,reply)=>{const u=(await resolveUser(request))!,reason=z.object({reason:z.string().trim().max(500).nullable().optional()}).parse(request.body).reason,client=await pool.connect();try{await client.query('begin');const count=(await client.query('insert into inventory_counts(business_id,branch_id,user_id,reason) values($1,$2,$3,$4) returning *',[u.businessId,u.branchId,u.id,reason??null])).rows[0];await client.query('insert into inventory_count_items(count_id,product_id,expected_stock) select $1,id,stock from products where business_id=$2 and track_stock=true and is_active=true',[count.id,u.businessId]);await client.query('commit');return reply.code(201).send({data:count})}catch(error){await client.query('rollback');throw error}finally{client.release()}});
  app.get('/api/inventory-counts/:id',{preHandler:guarded('inventory.read','inventory')},async(request,reply)=>{const u=(await resolveUser(request))!,countId=id.parse((request.params as any).id),count=(await pool.query('select * from inventory_counts where id=$1 and business_id=$2',[countId,u.businessId])).rows[0];if(!count)return reply.code(404).send({message:'Inventory count not found.'});return {data:{...count,items:(await pool.query('select i.*,p.name,p.sku,p.barcode,p.unit from inventory_count_items i join products p on p.id=i.product_id where i.count_id=$1 order by p.name',[countId])).rows}}});
  app.put('/api/inventory-counts/:id/items',{preHandler:guarded('inventory.write','inventory')},async(request,reply)=>{const u=(await resolveUser(request))!,countId=id.parse((request.params as any).id),input=z.object({items:z.array(z.object({product_id:z.number().int().positive(),counted_stock:z.coerce.number().nonnegative()})).min(1)}).parse(request.body);const count=(await pool.query("select 1 from inventory_counts where id=$1 and business_id=$2 and status='draft'",[countId,u.businessId])).rows[0];if(!count)return reply.code(409).send({message:'Inventory count is not editable.'});for(const item of input.items)await pool.query('update inventory_count_items set counted_stock=$1 where count_id=$2 and product_id=$3',[item.counted_stock,countId,item.product_id]);return {data:{updated:input.items.length}}});
  app.post('/api/inventory-counts/:id/confirm',{preHandler:guarded('inventory.write','inventory')},async(request,reply)=>{const u=(await resolveUser(request))!,countId=id.parse((request.params as any).id),client=await pool.connect();try{await client.query('begin');const count=(await client.query("select * from inventory_counts where id=$1 and business_id=$2 and status='draft' for update",[countId,u.businessId])).rows[0];if(!count){await client.query('rollback');return reply.code(409).send({message:'Inventory count cannot be confirmed.'})}const items=(await client.query('select i.*,p.stock,p.name from inventory_count_items i join products p on p.id=i.product_id where i.count_id=$1 and i.counted_stock is not null for update of p',[countId])).rows;for(const item of items){const before=num(item.stock),after=num(item.counted_stock),difference=after-before;if(!difference)continue;await client.query('update products set stock=$1,updated_at=now() where id=$2',[after,item.product_id]);await client.query("insert into stock_movements(business_id,branch_id,product_id,user_id,type,quantity,before_stock,after_stock,note) values($1,$2,$3,$4,$5,$6,$7,$8,$9)",[u.businessId,u.branchId,item.product_id,u.id,difference>0?'adjustment_in':'adjustment_out',Math.abs(difference),before,after,`Inventory #${countId}${count.reason?`: ${count.reason}`:''}`])}await client.query("update inventory_counts set status='confirmed',confirmed_at=now() where id=$1",[countId]);await client.query('insert into audit_logs(business_id,branch_id,user_id,action,entity_type,entity_id,description) values($1,$2,$3,\'inventory.confirm\',\'inventory_count\',$4,$5)',[u.businessId,u.branchId,u.id,String(countId),`Confirmed ${items.length} counted products`]);await client.query('commit');return {data:{id:countId,status:'confirmed'}}}catch(error){await client.query('rollback');throw error}finally{client.release()}});

  app.get('/api/audit-logs',{preHandler:guarded('business.manage')},async request=>{const u=(await resolveUser(request))!;return {data:(await pool.query('select a.*,u.name user_name from audit_logs a left join users u on u.id=a.user_id where a.business_id=$1 order by a.created_at desc limit 250',[u.businessId])).rows}});
  app.get('/api/sync/status',{preHandler:guarded()},async request=>{const u=(await resolveUser(request))!;const row=(await pool.query("select max(updated_at) last_sync_at,count(*) filter(where sync_status in('failed','conflict'))::int failed_count from sync_mutations where business_id=$1",[u.businessId])).rows[0];return {data:{...row,sync_status:row.failed_count?'failed':'synced'}}});
}
