import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import bcrypt from 'bcryptjs'
import {DatabaseSync} from 'node:sqlite'
import {buildLocalApp} from '../local/server.js'
import {localMigrations} from '../local/migrations.js'

// These onboarding/restaurant tests exercise the explicit development path;
// commercial certificate enforcement is covered by the licensing tests.
process.env.LICENSE_MODE='development'

const payload=(business_type:'library'|'cafe')=>({business:{name:business_type==='library'?'Librairie Atlas':'Cafe Atlas',business_type,currency:'MAD',locale:'fr-MA',timezone:'Africa/Casablanca',phone:'0500000000',address:'Centre'},enabled_features:business_type==='library'?['pos','inventory','barcode','suppliers','purchases','customers']:['pos','inventory','tables','qr_menu','kitchen','takeaway'],admin:{name:'Owner Test',email:`owner-${business_type}@test.invalid`,password:'password123'}})
function paths(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'bimik-core-setup-'));return {root,database:path.join(root,'data','bimik-cafe.sqlite'),uploads:path.join(root,'uploads'),logs:path.join(root,'logs'),backups:path.join(root,'backups'),config:path.join(root,'config','local.json')}}

for(const businessType of ['library','cafe'] as const)test(`fresh local ${businessType} setup, owner login and module visibility`,async()=>{const localPaths=paths(),app=await buildLocalApp({paths:localPaths,logger:false});try{assert.equal((await app.inject({method:'GET',url:'/api/setup/status'})).json().data.configured,false);assert.equal((await app.inject({method:'POST',url:'/api/setup',payload:payload(businessType)})).statusCode,201);const profiles=(await app.inject({method:'GET',url:'/api/login-profiles'})).json().data;assert.equal(profiles[0].role,'owner');const login=await app.inject({method:'POST',url:'/api/login',payload:{email:`owner-${businessType}@test.invalid`,password:'password123'}});assert.equal(login.statusCode,200);const token=login.json().data.access_token,headers={authorization:`Bearer ${token}`};const business=(await app.inject({method:'GET',url:'/api/business/current',headers})).json().data;assert.equal(business.business_type,businessType);assert.equal(business.enabled_features.includes('tables'),businessType==='cafe');assert.equal((await app.inject({method:'GET',url:'/api/tables',headers})).statusCode,businessType==='cafe'?200:403);assert.equal((await app.inject({method:'GET',url:'/api/kitchen/orders',headers})).statusCode,businessType==='cafe'?200:403)}finally{await app.close();fs.rmSync(localPaths.root,{recursive:true,force:true})}})

test('legacy local cafe data migrates without onboarding',async()=>{const localPaths=paths();fs.mkdirSync(path.dirname(localPaths.database),{recursive:true});const db=new DatabaseSync(localPaths.database);for(const migration of localMigrations.filter(x=>x.version<3))db.exec(migration.sql);db.prepare('insert into users(name,email,password,role,is_active,created_at,updated_at) values(?,?,?,?,1,?,?)').run('Legacy Owner','legacy@test.invalid',await bcrypt.hash('password123',12),'patron',new Date().toISOString(),new Date().toISOString());db.exec('pragma user_version=2');db.close();const app=await buildLocalApp({paths:localPaths,logger:false});try{const status=(await app.inject({method:'GET',url:'/api/setup/status'})).json().data;assert.equal(status.configured,true);assert.equal(status.business.business_type,'cafe');const migrated=new DatabaseSync(localPaths.database);const commercial=migrated.prepare("select status,reason_code from merchant_license_state where id=1").get();migrated.close();assert.equal(commercial?.status,'activation_required');assert.equal(commercial?.reason_code,'LEGACY_ACTIVATION_REQUIRED');assert.equal((await app.inject({method:'POST',url:'/api/setup',payload:payload('library')})).statusCode,409)}finally{await app.close();fs.rmSync(localPaths.root,{recursive:true,force:true})}})

test('local table requests retain resolver identity and timestamp',async()=>{const localPaths=paths(),app=await buildLocalApp({paths:localPaths,logger:false});try{await app.inject({method:'POST',url:'/api/setup',payload:payload('cafe')});const login=(await app.inject({method:'POST',url:'/api/login',payload:{email:'owner-cafe@test.invalid',password:'password123'}})).json().data,headers={authorization:`Bearer ${login.access_token}`};const room=(await app.inject({method:'POST',url:'/api/rooms',headers,payload:{name:'Salle',sort_order:0,active:true}})).json().data;const table=(await app.inject({method:'POST',url:'/api/tables',headers,payload:{room_id:room.id,table_number:'T1',name:'Table 1',capacity:4,status:'available',active:true}})).json().data;assert.equal((await app.inject({method:'POST',url:`/api/public/menu/cafe-atlas/table/${table.qr_token}/events`,payload:{type:'call_waiter'}})).statusCode,202);const event=(await app.inject({method:'GET',url:'/api/table-events',headers})).json().data[0];const resolved=(await app.inject({method:'PATCH',url:`/api/table-events/${event.id}/resolve`,headers})).json().data;assert.equal(resolved.status,'resolved');assert.equal(resolved.resolved_by_user_id,login.user.id);assert.ok(resolved.resolved_at)}finally{await app.close();fs.rmSync(localPaths.root,{recursive:true,force:true})}})

test('local table QR remains stable until explicit regeneration',async()=>{const localPaths=paths(),app=await buildLocalApp({paths:localPaths,logger:false});try{await app.inject({method:'POST',url:'/api/setup',payload:payload('cafe')});const login=(await app.inject({method:'POST',url:'/api/login',payload:{email:'owner-cafe@test.invalid',password:'password123'}})).json().data,headers={authorization:`Bearer ${login.access_token}`};const room=(await app.inject({method:'POST',url:'/api/rooms',headers,payload:{name:'Salle',sort_order:0,active:true}})).json().data;const created=(await app.inject({method:'POST',url:'/api/tables',headers,payload:{room_id:room.id,table_number:'5',name:'Table 5',capacity:4,status:'available',active:true}})).json().data;const database=new DatabaseSync(localPaths.database);database.prepare('update restaurant_tables set qr_public_token=null where id=?').run(created.id);database.close();const first=(await app.inject({method:'GET',url:'/api/tables',headers})).json().data[0],second=(await app.inject({method:'GET',url:'/api/tables',headers})).json().data[0];assert.notEqual(first.qr_token,created.qr_token);assert.equal(second.qr_token,first.qr_token);assert.equal((await app.inject({method:'GET',url:`/api/public/menu/cafe-atlas/table/${created.qr_token}`})).statusCode,200);assert.equal((await app.inject({method:'GET',url:`/api/public/menu/cafe-atlas/table/${first.qr_token}`})).statusCode,200);const regenerated=(await app.inject({method:'POST',url:`/api/tables/${created.id}/qr-token`,headers,payload:{}})).json().data;assert.notEqual(regenerated.qr_token,first.qr_token);assert.equal((await app.inject({method:'GET',url:`/api/public/menu/cafe-atlas/table/${created.qr_token}`})).statusCode,404);assert.equal((await app.inject({method:'GET',url:`/api/public/menu/cafe-atlas/table/${first.qr_token}`})).statusCode,404);assert.equal((await app.inject({method:'GET',url:`/api/public/menu/cafe-atlas/table/${regenerated.qr_token}`})).statusCode,200)}finally{await app.close();fs.rmSync(localPaths.root,{recursive:true,force:true})}})

test('local QR order deducts decimal inventory exactly once on replay',async()=>{
  const localPaths=paths(),app=await buildLocalApp({paths:localPaths,logger:false});
  try{
    await app.inject({method:'POST',url:'/api/setup',payload:payload('cafe')});
    const login=(await app.inject({method:'POST',url:'/api/login',payload:{email:'owner-cafe@test.invalid',password:'password123'}})).json().data,headers={authorization:`Bearer ${login.access_token}`};
    const room=(await app.inject({method:'POST',url:'/api/rooms',headers,payload:{name:'Salle',sort_order:0,active:true}})).json().data;
    const table=(await app.inject({method:'POST',url:'/api/tables',headers,payload:{room_id:room.id,table_number:'5',name:'Table 5',capacity:4,status:'available',active:true}})).json().data;
    const database=new DatabaseSync(localPaths.database),stamp=new Date().toISOString();
    const productId=Number(database.prepare("insert into products(business_id,category_id,name,sale_price_cents,purchase_price_cents,stock,min_stock,track_stock,is_active,is_public,available,created_at,updated_at) values(1,null,'Cafe grain',4000,1000,10,1,1,1,1,1,?,?)").run(stamp,stamp).lastInsertRowid);
    database.close();
    const client_id=crypto.randomUUID(),body={client_id,items:[{product_id:productId,quantity:.75,modifier_ids:[]}]},url=`/api/public/menu/cafe-atlas/table/${table.qr_token}/orders`;
    const first=await app.inject({method:'POST',url,payload:body}),replay=await app.inject({method:'POST',url,payload:body});
    assert.equal(first.statusCode,201);assert.equal(replay.statusCode,201);assert.equal(replay.json().data.id,first.json().data.id);
    const check=new DatabaseSync(localPaths.database);
    assert.equal(check.prepare('select stock from products where id=?').get(productId)!.stock,9.25);
    assert.equal(check.prepare("select count(*) count from stock_movements where product_id=? and type='sale'").get(productId)!.count,1);
    check.close();
  }finally{await app.close();fs.rmSync(localPaths.root,{recursive:true,force:true})}
})
