import { createHash } from 'node:crypto';import { readdir,readFile } from 'node:fs/promises';import path from 'node:path';import { spawn } from 'node:child_process';import { fileURLToPath } from 'node:url';import argon2 from 'argon2';import pg from 'pg';import { config } from '../src/config.js';
const args=new Map<string,string|true>();for(let i=2;i<process.argv.length;i++){const key=process.argv[i]!;if(key.startsWith('--')){const next=process.argv[i+1];if(next&&!next.startsWith('--')){args.set(key,next);i++}else args.set(key,true)}}
const url=new URL(config.DATABASE_URL),actual=decodeURIComponent(url.pathname.slice(1)),requested=args.get('--database'),confirmed=args.get('--confirm-database');
if(args.get('--execute-reset')!==true)throw new Error('Refus: ajoutez explicitement --execute-reset après examen de la sauvegarde.');
if(typeof requested!=='string'||typeof confirmed!=='string'||requested!==confirmed||requested!==actual)throw new Error('Refus: --database et --confirm-database doivent correspondre exactement à DATABASE_URL.');
if(['postgres','template0','template1'].includes(actual))throw new Error('Refus d’opérer sur une base système.');
const name=process.env.INITIAL_PATRON_NAME?.trim(),email=process.env.INITIAL_PATRON_EMAIL?.trim().toLowerCase(),password=process.env.INITIAL_PATRON_PASSWORD;if(!name||!email||!password)throw new Error('INITIAL_PATRON_NAME, INITIAL_PATRON_EMAIL et INITIAL_PATRON_PASSWORD doivent être définis localement.');
const repositoryRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..'),backupDir=path.join(repositoryRoot,'backups'),manifests=(await readdir(backupDir)).filter(f=>f.startsWith(`${actual}-`)&&f.endsWith('.dump.verified.json')).sort().reverse();if(!manifests.length)throw new Error(`Aucune sauvegarde vérifiée trouvée pour ${actual}.`);
const manifestPath=path.join(backupDir,manifests[0]!),manifest=JSON.parse(await readFile(manifestPath,'utf8')) as Record<string,unknown>;if(manifest.database!==actual||manifest.host!==url.hostname||String(manifest.port)!==(url.port||'5432')||manifest.pg_restore_list_valid!==true)throw new Error('La preuve de sauvegarde ne correspond pas à la cible.');
const dumpPath=String(manifest.dump_path),checksum=createHash('sha256').update(await readFile(dumpPath)).digest('hex');if(checksum!==manifest.dump_sha256)throw new Error('Le checksum de la sauvegarde ne correspond plus.');
const validate=(command:string,commandArgs:string[])=>new Promise<void>((resolve,reject)=>{const child=spawn(command,commandArgs,{stdio:'inherit'});child.on('error',reject);child.on('exit',c=>c===0?resolve():reject(new Error(`${command} a échoué.`)))});try{await validate('pg_restore',['--list',dumpPath])}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;await validate('docker',['run','--rm','--mount',`type=bind,source=${path.dirname(dumpPath)},target=/backups`,'postgres:18-alpine','pg_restore','--list',`/backups/${path.basename(dumpPath)}`])}
console.log(`Cible vérifiée: host=${url.hostname} port=${url.port||'5432'} database=${actual}`);console.log(`Sauvegarde vérifiée: ${dumpPath}`);console.log(`SHA-256: ${manifest.dump_sha256}`);
const client=new pg.Client({connectionString:config.DATABASE_URL});await client.connect();try{await client.query('begin');for(const table of ['refresh_tokens','sale_items','sales','stock_movements','menu_import_sessions','products','categories','users'])await client.query(`delete from ${table}`);await client.query(`delete from settings where key in ('wifi_name','wifi_code','cafe_name','cafe_subtitle','cafe_address','cafe_phone','ticket_header','ticket_footer','ticket_note')`);const hash=await argon2.hash(password);await client.query('insert into users(name,email,password,role,is_active) values($1,$2,$3,$4,true)',[name,email,hash,'patron']);for(const table of ['users','categories','products','sales','sale_items','stock_movements','refresh_tokens'])await client.query(`select setval(pg_get_serial_sequence('${table}','id'),coalesce((select max(id) from ${table}),1),exists(select 1 from ${table}))`);
const counts=(await client.query(`select (select count(*)::int from users where role='patron' and is_active) active_patrons,(select count(*)::int from users where role='worker') workers,(select count(*)::int from categories) categories,(select count(*)::int from products) products,(select count(*)::int from sales) sales,(select count(*)::int from sale_items) sale_items,(select count(*)::int from stock_movements) stock_movements,(select count(*)::int from refresh_tokens) refresh_tokens,(select count(*)::int from menu_import_sessions) menu_import_sessions,(select count(*)::int from products where stock<0) negative_stock`)).rows[0];if(counts.active_patrons!==1||counts.sales||counts.sale_items||counts.stock_movements||counts.refresh_tokens||counts.menu_import_sessions||counts.negative_stock)throw new Error('Les invariants post-préparation ont échoué.');await client.query('commit');console.log(JSON.stringify({database:actual,counts,settings_note:'Identité, Wi-Fi et texte de ticket effacés pour révision; réglages imprimante/système conservés.',uploads_note:'Aucun fichier supprimé; nettoyage des orphelins à confirmer séparément.'},null,2));}catch(error){await client.query('rollback');throw error}finally{await client.end()}
