import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent } from 'react'
import { Banknote, Bike, ChefHat, Coffee, Package, Plus, Printer, Search, ShoppingCart, Store, Utensils, X } from 'lucide-react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { getCategories } from '../api/categories'
import { getCurrentCashRegister } from '../api/cash-register'
import { appendOrderItems, createOrder, getOrders, getPublicMenu, getTables, payOrder, type PublicMenuProduct } from '../api/core-v2'
import { createProduct, getProducts } from '../api/products'
import { getSale } from '../api/sales'
import { defaultSettings, getPublicSettings, type AppSettings } from '../api/settings'
import { useAuth } from '../auth/useAuth'
import ErrorMessage from '../components/ErrorMessage'
import Loading from '../components/Loading'
import Receipt from '../components/Receipt'
import { useI18n } from '../i18n'
import type { Category, Product, RestaurantTable, Sale, UniversalOrder } from '../types'
import { resolveAssetUrl } from '../api/client'
import { formatCurrency, getApiErrorMessage } from '../utils/format'
import { isTauriRuntime, nativePrintSale } from '../utils/nativePrint'

type OrderMode = 'retail' | 'dine_in' | 'counter' | 'takeaway' | 'delivery'
type CartLine = { key:string; product:Product; quantity:number; unitPrice:number; variantId:number|null; variantName:string|null; modifierIds:number[]; modifierNames:string[]; notes:string }
type OptionDraft = { product:Product; options:PublicMenuProduct; variantId:number|null; modifierIds:number[]; notes:string }
type QuickProduct = { name:string; salePrice:string; categoryId:string; barcode:string; sku:string; stock:string; trackStock:boolean; unit:string }

const quickProductInitial:QuickProduct={name:'',salePrice:'',categoryId:'',barcode:'',sku:'',stock:'0',trackStock:true,unit:'piece'}
const hospitalityTypes=new Set(['cafe','restaurant'])
const productManagerRoles=new Set(['patron','owner','admin','manager','stock_manager'])
const paymentRoles=new Set(['patron','owner','admin','manager','worker','cashier'])
const tableRoles=new Set(['patron','owner','admin','manager','waiter'])
const emptyFeatures:string[]=[]
const productImage=(product:Product)=>resolveAssetUrl(product.image_url||product.image)

export default function CommandesPage(){
  const {t}=useI18n(),{user}=useAuth(),navigate=useNavigate(),[searchParams,setSearchParams]=useSearchParams(),searchRef=useRef<HTMLInputElement>(null)
  const business=user?.business,role=user?.role??'',features=business?.enabled_features??emptyFeatures,hospitality=hospitalityTypes.has(business?.business_type??'')
  const requestedMode=searchParams.get('mode')as OrderMode|null
  const allowedModes:OrderMode[]=['counter',...(features.includes('tables')&&tableRoles.has(user?.role??'')?['dine_in' as const]:[]),...(features.includes('takeaway')?['takeaway' as const]:[]),...(features.includes('delivery')?['delivery' as const]:[])]
  const mode:OrderMode|null=hospitality?(requestedMode&&allowedModes.includes(requestedMode)?requestedMode:null):'retail'
  const selectedTableId=mode==='dine_in'?Number(searchParams.get('table')||0):0
  const [categories,setCategories]=useState<Category[]>([]),[products,setProducts]=useState<Product[]>([]),[tables,setTables]=useState<RestaurantTable[]>([]),[orders,setOrders]=useState<UniversalOrder[]>([])
  const [publicOptions,setPublicOptions]=useState<Map<number,PublicMenuProduct>>(new Map()),[settings,setSettings]=useState<AppSettings>(defaultSettings),[cart,setCart]=useState<CartLine[]>([])
  const [selectedCategory,setSelectedCategory]=useState(''),[search,setSearch]=useState(''),[notFound,setNotFound]=useState<string|null>(null),[paymentMethod,setPaymentMethod]=useState<'cash'|'card'|'other'>('cash')
  const [orderNote,setOrderNote]=useState(''),[discount,setDiscount]=useState('0'),[registerOpen,setRegisterOpen]=useState(false),[receiptSale,setReceiptSale]=useState<Sale|null>(null)
  const [optionDraft,setOptionDraft]=useState<OptionDraft|null>(null),[quickProduct,setQuickProduct]=useState<QuickProduct|null>(null),[isLoading,setIsLoading]=useState(true),[isSubmitting,setIsSubmitting]=useState(false),[isPrinting,setIsPrinting]=useState(false)
  const [error,setError]=useState<string|null>(null),[success,setSuccess]=useState<string|null>(null)
  const canCreateProduct=productManagerRoles.has(role),canPay=paymentRoles.has(role),inventoryEnabled=features.includes('inventory')
  const selectedTable=tables.find(table=>table.id===selectedTableId)??null

  const loadData=useCallback(async()=>{try{setError(null);const canUseTables=hospitality&&features.includes('tables')&&tableRoles.has(role);const[categoryRows,productRows,appSettings,currentRegister,tableRows,orderRows]=await Promise.all([getCategories(),getProducts(),getPublicSettings().catch(()=>defaultSettings),getCurrentCashRegister().catch(()=>null),canUseTables?getTables():Promise.resolve([]),canUseTables?getOrders():Promise.resolve([])]);setCategories(categoryRows);setProducts(productRows);setSettings(appSettings);setRegisterOpen(Boolean(currentRegister));setTables(tableRows);setOrders(orderRows)}catch(value){setError(getApiErrorMessage(value))}finally{setIsLoading(false)}},[features,hospitality,role])
  useEffect(()=>{void loadData()},[loadData])
  useEffect(()=>{let active=true;async function loadOptions(){if(!selectedTable?.qr_token||!features.includes('qr_menu')){setPublicOptions(new Map());return}try{const menu=await getPublicMenu(selectedTable.qr_token);if(active)setPublicOptions(new Map(menu.products.map(product=>[product.id,product])))}catch{if(active)setPublicOptions(new Map())}}void loadOptions();return()=>{active=false}},[features,selectedTable?.id,selectedTable?.qr_token])
  useEffect(()=>{if(mode&&(mode!=='dine_in'||selectedTableId))window.setTimeout(()=>searchRef.current?.focus(),50)},[mode,selectedTableId])

  const activeProducts=useMemo(()=>products.filter(product=>product.is_active),[products])
  const visibleProducts=useMemo(()=>{const term=search.trim().toLocaleLowerCase();return activeProducts.filter(product=>(!selectedCategory||String(product.category_id??'')===selectedCategory)&&(!term||`${product.name} ${product.barcode??''} ${product.sku??''}`.toLocaleLowerCase().includes(term)))},[activeProducts,search,selectedCategory])
  const activeOrders=useMemo(()=>orders.filter(order=>!['completed','cancelled'].includes(order.status)),[orders])
  const editingOrder=selectedTableId?activeOrders.find(order=>order.table_id===selectedTableId)??null:null
  const cartSubtotal=cart.reduce((sum,line)=>sum+line.quantity*line.unitPrice,0),subtotal=(editingOrder?.subtotal??0)+cartSubtotal,discountValue=editingOrder?.discount??Math.min(cartSubtotal,Math.max(0,Number(discount)||0)),total=editingOrder?editingOrder.total+cartSubtotal:cartSubtotal-discountValue,cartCount=cart.reduce((sum,line)=>sum+line.quantity,0)

  function chooseMode(nextMode:OrderMode){setCart([]);setSuccess(null);setError(null);setSearchParams({mode:nextMode})}
  function chooseTable(table:RestaurantTable){setSearchParams({mode:'dine_in',table:String(table.id)})}
  function configuredPrice(product:Product,options:PublicMenuProduct,variantId:number|null,modifierIds:number[]){return product.sale_price+(options.variants.find(item=>item.id===variantId)?.price??0)+options.modifiers.filter(item=>modifierIds.includes(item.id)).reduce((sum,item)=>sum+item.price,0)}
  function addConfiguredProduct(product:Product,configuration?:Omit<CartLine,'key'|'product'|'quantity'>){if(product.available===false||(product.track_stock&&product.stock<=0))return;const line=configuration??{unitPrice:product.sale_price,variantId:null,variantName:null,modifierIds:[],modifierNames:[],notes:''},key=`${product.id}:${line.variantId??''}:${line.modifierIds.slice().sort((a,b)=>a-b).join(',')}:${line.notes}`;setCart(current=>{const existing=current.find(item=>item.key===key);if(!existing)return[...current,{...line,key,product,quantity:1}];if(product.track_stock&&existing.quantity>=product.stock)return current;return current.map(item=>item.key===key?{...item,quantity:item.quantity+1}:item)});setNotFound(null);setSuccess(t('pos.added',{product:product.name}));window.setTimeout(()=>setSuccess(null),1200)}
  function selectProduct(product:Product){const options=publicOptions.get(product.id);if(options&&!options.available)return;if(options&&(options.variants.length||options.modifiers.length)){setOptionDraft({product,options,variantId:null,modifierIds:[],notes:''});return}addConfiguredProduct(product)}
  function confirmOptions(){if(!optionDraft||(optionDraft.options.variants.length&&!optionDraft.variantId))return;const{product,options,variantId,modifierIds,notes}=optionDraft;addConfiguredProduct(product,{unitPrice:configuredPrice(product,options,variantId,modifierIds),variantId,variantName:options.variants.find(item=>item.id===variantId)?.name??null,modifierIds,modifierNames:options.modifiers.filter(item=>modifierIds.includes(item.id)).map(item=>item.name),notes});setOptionDraft(null)}
  function searchOrScan(event:FormEvent<HTMLFormElement>){event.preventDefault();const value=search.trim();if(!value)return;const exact=activeProducts.find(product=>product.barcode?.toLocaleLowerCase()===value.toLocaleLowerCase()||product.sku?.toLocaleLowerCase()===value.toLocaleLowerCase()),candidate=exact??(visibleProducts.length===1?visibleProducts[0]:null);if(candidate){selectProduct(candidate);setSearch('');return}if(!visibleProducts.length)setNotFound(value)}
  function changeQuantity(key:string,delta:number){setCart(current=>current.map(line=>line.key===key?{...line,quantity:line.quantity+delta}:line).filter(line=>line.quantity>0))}
  function startQuickProduct(){const value=notFound??search.trim(),looksLikeCode=/^\d{4,}$/.test(value);setQuickProduct({...quickProductInitial,name:looksLikeCode?'':value,barcode:looksLikeCode?value:'',stock:inventoryEnabled?'1':'0',trackStock:inventoryEnabled})}
  async function saveQuickProduct(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!quickProduct)return;if(inventoryEnabled&&quickProduct.trackStock&&Number(quickProduct.stock)<=0){setError(t('pos.quickStockRequired'));return}setIsSubmitting(true);setError(null);try{const payload=new FormData();payload.append('name',quickProduct.name.trim());payload.append('sale_price',String(Number(quickProduct.salePrice)));payload.append('category_id',quickProduct.categoryId);payload.append('barcode',quickProduct.barcode.trim());payload.append('sku',quickProduct.sku.trim());payload.append('stock',String(inventoryEnabled?Number(quickProduct.stock):0));payload.append('min_stock','0');payload.append('track_stock',inventoryEnabled&&quickProduct.trackStock?'true':'false');payload.append('unit',quickProduct.unit);payload.append('tax_rate','0');payload.append('is_active','true');payload.append('is_public','true');payload.append('available','true');const created=await createProduct(payload);setProducts(current=>[...current,created]);setQuickProduct(null);setSearch('');setNotFound(null);addConfiguredProduct(created)}catch(value){setError(getApiErrorMessage(value))}finally{setIsSubmitting(false)}}
  const cartItems=()=>cart.map(line=>({product_id:line.product.id,variant_id:line.variantId,modifier_ids:line.modifierIds,quantity:line.quantity,discount:0,tax:0,notes:line.notes.trim()||null}))
  function orderPayload(){return{client_id:crypto.randomUUID(),source:mode==='dine_in'?'employee_table':'pos',type:mode==='counter'?'dine_in':mode??'retail',table_id:selectedTableId||null,payment_status:'unpaid',discount:discountValue,tax:0,notes:orderNote.trim()||null,items:cartItems()}}
  function appendPayload(){return{client_id:crypto.randomUUID(),items:cartItems()}}
  async function submit(payNow:boolean){if(!cart.length||isSubmitting)return;if(payNow&&!registerOpen){setError(t('pos.registerRequired'));return}setIsSubmitting(true);setError(null);setSuccess(null);try{const created=editingOrder?await appendOrderItems(editingOrder.id,appendPayload()):await createOrder(orderPayload());if(payNow){const paid=await payOrder(created.id,paymentMethod),sale=await getSale(paid.sale_id);setReceiptSale(sale);setSuccess(t('pos.saleCompleted'));window.dispatchEvent(new Event('cash-register-changed'))}else setSuccess(features.includes('kitchen')&&mode!=='retail'?t('pos.sentToKitchen'):t('pos.orderSaved'));setCart([]);setOrderNote('');setDiscount('0');await loadData();if(!payNow&&selectedTableId)navigate('/tables')}catch(value){setError(getApiErrorMessage(value))}finally{setIsSubmitting(false)}}
  function printReceipt(){if(!receiptSale)return;if(isTauriRuntime()){setIsPrinting(true);nativePrintSale(receiptSale,settings,2).catch(value=>setError(getApiErrorMessage(value))).finally(()=>setIsPrinting(false));return}document.body.classList.add('ticket-print-mode');document.body.style.setProperty('--ticket-page-width',settings.ticket_width===58?'58mm':'80mm');const finish=()=>{document.body.classList.remove('ticket-print-mode');document.body.style.removeProperty('--ticket-page-width');window.removeEventListener('afterprint',finish)};window.addEventListener('afterprint',finish);window.print()}
  function newSale(){setReceiptSale(null);setSuccess(null);setSearch('');if(hospitality)setSearchParams({});window.setTimeout(()=>searchRef.current?.focus(),50)}
  if(isLoading)return <Loading label={t('pos.loading')}/>

  if(hospitality&&!mode)return <section className="pos-start-page"><div className="page-title"><div><h2>{t('pos.newOrder')}</h2><p>{t('pos.chooseService')}</p></div></div><div className="service-mode-grid">{features.includes('tables')&&tableRoles.has(user?.role??'')?<button onClick={()=>chooseMode('dine_in')}><Utensils/><strong>{t('pos.dineIn')}</strong><span>{t('pos.dineInHelp')}</span></button>:null}<button onClick={()=>chooseMode('counter')}><Coffee/><strong>{t('pos.counter')}</strong><span>{t('pos.counterHelp')}</span></button>{features.includes('takeaway')?<button onClick={()=>chooseMode('takeaway')}><Package/><strong>{t('pos.takeaway')}</strong><span>{t('pos.takeawayHelp')}</span></button>:null}{features.includes('delivery')?<button onClick={()=>chooseMode('delivery')}><Bike/><strong>{t('pos.delivery')}</strong><span>{t('pos.deliveryHelp')}</span></button>:null}</div></section>
  if(mode==='dine_in'&&!selectedTableId)return <section className="pos-start-page"><div className="page-title"><div><h2>{t('pos.chooseTable')}</h2><p>{t('pos.chooseTableHelp')}</p></div><button className="button secondary" onClick={()=>setSearchParams({})}>{t('common.back')}</button></div>{!tables.length?<div className="empty-state operational-empty"><h3>{t('pos.noTables')}</h3><button className="button" onClick={()=>navigate('/tables')}>{t('pos.configureTables')}</button></div>:<div className="pos-table-grid">{tables.map(table=>{const activeOrder=activeOrders.find(order=>order.table_id===table.id);return <button className={activeOrder?'occupied':''} key={table.id} onClick={()=>chooseTable(table)}><span><small>{table.room_name}</small><strong>{table.name}</strong><em>{t(activeOrder?'pos.tableOccupied':'pos.tableAvailable')}</em></span>{activeOrder?<b>{formatCurrency(activeOrder.total)}</b>:<Plus/>}</button>})}</div>}</section>

  const modeLabel=t(`pos.mode.${mode??'retail'}`)
  return <section className="commandes-page pos-workspace">
    <div className="page-title pos-title"><div><small>{editingOrder?editingOrder.order_number:hospitality?t('pos.newOrder'):t('pos.checkout')}</small><h2>{selectedTable?selectedTable.name:modeLabel}</h2><p>{t(hospitality?'pos.orderSubtitle':'pos.retailSubtitle')}</p></div><div className="page-title-actions"><span className={`badge ${registerOpen?'success':'warning'}`}>{t(registerOpen?'header.registerOpen':'header.registerClosed')}</span><button className="button secondary" onClick={()=>navigate('/sales')}><Store size={17}/>{t('pos.manageRegister')}</button>{hospitality?<button className="button secondary" onClick={()=>setSearchParams({})}>{t('pos.changeService')}</button>:null}</div></div>
    <ErrorMessage message={error}/>{success?<div className="success-message" role="status">{success}</div>:null}
    <div className="command-layout"><main className="command-menu"><form className="pos-search" onSubmit={searchOrScan}><Search aria-hidden="true"/><input ref={searchRef} autoComplete="off" aria-label={t('pos.searchLabel')} onChange={event=>{setSearch(event.target.value);setNotFound(null);setError(null)}} placeholder={t('pos.searchPlaceholder')} value={search}/><button className="button" type="submit">{t('pos.searchAction')}</button></form>
      <div className="worker-category-grid pos-categories"><button className={`worker-category-card ${!selectedCategory?'active':''}`} onClick={()=>setSelectedCategory('')} type="button"><span className="worker-category-placeholder">{t('orders.all').slice(0,1)}</span><strong>{t('orders.all')}</strong></button>{categories.map(category=><button className={`worker-category-card ${selectedCategory===String(category.id)?'active':''}`} key={category.id} onClick={()=>setSelectedCategory(String(category.id))} type="button"><span className="worker-category-placeholder">{category.name.charAt(0).toUpperCase()}</span><strong>{category.name}</strong></button>)}</div>
      {notFound||(search.trim()&&!visibleProducts.length)?<div className="product-not-found"><Search/><h3>{t('pos.productNotFound')}</h3><p>{canCreateProduct?t('pos.productNotFoundManager'):t('pos.productNotFoundRestricted')}</p>{canCreateProduct?<button className="button" onClick={startQuickProduct}><Plus size={18}/>{t('pos.createProduct')}</button>:null}</div>:visibleProducts.length?<div className="worker-products-grid command-products">{visibleProducts.map(product=>{const unavailable=product.available===false||(product.track_stock&&product.stock<=0),image=productImage(product);return <button className="worker-product-card command-product" disabled={unavailable} key={product.id} onClick={()=>selectProduct(product)} type="button">{image?<img alt="" className="worker-product-image" src={image}/>:<span className="worker-product-placeholder">{product.name.charAt(0).toUpperCase()}</span>}<span className="product-card-name">{product.name}</span><b>{formatCurrency(product.sale_price)}</b><span className={`badge ${unavailable?'warning':'muted'}`}>{unavailable?t('orders.outOfStock'):product.track_stock?t('pos.stockCount',{count:product.stock}):t('pos.available')}</span></button>})}</div>:<div className="empty-state">{t('orders.noActiveProducts')}</div>}
    </main><aside className="command-cart"><div className="panel-title"><div><h3>{t('orders.cart')}</h3><span>{t('pos.itemCount',{count:cartCount})}</span></div><ShoppingCart/><span className="cart-count">{cartCount}</span></div>
      {cart.length?<div className="cart-list">{cart.map(line=><article className="cart-item" key={line.key}><div className="cart-item-head"><div><strong>{line.product.name}</strong>{line.variantName?<small>{line.variantName}</small>:null}{line.modifierNames.length?<small>{line.modifierNames.join(', ')}</small>:null}<span>{formatCurrency(line.unitPrice)}</span></div><b>{formatCurrency(line.quantity*line.unitPrice)}</b></div><div className="qty-controls"><button className="qty-button" aria-label={t('pos.decrease')} onClick={()=>changeQuantity(line.key,-1)}>-</button><strong>{line.quantity}</strong><button className="qty-button" aria-label={t('pos.increase')} disabled={line.product.track_stock&&line.quantity>=line.product.stock} onClick={()=>changeQuantity(line.key,1)}>+</button><button className="qty-button remove" aria-label={t('common.delete')} onClick={()=>setCart(current=>current.filter(item=>item.key!==line.key))}><X size={16}/></button></div><input aria-label={t('pos.lineNote')} className="cart-line-note" onChange={event=>setCart(current=>current.map(item=>item.key===line.key?{...item,notes:event.target.value}:item))} placeholder={t('pos.lineNote')} value={line.notes}/></article>)}</div>:<div className="empty-state cart-empty"><ShoppingCart/><p>{t('orders.empty')}</p></div>}
      <label>{t('pos.orderNote')}<input disabled={Boolean(editingOrder)} onChange={event=>setOrderNote(event.target.value)} value={editingOrder?.notes??orderNote}/></label><label>{t('pos.discount')}<input disabled={Boolean(editingOrder)} min="0" onChange={event=>setDiscount(event.target.value)} step="0.01" type="number" value={editingOrder?String(editingOrder.discount):discount}/></label>{canPay?<label>{t('orders.payment')}<select value={paymentMethod} onChange={event=>setPaymentMethod(event.target.value as typeof paymentMethod)}><option value="cash">{t('payment.cash')}</option><option value="card">{t('payment.card')}</option><option value="other">{t('payment.other')}</option></select></label>:null}
      <div className="cart-totals"><span>{t('pos.subtotal')}<b>{formatCurrency(subtotal)}</b></span><span>{t('pos.discount')}<b>- {formatCurrency(discountValue)}</b></span><span>{t('pos.tax')}<b>{t('pos.included')}</b></span><strong>{t('orders.total')}<b>{formatCurrency(total)}</b></strong></div><div className="pos-primary-actions">{hospitality?<button className="button secondary" disabled={!cart.length||isSubmitting} onClick={()=>void submit(false)}>{features.includes('kitchen')&&mode!=='retail'?<><ChefHat size={18}/>{t('pos.sendKitchen')}</>:t('pos.saveOrder')}</button>:null}{canPay?<button className="button command-submit" disabled={!cart.length||isSubmitting||!registerOpen} onClick={()=>void submit(true)}><Banknote size={19}/>{isSubmitting?t('orders.validating'):t('pos.pay')}</button>:null}</div>{!registerOpen&&canPay?<p className="disabled-explanation">{t('pos.registerRequired')} <button onClick={()=>navigate('/sales')}>{t('orders.openRegister')}</button></p>:null}
    </aside></div>
    {optionDraft?<div className="modal-backdrop" role="presentation"><section aria-modal="true" className="modal-content product-options-modal" role="dialog"><button aria-label={t('common.cancel')} className="icon-button modal-close" onClick={()=>setOptionDraft(null)}><X/></button><h2>{optionDraft.product.name}</h2>{optionDraft.options.variants.length?<fieldset><legend>{t('pos.chooseVariant')}</legend>{optionDraft.options.variants.map(variant=><label key={variant.id}><input checked={optionDraft.variantId===variant.id} name="variant" onChange={()=>setOptionDraft({...optionDraft,variantId:variant.id})} type="radio"/><span>{variant.name}</span><b>+ {formatCurrency(variant.price)}</b></label>)}</fieldset>:null}{optionDraft.options.modifiers.length?<fieldset><legend>{t('pos.chooseModifiers')}</legend>{optionDraft.options.modifiers.map(modifier=><label key={modifier.id}><input checked={optionDraft.modifierIds.includes(modifier.id)} onChange={()=>setOptionDraft({...optionDraft,modifierIds:optionDraft.modifierIds.includes(modifier.id)?optionDraft.modifierIds.filter(id=>id!==modifier.id):[...optionDraft.modifierIds,modifier.id]})} type="checkbox"/><span>{modifier.name}</span><b>+ {formatCurrency(modifier.price)}</b></label>)}</fieldset>:null}<label>{t('pos.lineNote')}<textarea onChange={event=>setOptionDraft({...optionDraft,notes:event.target.value})} value={optionDraft.notes}/></label><button className="button" disabled={Boolean(optionDraft.options.variants.length&&!optionDraft.variantId)} onClick={confirmOptions}>{t('pos.addToCart')}</button></section></div>:null}
    {quickProduct?<div className="modal-backdrop" role="presentation"><form aria-modal="true" className="modal-content quick-product-modal" onSubmit={saveQuickProduct} role="dialog"><button aria-label={t('common.cancel')} className="icon-button modal-close" onClick={()=>setQuickProduct(null)} type="button"><X/></button><div><small>{t('pos.withoutLeavingSale')}</small><h2>{t('pos.quickProduct')}</h2></div><div className="form-grid two-columns"><label>{t('products.name')} *<input autoFocus required value={quickProduct.name} onChange={event=>setQuickProduct({...quickProduct,name:event.target.value})}/></label><label>{t('products.salePrice')} *<input min="0" required step="0.01" type="number" value={quickProduct.salePrice} onChange={event=>setQuickProduct({...quickProduct,salePrice:event.target.value})}/></label><label>{t('products.category')}<select value={quickProduct.categoryId} onChange={event=>setQuickProduct({...quickProduct,categoryId:event.target.value})}><option value="">{t('products.noCategory')}</option>{categories.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>{t('pos.barcode')}<input value={quickProduct.barcode} onChange={event=>setQuickProduct({...quickProduct,barcode:event.target.value})}/></label><label>SKU<input value={quickProduct.sku} onChange={event=>setQuickProduct({...quickProduct,sku:event.target.value})}/></label><label>{t('pos.unit')}<select value={quickProduct.unit} onChange={event=>setQuickProduct({...quickProduct,unit:event.target.value})}>{['piece','kg','gram','liter','ml','pack','box','custom'].map(unit=><option key={unit} value={unit}>{t(`unit.${unit}`)}</option>)}</select></label>{inventoryEnabled?<><label>{t('pos.initialStock')}<input min="0" step="1" type="number" value={quickProduct.stock} onChange={event=>setQuickProduct({...quickProduct,stock:event.target.value})}/></label><label className="checkbox-line"><input checked={quickProduct.trackStock} onChange={event=>setQuickProduct({...quickProduct,trackStock:event.target.checked})} type="checkbox"/>{t('products.trackStock')}</label></>:null}</div><div className="modal-actions"><button className="button secondary" onClick={()=>setQuickProduct(null)} type="button">{t('common.cancel')}</button><button className="button" disabled={isSubmitting}>{isSubmitting?t('orders.validating'):t('pos.createAndAdd')}</button></div></form></div>:null}
    {receiptSale?<div className="modal-backdrop no-print" role="presentation"><section aria-modal="true" className="modal-content receipt-modal" role="dialog"><div className="panel-title no-print"><div><h2>{t('pos.paymentSuccess')}</h2><p>{t('pos.readyNext')}</p></div><button aria-label={t('common.cancel')} className="icon-button" onClick={()=>setReceiptSale(null)}><X/></button></div><Receipt sale={receiptSale} settings={settings}/><div className="modal-actions no-print"><button className="button secondary" disabled={isPrinting} onClick={printReceipt}><Printer size={18}/>{isPrinting?t('orders.printing'):t('pos.printReceipt')}</button><button className="button" onClick={newSale}><Plus size={18}/>{t('pos.newSale')}</button></div></section></div>:null}
  </section>
}
