import{useEffect,useMemo,useState}from'react'
import{Bell,Check,ChevronLeft,Minus,Plus,ReceiptText,ShoppingBag,X}from'lucide-react'
import{useParams}from'react-router-dom'
import{createQrOrder,createTableEvent,getPublicMenu,type PublicMenu,type PublicMenuProduct}from'../api/core-v2'
import{useI18n,type Language}from'../i18n'

type CartLine={key:string;product:PublicMenuProduct;variantId:number|null;modifierIds:number[];quantity:number;notes:string;unitPrice:number}
type Draft={product:PublicMenuProduct;variantId:number|null;modifierIds:number[];quantity:number;notes:string}

export default function PublicMenuPage(){
  const{t,language,setLanguage}=useI18n()
  const{slug='',token=''}=useParams(),[menu,setMenu]=useState<PublicMenu|null>(null),[cart,setCart]=useState<CartLine[]>([]),[draft,setDraft]=useState<Draft|null>(null),[category,setCategory]=useState<number|null>(null),[message,setMessage]=useState(''),[submitting,setSubmitting]=useState(false),[cartOpen,setCartOpen]=useState(false)
  useEffect(()=>{getPublicMenu(slug,token).then(value=>{setMenu(value);setCategory(value.categories[0]?.id??null)}).catch(()=>setMessage(t('publicMenu.unavailable')))},[slug,t,token])
  const total=useMemo(()=>cart.reduce((sum,line)=>sum+line.unitPrice*line.quantity,0),[cart]),count=cart.reduce((sum,line)=>sum+line.quantity,0)
  const draftPrice=draft?draft.product.sale_price+(draft.product.variants.find(v=>v.id===draft.variantId)?.price??0)+draft.product.modifiers.filter(m=>draft.modifierIds.includes(m.id)).reduce((sum,m)=>sum+m.price,0):0
  function add(){if(!draft)return;const key=`${draft.product.id}:${draft.variantId??''}:${draft.modifierIds.slice().sort().join(',')}:${draft.notes}`;setCart(current=>{const existing=current.find(line=>line.key===key);return existing?current.map(line=>line.key===key?{...line,quantity:line.quantity+draft.quantity}:line):[...current,{key,...draft,unitPrice:draftPrice}]});setDraft(null);setCartOpen(true)}
  async function service(type:'call_waiter'|'request_bill'){await createTableEvent(slug,token,type);setMessage(t(type==='call_waiter'?'publicMenu.waiterCalled':'publicMenu.billSent'))}
  async function submit(){if(!cart.length)return;setSubmitting(true);try{const order=await createQrOrder(slug,token,{client_id:crypto.randomUUID(),items:cart.map(line=>({product_id:line.product.id,variant_id:line.variantId,quantity:line.quantity,notes:line.notes||null,modifier_ids:line.modifierIds}))});setCart([]);setCartOpen(false);setMessage(t('publicMenu.orderSent',{order:order.order_number,table:menu?.table.name??''}))}finally{setSubmitting(false)}}
  if(!menu)return <main className="public-menu-loading"><p>{message||t('publicMenu.loading')}</p></main>
  const products=menu.products.filter(product=>category===null||product.category_id===category)
  const tableLabel=menu.table.name.includes(menu.table.number)?menu.table.name:`${menu.table.name} · ${t('common.table')} ${menu.table.number}`
  return <main className="public-menu">
    <header className="public-menu-header"><div><small>{tableLabel} · {menu.table.room}</small><h1>{menu.business.name}</h1></div><label className="language-selector"><span className="sr-only">{t('language.label')}</span><select aria-label={t('language.label')} value={language} onChange={event=>setLanguage(event.target.value as Language)}><option value="fr">FR</option><option value="en">EN</option><option value="ar">AR</option></select></label><div className="public-service-actions"><button onClick={()=>void service('call_waiter')}><Bell/>{t('publicMenu.callWaiter')}</button><button onClick={()=>void service('request_bill')}><ReceiptText/>{t('publicMenu.requestBill')}</button></div></header>
    {message?<div className="public-message"><Check/>{message}<button aria-label={t('common.close')} onClick={()=>setMessage('')}><X/></button></div>:null}
    <nav className="public-category-tabs" aria-label={t('publicMenu.categories')}>{menu.categories.map(item=><button className={category===item.id?'active':''} key={item.id} onClick={()=>setCategory(item.id)}>{item.name}</button>)}</nav>
    <section className="public-menu-content"><div className="public-products">{products.map(product=><button className="public-product-card" disabled={!product.available} key={product.id} onClick={()=>setDraft({product,variantId:product.variants[0]?.id??null,modifierIds:[],quantity:1,notes:''})}>{product.image?<img src={product.image} alt=""/>:<div className="public-product-placeholder"><ShoppingBag/></div>}<span><strong>{product.name}</strong><small>{t(product.available?'publicMenu.available':'publicMenu.unavailableProduct')}</small></span><b>{product.sale_price.toFixed(2)} {menu.business.currency}</b></button>)}{!products.length?<div className="empty-state">{t('publicMenu.noProducts')}</div>:null}</div></section>
    <button className="public-cart-button" disabled={!count} onClick={()=>setCartOpen(true)}><ShoppingBag/><span>{t('publicMenu.cart',{count})}</span><strong>{total.toFixed(2)} {menu.business.currency}</strong></button>
    {draft?<div className="public-sheet-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target)setDraft(null)}}><section className="public-product-sheet"><button className="public-sheet-close" aria-label={t('common.back')} onClick={()=>setDraft(null)}><ChevronLeft/></button>{draft.product.image?<img className="public-detail-image" src={draft.product.image} alt=""/>:null}<h2>{draft.product.name}</h2><strong className="public-detail-price">{draftPrice.toFixed(2)} {menu.business.currency}</strong>{draft.product.variants.length?<fieldset><legend>{t('publicMenu.chooseVariant')}</legend>{draft.product.variants.map(variant=><label key={variant.id}><input checked={draft.variantId===variant.id} name="variant" onChange={()=>setDraft({...draft,variantId:variant.id})} type="radio"/><span>{variant.name}</span><small>{variant.price?`+ ${variant.price.toFixed(2)} ${menu.business.currency}`:t('publicMenu.included')}</small></label>)}</fieldset>:null}{draft.product.modifiers.length?<fieldset><legend>{t('publicMenu.extras')}</legend>{draft.product.modifiers.map(modifier=><label key={modifier.id}><input checked={draft.modifierIds.includes(modifier.id)} onChange={()=>setDraft({...draft,modifierIds:draft.modifierIds.includes(modifier.id)?draft.modifierIds.filter(id=>id!==modifier.id):[...draft.modifierIds,modifier.id]})} type="checkbox"/><span>{modifier.name}</span><small>+ {modifier.price.toFixed(2)} {menu.business.currency}</small></label>)}</fieldset>:null}<label className="public-note">{t('publicMenu.kitchenNote')}<textarea placeholder={t('publicMenu.kitchenPlaceholder')} value={draft.notes} onChange={event=>setDraft({...draft,notes:event.target.value})}/></label><div className="public-add-row"><div className="quantity-stepper"><button onClick={()=>setDraft({...draft,quantity:Math.max(1,draft.quantity-1)})}><Minus/></button><strong>{draft.quantity}</strong><button onClick={()=>setDraft({...draft,quantity:draft.quantity+1})}><Plus/></button></div><button className="button" onClick={add}>{t('publicMenu.add',{amount:`${(draftPrice*draft.quantity).toFixed(2)} ${menu.business.currency}`})}</button></div></section></div>:null}
    {cartOpen?<div className="public-sheet-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target)setCartOpen(false)}}><aside className="public-cart-sheet"><div className="public-sheet-title"><div><small>{menu.table.name}</small><h2>{t('publicMenu.yourOrder')}</h2></div><button aria-label={t('common.close')} onClick={()=>setCartOpen(false)}><X/></button></div>{cart.map(line=><article key={line.key}><span><strong>{line.quantity} × {line.product.name}</strong>{line.notes?<small>{line.notes}</small>:null}</span><b>{(line.unitPrice*line.quantity).toFixed(2)} {menu.business.currency}</b><button aria-label={t('common.delete')} onClick={()=>setCart(current=>current.filter(item=>item.key!==line.key))}><X/></button></article>)}<div className="public-cart-total"><span>{t('orders.total')}</span><strong>{total.toFixed(2)} {menu.business.currency}</strong></div><button className="button public-submit-order" disabled={!cart.length||submitting} onClick={()=>void submit()}>{t(submitting?'publicMenu.sending':'publicMenu.sendOrder')}</button></aside></div>:null}
  </main>
}
